### ISSUE TITLE
OMEMO Encrypted Jingle File Transfer (XEP-xxxx)

### ISSUE THREAD

**Issue by tristan-k** [monal-im/Monal#10]
> Jingle File Transfer (XEP-0234) describes a very flexible and powerful method for peer-to-peer file transfer with interchangable transports. Unfortunatly only some of those transports can by encrypted (e.g. Jingle In-Band Bytestreams Transport Method (XEP-0261) and none integrate into existing end-to-end encryption schemes. This specification defines an approach to encrypt the actual file before transferring it by using the OMEMO encryption. Note that the encryption can and should happen on the fly.
- https://xmpp.org/extensions/inbox/omemo-filetransfer.html
- https://conversations.im/xeps/omemo-filetransfer.html

**Comment by tmolitor-stud-tu** [comment]
This is a wontfix, because we won't implement jingle filetransfers at all (just use XEP-0363: HTTP File Upload instead)

**Comment by Echolon** [comment]
But don't one need jingle for calls and voice messages?
