### ISSUE TITLE
[Bug]: Since updating MacOS, Monal crashes immediately after starting

### ISSUE THREAD

**Issue by pieniunikko** [monal-im/Monal#1015]
### What Monal Release channel are you using?

AppStore

### iOS system version

--

### iOS Monal version

--

### macOS system version

14.4

### macOS Monal version

6.1.1

### Used XMPP server (domain)

prefer not to say

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

23.10

### How many accounts are you using in Monal?

1

### What happened?

Hi there, since updating to MacOS Sonoma 14.4 (23E214) on Thursday/Friday, Monal "starts" (the dot under the application appears) but crashes immediately. I never get to even see the interface. No idea what's wrong...

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please update to the latest monal version (6.2.0).
