### ISSUE TITLE
[Bug]: When the contact has no published OMEMO keys, Monal sends a known unusable message

### ISSUE THREAD

**Issue by linkmauve** [monal-im/Monal#1017]
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

jabber.fr

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

trunk changeset 95d8875c90dc

### How many accounts are you using in Monal?

1

### What happened?

The person using Monal tried to send me that stanza, probably because she forgot to disable OMEMO manually, but Monal shouldn’t let her send it anyway since it can’t be actioned on the other side:
```xml
<message type="chat" xml:lang="en" to="*me*@*my-server*" id="A7F8FB0C-33C4-4BB6-9B9E-1DA499C30470" from="*her*@*her-server*/Monal-iOS.*id*">
    <origin-id xmlns="urn:xmpp:sid:0" id="A7F8FB0C-33C4-4BB6-9B9E-1DA499C30470" />
    <body>[This message is OMEMO encrypted]</body>
    <encryption xmlns="urn:xmpp:eme:0" name="OMEMO" namespace="eu.siacs.conversations.axolotl" />
    <request xmlns="urn:xmpp:receipts" />
    <markable xmlns="urn:xmpp:chat-markers:0" />
    <store xmlns="urn:xmpp:hints" />
</message>
```

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by matthewrfennell** [comment]
I'm not associated with Monal, just interested in this issue. I was able to replicate this.

* Monal Stable 6.2.0 (895) on jabber.fr
* Profanity (no OMEMO keys configured) on another Prosody server

Every time I opened the chat with the profantiy user, it showed this alert:

![116B1D8C-8C01-415D-AB2E-BBD59560FB7F_125f9fb47f87939b4e33dec020d082a848384ed2](https://github.com/monal-im/Monal/assets/148400980/e5f046f3-1deb-47ff-a100-8bf6e9f3748f)

* If I chose "Ignore" I got the same as you.
* If I chose "Disable Encryption" I could send unencrypted messages fine.
* If I tried to re-enable encryption, it wouldn't let me:

![A2C959AA-8659-4891-898C-C7BF7B77AC99_7dd976daedfdfe5cf0d527771efbf4854d33b66a](https://github.com/monal-im/Monal/assets/148400980/00430bfe-a4da-4e70-b0ed-82fb6278a142)

Is it an option to remove the "Ignore" button from the first popup, and disable OMEMO entirely until the keys are properly configured?

I had a look at Conversations, Gajim and Siskin and they all (in various ways) prevent you entirely from sending OMEMO-encrypted messages in this scenario.

I'm open to working on this too if that helps, though I'd need approval from my job first.

**Comment by FriedrichAltheide** [comment]
> Is it an option to remove the "Ignore" button from the first popup, and disable OMEMO entirely until the keys are properly configured?

No. Instead the error message could be improved. Something like
- Monal was unable to lookup the encryption keys of <placeholder>
- Please check if you and <placeholder> added each other into your contact lists
- Note, the contact may not support encrypted chats using OMEMO. If that is the case you can only contact <placeholder> using unencrypted messages

But that would be a wall of text...

> I had a look at Conversations, Gajim and Siskin and they all (in various ways) prevent you entirely from sending OMEMO-encrypted messages in this scenario.

When rewriting the chat UI this could/should be improved.

**Comment by gunwixor** [comment]
I am unable to add new contacts via Monal. Same error about the keys. None of my contacts use xmmp. I am using JMP.chat 

I add contacts via Dino. Sent messages from Dino appear in Monal but with an error 

Stable 6.2.0

**Comment by tmolitor-stud-tu** [comment]
@lowviz You are unable to add contacts?
This issue is about a warning message related to encryption that can be ignored (and prevents you from sending messages if you ignore it).

--> If the warning message pops up, just don't select ignore.
