### ISSUE TITLE
[Bug]: Menu-States of "Edit > Spelling & Grammar" are weirdly checked/set upon reentering a/the TextEdit field

### ISSUE THREAD

**Issue by TiBooX** [monal-im/Monal#1034]
### What Monal Release channel are you using?

AppStore

### iOS system version

17.4.1

### iOS Monal version

Stable 6.2.0 (895)

### macOS system version

13.6.6

### macOS Monal version

Stable 6.2.0 (895)

### Used XMPP server (domain)

private (will not disclose)

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4 Linux

### How many accounts are you using in Monal?

1

### What happened?

**macOS Version only:**
Usually after the (sub)menuItems : in "Edit > Spelling & Grammar" come from the disabled state they are checked (with a checkmark) again and again even it I unchecked them a thousand times before.
Suggestion: Please read Apple's TextField documentation at least the fist concept pages (don't avoid the provided delegates/callbacks) since it looks as if you were making assumptions and manual state changes that result in fighting with the OS.
_This is completely reproducable. I haven't found any workaround._

### Anything else?

In the Edit (Bearbeiten) Menu <img width="718" alt="Bildschirmfoto 2024-04-15 um 20 46 29" src="https://github.com/monal-im/Monal/assets/1352573/2faead5d-b219-456e-9cfc-b60beae1042c">

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [x] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by TiBooX** [comment]
I'm not happy about filing a macOS-UI-Bug and having to fill in irellevant XMPP and private Server Information, iOS Version and OS Monal Verions here? Why are they mandatory to send a macOS-UI-only-bug-report? It almost kept me from submitting this bug. Feels like English bureaucracy. 42.

**Comment by tmolitor-stud-tu** [comment]
I assume you mean the text input field in an open chat. If so I can't reproduce your problem in macOS 14.4.1 (M1 processor).

We don't make any assumptions nor do we set anything regarding spell checking at all.
We only implement 3 `UITextView` delegates: [`textViewDidBeginEditing:`](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/chatViewController.m#L2882), [`textView:shouldChangeTextInRange:replacementText:`](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/chatViewController.m#L2887) and [`textViewDidChange:`](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/chatViewController.m#L2905).

[This documentation](https://developer.apple.com/documentation/uikit/uitextviewdelegate?language=objc) says that all `UITextView` delegates are purely optional. 

That said: if you really think it's a bug in Monal and no obscure Catalyst related bug in MacOS, feel free to create a PR or send us a patch via mail etc.
I'm happy to merge that.

Regarding your second message: neither your iOS/macOS version nor the Monal version are mandatory. In fact most of the fields are optionally. But you are right, at least the Monal version should be mandatory for every bug report, I'll change that.
Regarding the other mandatory fields: Often a user is not able to distinguish a pure UI error from an error involving the XMPP server/protocol. And I don't want to manually ask for all these values for the vast majority of error reports, so they are mandatory.
