### ISSUE TITLE
[Bug]: custom chat backgrounds not showing even though its set

### ISSUE THREAD

**Issue by jjj333-p** [monal-im/Monal#1043]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.5 dev beta 2

### Monal version

Beta 6.3.0 (897)

### Used XMPP server (domain)

h2.gay

### Which XMPP-Server software are you using?

Prosody

### How many accounts are you using in Monal?

1

### What happened?

I was on the stable version (from appstore), i set a chat background and it showed up. i installed the testflight in place and there is no more custom background. i tried changing it to see if it just bugged the data but it still doesnt show. 

heres a video of it happening: https://share.icloud.com/photos/094ftu8djyPe_MpViGh47UALg

will send logs over email

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
@zainashraf1562 I suspect that's something you broke when changing colors etc. Could you look into it?

**Comment by zainashraf1562** [comment]
I'll look into it :)

**Comment by jjj333-p** [comment]
just wanted to note that when i installed the testflight update it did fix this :+1: 

meant to write before the next ones came out but uni got the best of me
