### ISSUE TITLE
[Bug]: Spurious MUC OMEMO alerts

### ISSUE THREAD

**Issue by roge** [monal-im/Monal#1051]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.4.1

### Monal version

Stable 6.3.0 (900)

### Used XMPP server (domain)

creep.im

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

23.01-1

### How many accounts are you using in Monal?

1

### What happened?

Every time I open one of my MUCs, I get a modal alert message that reads:

> #### No OMEMO keys found
>
> This contact may not support OMEMO encrypted messages. Please try to enable encryption again in a few seconds, if you think this is wrong.

The only way to dismiss this message and proceed to the chat is to tap "**Disable Encryption**".

This is quite annoying since it appears every time I open this MUC. This did not occur in prior versions. If I tap the lock in the upper right after tapping "Disable Encryption", everything seems to work correctly (including OMEMO).

### Anything else?

I believe this recent change might have something to do with this issue: https://github.com/monal-im/Monal/commit/282a2cc40e6273f5ae41a2aac71bf753f1cc03a9

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Are these MUCs closed group chats or an open channels?

**Comment by roge** [comment]
> Are these MUCs closed group chats or an open channels?

Gajim shows the same MUC as "members only".
