### ISSUE TITLE
[Bug]: cannot clear storage space

### ISSUE THREAD

**Issue by grgq** [monal-im/Monal#1060]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

14.8.1

### macOS system version (if applicable)

13.4.1

### Monal version

6.3.1

### Used XMPP server (domain)

conversations.im

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

2

### What happened?

Trying to backup iphone.  Iphone storage shows monal consuming 1.36 gigs.  I cannot uninstall and reinstall as I am unwilling to install the new ios until I complete an icloud backup.  I am not self hosting xmpp.

how do I discard much of the "documents & data" of monal?  I am not interested in retaining any of the media received in conversations threads.

### Anything else?

should there not be a simple way to purge storage.  I searched issues and faq for 'storage'

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
You can clear the chat history of individual chats or of the whole account.
That will remove all downloaded media, too.
