### ISSUE TITLE
[Bug]: messages still appears as omemo and cant be uncrypted

### ISSUE THREAD

**Issue by lm2lm2** [monal-im/Monal#1061]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

15

### Monal version

6.2.0 895

### Used XMPP server (domain)

jabber.chaosbern.ch + others

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

A problem happened!
this : 
![4f1cfa68_E3FDA94E-6692-4FF0-959A-91EAC44E0915](https://github.com/monal-im/Monal/assets/125938702/82dfc5ae-f9c5-43d8-be47-89c417a26e6e)
![ed3b7e63_55489C3D-094F-4A29-8384-2C8F11E718C9](https://github.com/monal-im/Monal/assets/125938702/24bf830a-88d4-40d0-a3e2-0377237d5a96)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
That's not a Monal bug:

These users aren't encrypting the messages for decryption with your device.
Make sure they trust your OMEMO key/fingerprint.

**Comment by lm2lm2** [comment]
> That's not a Monal bug:
> 
> These users aren't encrypting the messages for decryption with your device. Make sure they trust your OMEMO key/fingerprint.

ty for your reply
but
it's doing it only with non-conversations.im client..
how could i check omemo?
it's very strange

**Comment by Echolon** [comment]
Hi @tmolitor-stud-tu 

It also recently happened to me. Messages that came from an Monal device were not decrypted (however, Monocles did decrypt)

![IMG_0183](https://github.com/monal-im/Monal/assets/29168011/b884e106-d6ac-40a0-9e1e-215cd2dac482)

**Comment by tmolitor-stud-tu** [comment]
As I said, make sure the sender trusts the fingerprint for this device id.
You can view the fingerprint corresponding to your own deviceid in Settings --> Your Account --> Keys (OMEMO) (the device having no toggle is your current device).

Then check if that fingerprint is turned on on the sending device.
