### ISSUE TITLE
[Bug]: Links are opened in Safari instead of the default browser app e.g. Firefox

### ISSUE THREAD

**Issue by chschwerdt** [monal-im/Monal#1062]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.5.1

### Monal version

6.3.1

### Used XMPP server (domain)

x.y.z

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

If you click on a link in a message, the link is opened in Safari. 
As in other apps, the default browser should be used.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Fixed in https://github.com/monal-im/Monal/commit/f605172988eb0b00baf8a7993294340527cc1b6d
