### ISSUE TITLE
[Minor]: New Device ID notification

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#1071]
### What Monal Release channel are you using?

AppStore

### Monal version

> 6.0

### Used XMPP server (domain)

jabbers.one

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Just a general question if this information is required as push notification? Most user don't know what it means anyway.

Maybe it could be shown only in app, but not on the lock screen. What do you think?

![IMG_0181](https://github.com/monal-im/Monal/assets/29168011/5016b229-c0d2-405a-b505-301743635c9e)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
This is important, because it means a new OMEMO device was added to your account and is now able to read all encrypted messages sent to/from your account.

It is less useful on first login, so changed the code to not show these messages on first login: https://github.com/monal-im/Monal/commit/d1806cccdb828d8f78ab9ccdcca1af94c25419a4
