### ISSUE TITLE
[Minor]: User experience when first time login OMEMO infomation is loaded

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#1072]
### What Monal Release channel are you using?

AppStore

### Monal version

> 6.0

### Used XMPP server (domain)

jabbers.one

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

I wanted to discuss what is happening in this screen.

1. I log in the first time.
2. Some OMEMO data is being loaded for about 2 minutes
3. The number counting in not intuitive (kind of reverse order)
4. Why is this shown to the user and why does this take so long? I cannot remember other clients taking so long.

I general its not helpful for the user experience I think.

![IMG_0177](https://github.com/monal-im/Monal/assets/29168011/47beee63-2a60-48c6-94c9-006218c21eb7)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Monal first discovers the device ids of every contact (that's the phase when mainly the count after the slash increases), after that it fetches the key bundles for all discovered devices (that's when mainly the counter before the slash increases).

Only after loading all these key bundles you will be able to send encrypted messages to your contacts. That's the reason why we do it on first login.

Conversations does this when you try to write the first message to a contact, which shows a similar blocking ui until the keys of this contact are loaded. I don't like the Conversations experience.

If you have a fast internet connection and/or your contacts have few devices, that should not take 2 minutes...for me, a test with 53 devices took only ~11 seconds with the whole login process taking ~20 seconds.

**Comment by Echolon** [comment]
> Monal first discovers the device ids of every contact (that's the phase when mainly the count after the slash increases), after that it fetches the key bundles for all discovered devices (that's when mainly the counter before the slash increases).
> 
> Only after loading all these key bundles you will be able to send encrypted messages to your contacts. That's the reason why we do it on first login.
> 
> Conversations does this when you try to write the first message to a contact, which shows a similar blocking ui until the keys of this contact are loaded. I don't like the Conversations experience.
> 
> If you have a fast internet connection and/or your contacts have few devices, that should not take 2 minutes...for me, a test with 53 devices took only ~11 seconds with the whole login process taking ~20 seconds.

I was on a 5G connection :man_shrugging: 

But my point was not to prevent the loading. It was the user experience I would rework. Just show a progress bar for first setup of the app or so. I would reopen the issue.

**Comment by tmolitor-stud-tu** [comment]
The progress bar would jump a lot because key bundles are fetched while still discovering new ones.
You can easily observe that yourself: the number on the right increases even when the number on the left is greater than zero.

I don't think a progress bar resembles a better user experience than showing a `<count> / <total>` message. And no, even a percent message would jump around.
