### ISSUE TITLE
[Bug]: Keyboard should not hide chat in the background

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#1073]
### What Monal Release channel are you using?

AppStore

### Monal version

> 6.0

### Used XMPP server (domain)

jabbers.one

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

The keyboard hides the chat in the background.

It would be better if an appearing keyboard would move the chat up the same way instead of having it in the background.

![IMG_0182](https://github.com/monal-im/Monal/assets/29168011/6e5b7c1e-86b2-4519-8a93-44bd5e65f8f9)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Already fixed in current beta. Btw: Monal 6.0 is rather old, the current version is 6.3.1 and the current beta is 6.4.0.
