### ISSUE TITLE
[Bug]: regression in group chat creation and inviting members

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1080]
### What Monal Release channel are you using?

Alpha

### iOS system version (if applicable)

16.7

### Monal version

6.4.0 rc2 (908) commit f0dae09

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

1

### What happened?

There's a regression between build 907 and build 908, probably introduced in 11ffdb9
On build 908, when trying to create a group chat (even an empty one with no name), Monal's UI gets stuck on "Creating Group" with the spinning animation, until you click on the back arrow on the top left.
However, the MUC is created instantly, albeit without the specified name, or the specified members (they don't get an MUC invitation, nor do they get added to the member list)

Similarly, when trying to add a member to the group chat, the Monal UI gets stuck on "Adding new member adding `friend@example.org`". Though you can see on the background that a new entry was added.
If you go back and enter the member list again, you find the recently added member greyed out, with "(offline)" next to their affiliation.
However, the contact does not get the MUC invite.
You need to invite them again for them to receive the invite.
(If they accept it they're no longer shown as "offline" in the member list)

On build 907, the contact gets the invitation the first time you invite them. No need to do it twice.

semi-related note:
If the invitee declines the invitation, they stay in the member list as "offline" (not sure what the spec says about this case. Maybe the contact should've been removed from the member list?)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Thanks for your detailed description!
I think its line 1723 in the commit you already identified. That line should call the other function with a nil argument for callback instead of doing nothing.

Am 15. Juni 2024 07:42:42 MESZ schrieb lissine0 ***@***.***>:

**Comment by lissine0** [comment]
I confirm it's fixed with the latest commit. Thanks!
