### ISSUE TITLE
[Bug]: Can't invite prosody server admins to chatrooms in their server

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1085]
### What Monal Release channel are you using?

Alpha

### iOS system version (if applicable)

16.7

### Monal version

6.4.0

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

1

### What happened?

In prosody, by default, admin accounts are granted `owner` affiliation in any chatroom they enter (that belongs to their server).
See https://prosody.im/doc/modules/mod_muc#admin-privileges

This results in an error when trying to invite a prosody server admin to a chatroom: Monal tries to grant them `member` affiliation, but they can only be `owner`.
The error message is:
 `Failed to change affiliation of 'admin@example.org' in 'room@conference.example.org' to 'member': not-acceptable`

Note that what happens depends on when we try to invite the prosody admins:
-If we invite them at room creation, we see the error above, but they're added to the room with `owner` affiliation, as should be.
-If we invite them _after_ the room was already created, we get the error above but the prosody admin is not added to the room.
Note that Gajim and Conversations handle this correctly i.e. the prosody admin gets added to the room as `owner`.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Well, Monal adds the user to the group first (member affiliation) before sending out the direct invite and if that does not work, it does not send a (then useless) direct invite.

This prosody setting is a special case.
IMHO Prosody should accept any affiliation adding the admin to a muc they aren't already in and automatically promote them to owner. And only respond with an error message if the admin is already in the room (e.g. when it's a true affiliation change and not adding a new user).

Direct invites have the benefit that the inviter can be used to determine the trustworthiness of the invite (e.g. check if the inviter is in my roster before automatically entering the muc etc.).
Mediated invites can be spoofed --> a spammer's muc can just use any jid as the inviter.

**Comment by mwild1** [comment]
We have been planning to deprecate this behaviour for some time - we made it optional in the last release, and the next release will now disable it by default: https://hg.prosody.im/trunk/rev/3e6d5738ea09

This change won't be backported to 0.12, though a new major release is not far away.

**Comment by tmolitor-stud-tu** [comment]
Since is's now fixed on the prosody side, I'll close this issue now.
