### ISSUE TITLE
[Feature]: Implement dynamic UI updates for our OMEMO keys list

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#1101]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Make the whole `OmemoKeys.swift` file dynamic by adding several `[[MLNotificationQueue currentQueue] postNotificationName:[...] object:self.account userInfo:@{[...]}];` notifications to `MLOMEMO.m` and using them in the omemo view by `.onReceive(NotificationCenter.default.publisher(for: NSNotification.Name("[...]")).receive(on: RunLoop.main)) { notification in [...] }`

The view should dynamically show all changes in trust, and newly added or removed keys as well as newly added or removed users in a group (and their keys).

@matthewrfennell That one could be something for you, I guess :)

**Comment by tmolitor-stud-tu** [comment]
Notification names can be defined in `MLConstants.h`

**Comment by tmolitor-stud-tu** [comment]
can this be closed now or is still something missing?

**Comment by matthewrfennell** [comment]
Still missing one more thing unfortunately, which is making sure the device trust is synced (it could even be working at the moment,but I haven't tested it). I haven't started that yet, but should be able to take a look this weekend.

**Comment by matthewrfennell** [comment]
Actually, I think this can be closed after all :)
I had mistakenly thought that device trust was synced between devices. But, if I mark a device as trusted, nothing gets sent to the server.
So, since we have handled the other two cases, I think we are now syncing everything we can.

**Comment by tmolitor-stud-tu** [comment]
Perfect, thanks!! :)
