### ISSUE TITLE
[Feature]: Use Geometry Reader and SmartScrollView in Register and Login views

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#1108]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Use the following code in `WelcomeLogin.swift` and `Register.swift` to make the forms take the whole available space while still being properly scrollable instead of hardcoding their heights.

```
GeometryReader { proxy in
    SmartScrollView(.vertical, showsIndicators: true, optionalScrolling: true, shrinkToFit: false) {
        VStack(alignment: .leading) {
        }
        /// Sets the minimum frame height to the available height of the scrollview and the maxHeight to infinity
        .frame(minHeight: proxy.size.height, maxHeight: .infinity)
    }
}
```

**Comment by lissine0** [comment]
Note: the WelcomeLogin is still shown the same as before, for me on Beta 6.4.3 (973) using macOS 12.7.4

Default Monal window dimensions:
![screenshot](https://github.com/user-attachments/assets/f2b89e1f-be83-4b6a-b06e-0ba846fd4fbd)

Maximum window dimensions (not fullscreen):
![screenshot_fullscreen](https://github.com/user-attachments/assets/57686fb2-340b-4972-8d8d-e78ded3c327f)

**Comment by lissine0** [comment]
FYI the onboarding screen needs to be scrolled to show the next button on macos with a resolution of 1366x766
![screenshot2](https://github.com/user-attachments/assets/b851d409-0774-4d93-8f15-56043a480aed)

**Comment by tmolitor-stud-tu** [comment]
I know, I didn't manage to fully fix it, feel free to do it yourself :)

Am 6. August 2024 14:21:53 MESZ schrieb lissine0 ***@***.***>:
