### ISSUE TITLE
Monal onboarding: some titles don't fit on small screen iphones

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1113]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

16.7

### Monal version

6.4.1rc2 (919)

### What happened?

The titles of these two screens don't fit on 4.7 inch iphones e.g. iphone SE (2nd and 3rd gen)
![welcome](https://github.com/user-attachments/assets/713a040d-4a23-41c5-a25e-dcf486133c80)
![even-more](https://github.com/user-attachments/assets/36115cb0-d346-423c-9c11-d7ada9b67b8e)

But the features page's title fits:
![features](https://github.com/user-attachments/assets/b1018c72-78b2-46a5-9eb2-12b736134a15)

CC @thevaidik

**Comment by tmolitor-stud-tu** [comment]
That seems to be an iOS 16 bug, on iOS 17 the text is wrapped into a second line if its too long
