### ISSUE TITLE
[Bug]: messages sent to public channels are shown with locks, as if encrypted

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1115]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

16.7

### Monal version

6.4.1rc2 (919)

### Used XMPP server (domain)

Personal

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

3

### What happened?

When using public channels, the encryption icon in the top right is greyed out and the icon is a locked lock (as if E2EE is enabled)
Consequently, messages sent from Monal to public channels get displayed with a lock in their bottom-left corner, giving users the false impression that they're OMEMO encrypted.
![1115](https://github.com/user-attachments/assets/51727c56-466d-4208-84e9-fae4d5374601)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
I can't reproduce this. All my public channels behave just fine.

**Comment by lissine0** [comment]
Perhaps because you logged in to Monal from those accounts a long time ago.
Try a fresh install of Monal (for example reinstall the alpha build) or perhaps log in with a new account

**Comment by tmolitor-stud-tu** [comment]
Okay, I managed to reproduce this in alpha with the monal-alpha channel

**Comment by lissine0** [comment]
> Okay, I managed to reproduce this in alpha with the monal-alpha channel

Here's my theory:
Previously, you could set / unset omemo encryption for public channels (though it might've resulted in errors IIRC)
At some point in the past few months, a commit disabled that action.
So, the last value of the Omemo Encryption Setting per channel was saved.
Now, joining new channels or using new accounts gets you the default, which is Omemo Enabled.
That's why you got the lock, because it was a new channel that you recently joined.

**Comment by tmolitor-stud-tu** [comment]
No, its more subtle: when creating a new muc its type is set to "channel" per database default.
Later on when initializing that muc on join, the code checks if the type in database differs from the type of the muc its currently joining and updates the type in database, if so.
That database update in turn checks if the type is "channel" and sets encryption to off, if so.

Since the database default was "channel", the check if the db differs from the real muc didn't trigger for channel type mucs and thus the encryption setting was never updated.

**Comment by lissine0** [comment]
Confirmed fixed with the latest commit, thanks!
