### ISSUE TITLE
[Bug]: Monal to Monal OMEMO encryption doesn't work

### ISSUE THREAD

**Issue by verbit** [monal-im/Monal#1153]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

16.7.8

### macOS system version (if applicable)

14.4

### Monal version

6.4.1

### Used XMPP server (domain)

draugr.de

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

We have the very weird issue that OMEMO encryption doesn't work when both ends use the Monal app. For some reason, the Monal's OMEMO key is not recognized by the other end and vice versa. We tested Monal (iOS) <-> Monal (iOS) and Monal (iOS) <-> Monal (macOS). In both cases it's not working.

When the other end uses another client, like Monal<->Gajim or Monal<->Conversejs, then it works.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Please send in logfiles of both iOS devices to debug this further: https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging

Send them via email to info@monal-im.org and include the jids of both accounts.

**Comment by verbit** [comment]
Done.

I sent you the log files from the one iOS device and the macOS device. I don't have access to the other iOS device.

**Comment by tmolitor-stud-tu** [comment]
That's okay, thanks!

**Comment by tmolitor-stud-tu** [comment]
Can you tell me which omemo deviceids the two devices you sent me the log of have?

**Comment by verbit** [comment]
The current** ones are:

- iOS: 520568234
- macOS: 1645153921

** I used to delete and re-add the account on the iOS device in trying to resolve the issue, which regenerated the device ID IIRC

**Comment by tmolitor-stud-tu** [comment]
ah okay, then this ids won't be of much use...

What exactly do you mean by "delete and re-add the account"? You removed the contact or you removed the entire account on the device (under Settings --> [your account name] --> Remove Account from this Device) so that monal was fresh?

**Comment by tmolitor-stud-tu** [comment]
Can you provide a screenshot of the server details of your server (Settings --> [your account name] --> Protocol support of your Server)?

**Comment by verbit** [comment]
> you removed the entire account on the device (under Settings --> [your account name] --> Remove Account from this Device) so that monal was fresh

This

**Comment by verbit** [comment]
> Can you provide a screenshot of the server details of your server (Settings --> [your account name] --> Protocol support of your Server)?

There you go
![IMG_3138](https://github.com/user-attachments/assets/2d92cc27-f49c-4d79-85a0-4a20f3333915)
![IMG_3139](https://github.com/user-attachments/assets/9012fda9-78ca-4e7e-9ef1-1d129582d0db)
![IMG_3140](https://github.com/user-attachments/assets/e4657dd7-6a77-4029-a5c8-38f4cc56d086)
![IMG_3141](https://github.com/user-attachments/assets/396365e6-8185-4b64-bf39-aea2eaf87868)
![IMG_3142](https://github.com/user-attachments/assets/07fb0916-3af1-44a2-b93c-88643125621a)
![IMG_3143](https://github.com/user-attachments/assets/7248c0a8-1b8e-4ded-98cf-b9abe38799f9)

**Comment by tmolitor-stud-tu** [comment]
The server is too old, pubsub (which is used for omemo) won't work properly on this server. Please use at least ejabberd 23.10, as per https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins
The yellowish XEP-0163 entry in your screenshot indicates this, too.

**Why is omemo working between Monal and other clients?**
Because omemo is self-healing and if one device can get the keys of the other device an encrypted session will be created, but between Monal <--> Monal on the same old server, none of the two clients is able to get the keys of the other party, so no one is able to initiate the encrypted session.

> **Use backports for Debian to get recent enough versions and bugfixes!**

**Comment by tmolitor-stud-tu** [comment]
I added a workaround in https://github.com/monal-im/Monal/commit/dd6435740fedf6a9ccf8f927ab49ea76b04f4738 that will make it into the 6.4.2 stable coming out in a few days.
