### ISSUE TITLE
No Sound is played on incoming new message [Bug]: 

### ISSUE THREAD

**Issue by Hajo5** [monal-im/Monal#1156]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.5.1

### macOS system version (if applicable)

14.5

### Monal version

6.4.1

### Used XMPP server (domain)

jabber.de

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12 (23-09-06 on linux)

### How many accounts are you using in Monal?

1

### What happened?

No Sound is played on incoming new message on iOS an none on macOS, on the other side (Pidgin client) typing is seen and tones are heard.

### Anything else?

XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are displayed blue, Contact is NOT muted and Messages are OMEMO encrypted.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Go to Settings --> Sounds and select a sound to be played on incoming messages.

You will not hear sounds or get notifications for messages received in a chat currently open in foreground. And keep in mind that you have to unmute your phone.

**Comment by tmolitor-stud-tu** [comment]
Oh, and make sure to turn the volume of your device up, not just unmute it.

**Comment by Hajo5** [comment]
Many thanks for your prompt help, this resolved my problem.
1) Sounds are only to expected, wen the app has no Focus.
2) The iMac remained silent never the less, only the icon in the doc got a red point that increased the number with each new message. 
I did not receive acoustic notations for new eMails either. After changing the sound for new email to anything apart from nothing, incoming emails and also Monal Messages  are announced. (With different sounds, as specified in their respective settings). 
Not sure, why this should have an effect, the truth is, in "Systemeinstellungen" - "Benachrichtigungen" everything was on, only after setting "Mail" "Einstellungen" "Allgemein" "Ton für neue Emails" to a value other than "Ton für neue Emails" (=empty default) everything started to bing. Great!
