### ISSUE TITLE
[Feature]: Streamline code

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#1188]
- [x] The current code has different names for the same thing: `isGroup` in `MLContact`, but `isMuc` in `MLMessage`. Use `isMuc` everywhere.
- [x] `mucType` is named same in both files, but is a `NSString`. Make this an enum having the values `channel` and `group` (and unknown, if the db has the value NULL for this information which is needed to trigger a proper update, see 4ac649597f31187cd2fb663d43cdd9d9dc84dd29).
- [x] Rename `connectedAccounts` (and `connectedAccount`) to `enabledAccounts` (`enabledAccount`) everywhere
- [x] Use `accountID` as `NSNumber` everywhere (not `accountId` or `accountNo` and not as `NSString` either).

**Comment by tmolitor-stud-tu** [comment]
@lissine0 This is complete, right?

**Comment by lissine0** [comment]
Yes it is complete (though someone may want to switch from String constants to enums at some point)
