### ISSUE TITLE
[Bug]: Beta builds are no longer published for iOS

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1198]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

16.7

### What happened?

Testflight shows 6.4.2 (963) as the latest available version for iOS, and it shows 6.4.3 (973) as the latest available version for macOS.
![testflight](https://github.com/user-attachments/assets/7314a682-2412-4060-96c1-12a79a74150f)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Tell apple to finish the review more quickly, its still pending since Sunday...

Am 6. August 2024 15:44:27 MESZ schrieb lissine0 ***@***.***>:
