### ISSUE TITLE
[Bug]: The app crashes on downloading Media.

### ISSUE THREAD

**Issue by ghost** [monal-im/Monal#1202]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

17.5.1

### Monal version

6.4.3 (973) / Testflight

### Used XMPP server (domain)

bla.bla.bla

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.07

### How many accounts are you using in Monal?

1

### What happened?

I receive media (picture or Video).
I click download
File gets downloaded
As soon as thumnail appears, the app crashes
I cant send mail report because "something with email adress..."

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by matthewrfennell** [comment]
Thanks for reporting this!

I was able to replicate this on `develop`, ejabberd 24.07 (conversations.im), and iOS 18 on an iPhone 15 Pro simulator.
Error only appears for me when I turn off "auto-download media and files".
git bisect reports that `2745c8f6` introduced the regression (although interestingly, reverting that commit on top of `develop` doesn't fix the issue). Taking a look to see if I can figure it out now.

https://github.com/user-attachments/assets/35a018a4-821e-44ab-aabe-bcd415a99838

**Comment by ghost** [comment]
thank you!
Waiting for a fix.
I noticed something strange.
I do have auto download enabled but it gets ignored:meaning I have to click the attachment to download

**Comment by ghost** [comment]
![IMG_0617](https://github.com/user-attachments/assets/abd228f0-ff49-4fc8-8632-8db4434e7a78)

**Comment by tmolitor-stud-tu** [comment]
Fixed in 0d30fbaa8d0a519d9d4a9cf612e5f53b98186b1a
