### ISSUE TITLE
[Feature]: move the "audio message" record button

### ISSUE THREAD

**Issue by lm2lm2** [monal-im/Monal#1273]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

as everytime i send a text message
if i push a bit long on the send button
just after there is the micro icon for audio message button.. .at the same place
results it starts recording, and when stopped, automatically sent

it's too easy to send audio messages accidentally with this way.

is it possible to move somewhere else this button/feature?

thank you

**Comment by tmolitor-stud-tu** [comment]
Will be solved once the new chatview is there.
