### ISSUE TITLE
[Bug]: Leaving channels while syncing history makes Monal consider them 1-1 chats

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1275]
### What Monal Release channel are you using?

Alpha

### iOS system version (if applicable)

16.7

### Monal version

Alpha ef56a94 (Oct 15 2024)

### Used XMPP server (domain)

personal

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

2

### What happened?

I connected to the internet after being offline for ~3 days, and Monal was syncing history from chats.
I left a channel while it was syncing history, and it disappeared from the `Chats` view for a moment, and then popped up again to finish syncing history until the most recent message.
As mentioned in the title, the chat is now considered a normal contact i.e. there's a call button, and in the `Contact details` view there's an `Add Contact` button instead of `Join Channel` or `Leave Channel`
I tried to leave another channel that was also still syncing history and the same thing happened. So it seems that this bug is reproducible.

Workaround: you can go to the `Contact details`, click `Add Contact` and the go to the `Contacts` view, swipe the entry and `Remove Contact`

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
I think I know whats causing this: incoming type=groupchat messages aren't ignored if we don't know a groupchat having that jid (just like handling 1:1 jids which we also don't ignore if we don't have them in our roster).

**Comment by tmolitor-stud-tu** [comment]
Okay, never mind. That should be already fixed in 7bce655f58f6bbcdcf2153e8bd4c2690592f4260, specifically this line: https://github.com/monal-im/Monal/blob/develop/Monal/Classes/MLMessageProcessor.m#L250
