### ISSUE TITLE
Onboarding: User should be invited to register a new or existing account (Welcome screen)

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#128]
#### Introduction

Today I tested the first time Monal on a friends device. My first impression wasn't that good. Two accounts couldn't really connect, so I only got an "offline" experience. Cannot tell what the problem was :/
However, I somehow used to managed to add a new account. And that's a problem. New users _(and probably new users to XMPP)_ don't know anything about this network. They even don't know what a good server is or that they need an ID. So, I think it should be make much easier for them to get started. They are used to being guided and introduced to knew "fancy" apps. We should guide and introduce them to the "fancy" Jabber world - syrsly! :smiley: 

The ideal setup would be, that I recommend Monal to a friend, and just tell them to send my ID or register mine. No extra help needed from my side.

#### Suggestions

- Add a welcome screen: Maybe you can checkout clients like Conversations or it's Pix-art fork. Those have a welcome screen. You can add your existing account or register to a new server. If they create a new account, it should be all compliant. You can let them choose, but the default suggestion should be a good experience. Especially for iPhone users.

- [Your ideas]

I additionally relate to this, which is more specific: #127 implement XEP-0379: Pre-Authenticated Roster Subscription

Cheers & thanks for the development

**Comment by anurodhp** [comment]
Yup I was actually in the process of making a new login screen that should work for most people.  There is a screenshot st monal.im right now. 
I am also planning on adding onbiarding tutorial screens.

**Comment by anurodhp** [comment]
Also, thanks for your suggestions.  At the end of the day I am an engineer not a UI/UX person so despite my best efforts I am literally blind to things.

**Comment by anurodhp** [comment]
I send people here when they click register:
https://monal.im/welcome-to-xmpp/

jabb3r and Jabber.at at the moment but I can add mode

**Comment by Echolon** [comment]
blabber.im just gave me their OK!

**Comment by Echolon** [comment]
Even if Monal doesn't may support the missing XEPs from https://compliance.conversations.im/ I would only recommend 100% servers. Hot-Chill only has 88%. With regards to OMEMO in Monal, this might become an issue. And I suggest to give people a sufficient expierence right away. If they want, they still can switch the server.

**Comment by Echolon** [comment]
jabber.de gave me their okay, too. It's a prosody server FYI

**Comment by Echolon** [comment]
Many server expect solving of Captchas when registering. I thing this must be adressed, too in the welcome screen

**Comment by anurodhp** [comment]
I am steering clear of in-band registration and just sending people to web pages

**Comment by Echolon** [comment]
You mean you don't wanna support inband registration?

**Comment by anurodhp** [comment]
yeah it appears that a lot of servers block it due to spam

**Comment by Echolon** [comment]
Hm okay. Was wondering because Pix-art enables direct captcha resolving.

However, nice approach about welcome screen!
What I was actually intending, is not only explaining why the list is empty (but which is good!). I rather was talking about an introduction screen. Something you see the first time when you open Monal. It should help you to get along with xmpp in general

**Comment by anurodhp** [comment]
yup intro screens are up too. 
https://monal.im/blog/the-welcome-screen/

I'll probably refine this more as I get more feedback from people.  Im hoping the changes make things less hostile to new users.

**Comment by Echolon** [comment]
Anu - this is AWESOME! Really nice! Will look in detail the next days. But so far I'm happy you managed to build this!

**Comment by Echolon** [comment]
Hey Anu,

as there is no possibility to register a new account within Monal after installing the app, I would like to ask to **reopen** this thread.

I'd suggest to add a `Register new account` button below those options:

<img src="https://user-images.githubusercontent.com/29168011/55551948-51ff7200-56dc-11e9-8915-b63b2a043bbc.png" width="250">

In a new screen, I would then:

- Directly suggest a **good default server** which supports all necessary XEPs. (For example, www.blabber.im are happy to gain new users, they also have a decent website and hosting. But a new @monal.im server could do it as well)
--> Therefore, people don't need to choose their domain, but only their name
Blabber or Pix-art do it like this: 
<img src="https://user-images.githubusercontent.com/29168011/55552241-2fba2400-56dd-11e9-951e-bae0230b8332.png" width="250">

- Of course let them define a **password**
   May inform them about specific expectations like: 
    -- Minimum length of 2 characters
    -- This is case insensitive: macbeth is the same that MacBeth and Macbeth.
    -- Characters not allowed: " & ' / : < > @ 

- I'd also would ask them to **choose a nickname** which will be displayed to other contacts

- Extra point: Lots of user just forget their passwords by time. So if they come back to Monal and type their domain and passwort a hint which adresses them to their domains contact website or **support website** to reset their passwort could prevent them being stucked. For example: https://blabber.im/kontakt/

- Another extra point: Let them pic an **avatar**


I hope this helps a little bit.

Thank you for your work and efforts!

**Comment by Echolon** [comment]
@anurodhp 
Regarding the new Registration, I set up a checklist :smile: 
https://monal.im/blog/registration/

- [X] Directly suggest a **good default server** (blabber.im)
- [ ] Add a **nice text** on top to explain that this account will offer independent and decentralized communication. Maybe combine it with the welcome screen
- [ ] The explaination of "What the ID is" should be rather in a design like this:
**Enter:**
**__ _your nickname_ __ @blabber.im**
Once they finally created their accout, confirm in an extra screen, like: "Hurray! Your ID is _your nickname_@blabber.im  Have lots of fun!"
- [ ] Show a list with some **other choices** of (hopefully) good servers (https://compliance.conversations.im/)
- [ ] Field: **Choose your name** - This can be set before the ID creation. The ID could also be suggested as 'Name' + random 3 digits number (Name: Bob, ID: bob543@blabber.im)
- [ ] Show reference to provider's **support website** if the password forgotten (hard coding in the beginning I'd suggest)

PS: I **wouldn't** offer auto-gen passwords. Has bad drawback and effectively no chance of reminding passwords! Also remind the advises for a secure password (or in review of limits from blabber.im)

**Comment by licaon-kter** [comment]
https://blog.prosody.im/great-invitations/
