### ISSUE TITLE
[Feature] Add the ability to enter a password when joining password protected room/channel

### ISSUE THREAD

**Issue by ellienieuwdorp** [monal-im/Monal#1285]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Not sure if this is a bug or a missing feature, but I am unable to join a password protected room.

When attempting to join the following message is displayed: “Failed to enter Group/Channel [channel jid] not-authorized”. With no ability to input the password anywhere.

![IMG_1480](https://github.com/user-attachments/assets/57ce1c99-5e05-4b9c-93fa-f655bae20a81)

**Comment by licaon-kter** [comment]
https://github.com/monal-im/Monal/issues/1269 ?

**Comment by tmolitor-stud-tu** [comment]
Currently this feature is intentionally missing, other than that, this issue is a duplicate of #1269
