### ISSUE TITLE
[Bug]: Imposible to login with SCRAM-SHA-1-PLUS and ejabberd 24.10 with enabled XEP-0480

### ISSUE THREAD

**Issue by beherit** [monal-im/Monal#1286]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

15.8.3

### Monal version

6.4.5

### Used XMPP server (domain)

jix.im

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.10

### How many accounts are you using in Monal?

1

### What happened?

I tried to check how XEP-0480 works on my server, and I found only this IM that support that XEP. On my server I have enabled `auth_scram_hash: sha` and new module mod_scram_upgrade:

```
modules:
  mod_scram_upgrade:
    offered_upgrades:
      - sha256
      - sha512
```
After refreshing configuration I not able to login with Monal. I get error "XMPP stream error: bad-format". I don't know it is ejabberd issue or problem with Monal. I sent you the log files.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by licaon-kter** [comment]
are you sure that's the way to do it?

I opened https://github.com/processone/ejabberd/issues/4301 because I don't think that's how it works

**Comment by beherit** [comment]
Oh it was You :D No, I not 100% sure, maybe it's actually a problem with ejabberd.

**Comment by tmolitor-stud-tu** [comment]
@beherit Can you tell me the datetime of that mail containing your logfile?

**Comment by beherit** [comment]
@tmolitor-stud-tu 6 Nov 2024 16:51:27 UTC

**Comment by tmolitor-stud-tu** [comment]
@beherit No incoming mail over here

**Comment by Neustradamus** [comment]
@beherit: Thanks for your ticket, we can track the problem! :)

**Comment by tmolitor-stud-tu** [comment]
xep-0480 is not completely implemented in ejabberd. you should disable it.

**Comment by Neustradamus** [comment]
@beherit: Have you seen this important @tmolitor-stud-tu XEP-0480 fix?
- https://github.com/xsf/xeps/pull/1403

It has been updated in ejabberd/xmpp.

Linked to:
- https://github.com/processone/xmpp/issues/80#issuecomment-2509482891
- https://github.com/processone/xmpp/commit/f5551549e4ba7c27ba84ac4ba7ee7386644b816a

**Comment by Neustradamus** [comment]
@tmolitor-stud-tu, @beherit: The XEP-0384 fix has been merged!

XEP-0384 0.2.0 is now official:
- https://xmpp.org/extensions/xep-0480.html

ejabberd has been updated in master, good reactivity from ejabberd devs.

**Comment by Neustradamus** [comment]
@tmolitor-stud-tu, @beherit: The XEP-0480 fix has been merged!

XEP-0480 0.2.0 is now official:
- https://xmpp.org/extensions/xep-0480.html

ejabberd has been updated in master, good reactivity from ejabberd devs.
