### ISSUE TITLE
[Feature]: Synchronize subscription requests across devices

### ISSUE THREAD

**Issue by sstrigler** [monal-im/Monal#1301]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Currently if I have multiple instances of Monal (eg desktop and phone), if I get an incoming subscription request that I want to block, I have to handle them on both devices. Instead, if I react on one instance I want the other to reflect that change.

Eg, if I decline a subscription request, a client receives a stanza like the following and it should handle it by removing the corresponding entry from the list of incoming requests (and send an `iq-result` accordingly).
```xml
<iq xmlns='jabber:client' to='icke@example.org/eli' from='icke@example.org' type='set' id='push6302782379657504161'>
	<query xmlns='jabber:iq:roster' ver='173685c48e2d68315a1e34d4d6d997f25f53a223'>
		<item subscription='remove' jid='spammer@otherserver.com'/>
	</query>
</iq>

<iq type='result' id='push6302782379657504161'/>
```

PS: This seems to work if I accept the request.

**Comment by sstrigler** [comment]
So, yeah, maybe this should have been filed as a bug. Let me know if I should re-post.

**Comment by tmolitor-stud-tu** [comment]
Already implemented. Some servers can hold off sending subscription changes until important data (such as incoming messages, etc.) needs to be delivered. I believe that's what you are experiencing.

Try sending a message to some of your contacts (or to "notes to self") to trigger a sync. Feel free to reopen this issue, if that doesn't work.

**Comment by sstrigler** [comment]
Can‘t confirm unfortunately. Tried as suggested by sending a message to myself. Message was received on second device but subscription request remained. Even more so, I can add another observation which might hint at a bug: On the second device I was shown a notification „User \<foo\> wants to add you to their contact list“. So it seems like it received the iq-stanza but interpreted it wrongly.
