### ISSUE TITLE
[Feature]: Copy message text

### ISSUE THREAD

**Issue by cweiske** [monal-im/Monal#1302]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

I am using Monal 6.4.6 on a Mac Mini, and I am not able to copy text from received messages into the clipboard.
I can neither select text, nor right-click to open a context menu and select "copy".

**Comment by licaon-kter** [comment]
There's a swipe action with mouse or trackpad?

**Comment by cweiske** [comment]
The Mac Mini does not have a trackpad.
Swiping the message bubble with the mouse to the left or right is not possible.

**Comment by tmolitor-stud-tu** [comment]
You'll need a magic mouse or trackpad or touch to be able to swipe things. That's apparently an apple limitation.

**Comment by lissine0** [comment]
It seems that you can use https://github.com/intitni/AbnormalMouseApp to do gestures with a non-Apple mouse
(I did not test it)

**Comment by cweiske** [comment]
@tmolitor-stud-tu How is this problem solved?

**Comment by lissine0** [comment]
@cweiske This is a limitation on the Apple side.
As mentioned above, you'll need either a magic mouse or a trackpad; or possibly https://github.com/intitni/AbnormalMouseApp with a normal mouse.

**Comment by cweiske** [comment]
@lissine0 So the Monal developers officially tell people to buy an apple mouse if they want to copy text? Wow.

**Comment by lissine0** [comment]
> the Monal developers officially tell people to buy an apple mouse

~~Monal developers~~ Apple officially tells people to buy an apple mouse to do gestures.
That's the reason someone created a mac app that allows you to do gestures with a regular mouse.
But you like ignoring that, so here's another idea:
Monal is free (libre) software, so feel free to open PR improving the situation, and I'm sure the Monal developers will be happy to review it.
