### ISSUE TITLE
[Bug]: There seems to be an issue with the app’s sound settings. On the iPhone 15 Pro Max, incoming messages fail to trigger notification sounds!

### ISSUE THREAD

**Issue by HelloSkyHigh** [monal-im/Monal#1321]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

18.11

### Monal version

Stable 6.4.7 (1003)

### Used XMPP server (domain)

xmpp.jp

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

A problem happened! There seems to be an issue with the app’s sound settings. On the iPhone 15 Pro Max, incoming messages fail to trigger notification sounds!

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Works for me, did you turn on the small mute switch on the side of your phone? Try to restart your whole phone, in case some apple service crashed.

**Comment by HelloSkyHigh** [comment]
> Works for me, did you turn on the small mute switch on the side of your phone? Try to restart your whole phone, in case some apple service crashed.

All the apps on my phone have normal notification sounds except Monal. I’ve checked a million times, and it’s definitely not my settings.

**Comment by tmolitor-stud-tu** [comment]
reboot your phone and reopen this issue, if your problem persists.
