### ISSUE TITLE
Cannot add/invite users to MUC

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [monal-im/Monal#158]
In my iOS application, I can able to create the groups (in Groups Tab). But I didn't find option to add/invite an user to that particular group

<img src="https://user-images.githubusercontent.com/46367348/50682138-e69df980-1033-11e9-816f-6058dd300330.PNG" width="300">

**Comment by Echolon** [comment]
Yep, I think this is a very important function. I would also add something like:

once you created a group, the software directely askes you to invite people. Or as there is no one in the group, a button shows up in the chat windows which suggest to invite people

**Comment by Echolon** [comment]
@NagarajuMetavoxx 

Is that still not possible in MUCs in the latest release?

**Comment by Echolon** [comment]
ref. **XEP-0048: Bookmarks** #19

**Comment by tmolitor-stud-tu** [comment]
duplicate of #41
