### ISSUE TITLE
Setting own status in Preferences is cumbersome

### ISSUE THREAD

**Issue by CodingMarkus** [monal-im/Monal#165]
It's pretty cumbersome to always open the preferences just to set the status "Away" and later on setting it back. Why not offering this via a toolbar button that can be toggled? Also useful would be to allow entering multiple status messages and allowing to quick switch between those using a second toolbar button.

**Comment by Echolon** [comment]
@tmolitor-stud-tu does this still has relevance?

**Comment by tmolitor-stud-tu** [comment]
closed, ui changed a lot
