### ISSUE TITLE
XEP-0048: Bookmarks

### ISSUE THREAD

**Issue by andersruneson** [monal-im/Monal#19]
Monal should use [XEP-0048 Bookmark Storage](http://xmpp.org/extensions/xep-0048.html) to join those MUCs in the users bookmarks. Also when joining a new MUC with Monal, that MUC should be added to the bookmark list.

This gives the following possibilities:
- Only join those those marked with auto join
- Use nickname from bookmark
- Use name from bookmark to display in conversations list

(e.g. clients like Gajim and Conversations uses bookmarks and honours all those settings)

**Comment by tmolitor-stud-tu** [comment]
Currently MUCs are displayed as their jid. But many MUCs create by Conversations (for example) use a random string here and the MUC topic is displayed as MUC name.
Monal should do the same as random MUC names are not very user friendly.

**Comment by Echolon** [comment]
related. XEP: 
XEP-0411: Bookmarks Conversion https://xmpp.org/extensions/xep-0411.html

**Comment by tmolitor-stud-tu** [comment]
For reference (and timeline) I (and maybe Friedrich) will start working on this as soon as notifications without dummy message are implemented.

But we have quite a lot on our internal ToDo list: https://github.com/tmolitor-stud-tu/Monal/issues/12

**Comment by Echolon** [comment]
just wow! 🚀
