### ISSUE TITLE
Share button: allow other file types

### ISSUE THREAD

**Issue by ge0rg** [monal-im/Monal#215]
The :paperclip: button left to the input box only allows sharing of pictures. It would be great to also have sharing of videos (maybe with recompression), and also maybe of other file types like documents etc.

**Comment by tmolitor-stud-tu** [comment]
I second this.
It would be really(!!) nice if audio messages could be sent, too.

**Comment by tmolitor-stud-tu** [comment]
Even Chatsecure allows for this...

**Comment by anurodhp** [comment]
Audio and video are in dev

**Comment by Echolon** [comment]
Other filetypes like PDF are not possible yet

**Comment by tmolitor-stud-tu** [comment]
Fixed in latest alpha, will be in monal 5.0

**Comment by tmolitor-stud-tu** [comment]
already in 5.0 beta, I'll close this
