### ISSUE TITLE
Explain what icons mean in-app (Moon / mute icon)

### ISSUE THREAD

**Issue by trwnh** [monal-im/Monal#220]
I had no idea what the moon meant until I found this page on your blog: https://monal.im/blog/mute/

Nowhere in the app is it ever explained what this button does, or what any of the other buttons do. And a crescent moon usually does not mean "muted", it means something like "night mode". So it was very confusing to see that icon, tap it a few times, and not be able to figure out what it does.

**Comment by anurodhp** [comment]
This is how iOS represents it in its design language. The system do not disturb uses a moon as well as iMessage which uses a moon for mute

**Comment by eun-ice** [comment]
I got confused by the moon in iMessage too, but it is better to stay consistent with the UI design language.

**Comment by anurodhp** [comment]
The assumption is that 100% of users are iOS and Mac users :) so using things people are already familiar with make transition easier. I am also adopting things from what’sapp on the assumption that many users have already used it.

**Comment by trwnh** [comment]
OK, was unaware that this was an iMessage thing. Changed this issue title.

**Comment by pgeorgi** [comment]
Maybe create a bubble notification for the various actions, both to signify that they do anything and also what they do? For the moon something like "user a@b.c (un)muted".

Or is that unusual in the iOS design?

**Comment by Echolon** [comment]
@trwnh 

I will close this thread, I hope that's okay for you as the topic seem to be cleared out

**Comment by trwnh** [comment]
I think it's still an issue and there should be a text label somewhere, but I don't mind the status of this issue

**Comment by tmolitor-stud-tu** [comment]
Fixed in the upcoming 6.0 beta
