### ISSUE TITLE
Groups not syncing 

### ISSUE THREAD

**Issue by anilk9096** [monal-im/Monal#223]
Monal was best xmpp client i ever used . Only problem i was facing was groups which were already created not getting in monal group chat list . any solution ?

**Comment by zippydan** [comment]
is this referring to group chats or to user group organization in the contact list?

a request for Monal to support user groups already exists here:

https://github.com/anurodhp/Monal/issues/121 
> [feature request] support for user groups #121

If you are referring to a problem with group chats, then ignore my message and try to explain your specific issue a little better - preferably with an example scenario.

**Comment by Echolon** [comment]
@anilk9096 

Hi,

have you check if your problem exists with the current release?

**Comment by Echolon** [comment]
ref. **XEP-0048: Bookmarks** #19

**Comment by Echolon** [comment]
Confirmed. No syncing anymore.

iOS - Beta 4.7. (633)

**Comment by tmolitor-stud-tu** [comment]
Fixed in latest 5.0 beta, groupchat support is still in alpha state though...
