### ISSUE TITLE
Security and privacy: Dont inline every image URL

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#224]
You shouldn't show previews for every url pointing to an image. This leaks your IP address every time a message containing only an URL is received and has potentially other security impacts.

Correct behaviour implemented by Conversations, gajim, chatsecure and others:
Only download and inline images which are accompanied by an oob-tag containing the same URL as the message body.
For omemo: inline URLs having the aesgch:// Uri scheme.

**Comment by Echolon** [comment]
Hi,

I agree with your point. However, iPhones user expect a very convient app beaviour. I would do instead:

In the welcome screen, ask the user to toggle a few things like:

Link preview     ON (by default)
Automatic download of files up to 10 MB       ON (By default)
...

Thereby every user can decided on their own.

Cheers

**Comment by tmolitor-stud-tu** [comment]
Inlining arbitrary urls someone pastes into the chat is not convenience but inconvenience.
If I paste a link I want you to receive this link as is, not inlined as some image or whatever.

Additionally it is a privacy leak: for *every* link I sent to you, your device will make a head request to check the mime type and I can get your device type, your ip address and possibly other information without you even noticing. I can even track if your device is online using this technique (even if you are in invisible/private mode and/or turned of XEP-0184 message delivery receipts).

Every other client only inlines images intended to be send as such (indicated by the oob tag or aesgcm:// uri scheme). Implementing the same behaviour in monal would actually meet expectations of the users.

Your suggestion allowing to turn on and of the inlining is not solving the issue that I want *some* images to be inlined (those send as media by my chat partners) and *some other* images to not being inlined (plain uris pasted by my chat partners).

Whether a knob to turn off inlining completely or not would be helpful for overly privacy concerned people is another question though.
Maybe even a knob turning on inlining for all links (default off) would be some option for overly *not* privacy concerned people.

**Comment by Echolon** [comment]
How do you want to prevent the other side to open the link? from what ever side?
if you only want to send a link, then use a quoting formation or so?

**Comment by eun-ice** [comment]
Apart from the privacy issue, sending links simple does not work. If someone sends me a link to a private site, I often just see a large grey area with ‚something.com‘, and I’m not even able to open the link. (macOS Version)

I also agree with the privacy issue though, but if the head request fails, please just show the link as Text. That would be a step forward we can all agree on.

**Comment by Echolon** [comment]
@FriedrichAltheide isn't that an opt-out in the pop-up settings screen?

**Comment by FriedrichAltheide** [comment]
@Echolon we should keep this open till the new file transfer UI is implemented / tested

**Comment by tmolitor-stud-tu** [comment]
fixed now :)

**Comment by Echolon** [comment]
What is the fix? :smiley:
