### ISSUE TITLE
Enable OMEMO by default

### ISSUE THREAD

**Issue by Midar** [monal-im/Monal#234]
Would it be possible to add an option to enable OMEMO by default? It keeps happening to me that I don’t use OMEMO when both parties support it because Monal requires manually enabling it per contact.

**Comment by Echolon** [comment]
As long there is no stable MUC OMEMO and good guidance for the user I would be careful about such a step now

**Comment by Midar** [comment]
I think MUC and regular chat are a different story. I think it makes sense to enable it by default for regular chats, but not MUC. And maybe also adding a warning when not using OMEMO.

**Comment by Echolon** [comment]
No warning which cannot be clicked away (one-time decision!) please. And still there should be an easy opt-out option

**Comment by Midar** [comment]
A notification would not need to be permanent - I think it would be enough to show it when starting a new unencrypted chat or when switching from OMEMO to no OMEMO.

**Comment by ThatOneCalculator** [comment]
As there is now OMEMO in private MUCs, I think this should be relooked at

**Comment by FriedrichAltheide** [comment]
OMEMO is enabled by default in monal 5.3.0
