### ISSUE TITLE
Send and play voice / audio messages inline

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#238]
Hi,

appart from this issue 

**Support VoIP for voice calling with other apps** #205 

voice messages are essential for lots of people. Therefore, inline sending of voice messages as well as playing would be a great feature.

Kind regards

**Comment by Echolon** [comment]
Hello,

I would like to also remind on this experience from ChatSecure, if that applies to Monal one day:

**[UX] Voice-Messages don't get saved nor continue recording on events** #1054

**Comment by Echolon** [comment]
I additionally recommend to implement the function that missed or stopped voice recordings can be continued. It's really annoying if you loose one or two minutes talking.

**Comment by tmolitor-stud-tu** [comment]
implemented
