### ISSUE TITLE
Quote on message swipe

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#239]
Hi,

I just saw how friends frequently use quoting of textmessages in their chat window by swiping the text bubble to the right.

https://youtu.be/DgsYAJtz74U?t=127

Another possibility is tapping or double tapping a message

Cheers

**Comment by anurodhp** [comment]
This is more than a ui change. Xmpp does not have a way to reply to a specific message like this so the receiver will not see the message quoted

**Comment by Echolon** [comment]
Ok, but what is Conversations doing differently?

**Comment by anurodhp** [comment]
I’ll ask Daniel. I am not aware of contextual replies like this but maybe it’s been added

**Comment by Echolon** [comment]
I just know the app can do quoting, but via context menu. Thought a swipe gesture could be possible

**Comment by jubalh** [comment]
I think its this: XEP-0393: Message Styling. See here for [quote](https://xmpp.org/extensions/xep-0393.html#quote).

@anurodhp do you think you can implement this feature in the near future?
Like holding down on a message and then one can reply to it via XEP 0393.

**Comment by Shura0** [comment]
Suppose it should work well with #143

**Comment by FriedrichAltheide** [comment]
ref. #604 #605

**Comment by FriedrichAltheide** [comment]
Working in alpha
