### ISSUE TITLE
Allow downloading aesgcm (non image) URLs

### ISSUE THREAD

**Issue by pgeorgi** [monal-im/Monal#256]
When sharing non-image files from Conversations, the recipient gets an aesgcm URL that they can't open. Ideally the file would be downloaded by Monal, decrypted and passed to whatever mechanism iOS has for opening arbitrary files.

**Comment by Echolon** [comment]
Hi @pgeorgi,

have you checked the current beta?

**Comment by pgeorgi** [comment]
Sorry, I don't have iOS devices around and was just passing along a report by a friend who uses Monal (and who I wouldn't want to enroll in beta builds). I could send a file from Conversations to an XMPP address of your choice though.

**Comment by Echolon** [comment]
Ok thx - will try myself

**Comment by Echolon** [comment]
@foss- can you also try to reproduce this from a non apple device?

**Comment by foss-** [comment]
Sorry no device at hand.

**Comment by Echolon** [comment]
**Share button: allow other file types tada Feature**
#215

**Comment by tmolitor-stud-tu** [comment]
Fixed in latest alpha, will be in monal 5.0

**Comment by tmolitor-stud-tu** [comment]
This is now in 5.0 beta, I will close
