### ISSUE TITLE
[macOS] Unencrypted messages in MUC with OMEMO enabled

### ISSUE THREAD

**Issue by ritzmann** [monal-im/Monal#257]
I have been trying this every once in a while since Monal supports OMEMO but it has always failed for me:
1. Join a private MUC, enable OMEMO encryption
2. Send a message to MUC

Result:
Monal pretends to have sent an encrypted message but in fact it sent the message unencrypted.

FWIW, receiving and decrypting OMEMO messages in the MUC works fine, just the sending part is wrong.

**Comment by Echolon** [comment]
@ritzmann Same here, still existent?

**Comment by ritzmann** [comment]
Yep, just tried out the latest. Doesn't seem like the author ever tested that.

**Comment by anurodhp** [comment]
I’ve hidden the lock in muc since muc omemo isn’t supported yet and the ui was confusing

**Comment by Echolon** [comment]
ref. #564
