### ISSUE TITLE
Groupchats are constantly offline

### ISSUE THREAD

**Issue by sirdrakeistda** [monal-im/Monal#260]
In Monal the groupchats seem to be constantly offline. No messages arrive in Monal and Messages in Monal groupchats are not send. The Groupchat works with Conversations and Gajim.
Monal: 3.8
Server: trashserver.net
Groupchatserver: draugr.de

I'm not sure if it's a problem only for Version 3.8. But with Version 3.7 it was possible to send messages in the groupchats, which don't work anymore. 1:1 messages work without problem and normal contacts are correctly shown as offline/online. I can't provide logs. I hope somebody else can.

**Comment by anurodhp** [comment]
this may be resolved in the latest beta

**Comment by sirdrakeistda** [comment]
It's not realy solved. In version 4.2 I got the same issue. The problem showed up, when I re-added the groupchat, because after invitation the groupchat didn't showed up in the groupchat list. I tried a few times to re-add the groupchat, but the groupchat is always offline. A similar groupchat (also privat, no password) made no problems and works.

**Comment by sirdrakeistda** [comment]
I have the same issue with Monal 4.4 for private groupchats (Monal was invited to the groupchat via xmpp uri) on the server blabber.im . Re-adding didn't helped.

**Comment by Echolon** [comment]
ref. **XEP-0048: Bookmarks** #19

**Comment by Echolon** [comment]
Confirmed. No syncing/reaction anymore.

iOS - Beta 4.7. (633)

**Comment by tmolitor-stud-tu** [comment]
fixed in current alpha and next beta

**Comment by Echolon** [comment]
It begins :)

Great heavy heavy deployment guys!
