### ISSUE TITLE
Retrieve iOS Group Chat History does not work

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [monal-im/Monal#296]
when participants are online this time  we can able to get the messages .  But  when participant went offline  not able to  get messages ...

**Comment by Echolon** [comment]
Can you please be a bit more clear about the issue?

You mean you are not able to retrieve an existing history in a single chat if a person is offline? Or is this about MUC/Group chat?

**Comment by NagarajuMetavoxx** [comment]
MUC/Group chat history not able to getting

**Comment by NagarajuMetavoxx** [comment]
@Echolon , its MUC/Group chat history not able to getting

**Comment by Echolon** [comment]
ref. **XEP-0048: Bookmarks** #19

**Comment by Echolon** [comment]
Confirmed for MUC.

iOS - Beta 4.7. (633)

**Comment by tmolitor-stud-tu** [comment]
fixed in alpha and next beta
