### ISSUE TITLE
Catalyst: Group Chat list might be confusing

### ISSUE THREAD

**Issue by ingoj** [monal-im/Monal#307]
When you have multiple JIDs all starting with the same identity, it gets confusing/impossible to determine which account has joined which MUC: 
<img width="351" alt="Bildschirmfoto 2019-12-21 um 15 43 36" src="https://user-images.githubusercontent.com/18173881/71309506-abddce80-2408-11ea-9bb0-2cc702326be8.png">

As you can see, I have multiple accounts all starting with ij@... and Monal only lists "ij on monal@chat.jax.im" or so. That might be better when #306 would be fixed, but I think the best would be if you can spot which account is in which MUC at first glance without the need to click on the (i)

**Comment by Echolon** [comment]
@foss- is that still the case on Mac?

**Comment by foss-** [comment]
yes, muc still needs some love which is planned for v5

**Comment by tmolitor-stud-tu** [comment]
thislist does not exist anymore, fixed
