### ISSUE TITLE
Overview: Tasks and Issues

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#322]
Dear participants,

hereby an overview for the current focus of work is provided. 
Please, consider this as an **orientation** and not fixed structure. It also help you to see if your issues are already known. As you can see we collected significant issues, where other existing ones are neglected for the moment. The focus will be iOS. The points are listed in a way to give some respect about prioritization. Also consider the search via clicking [labels](https://github.com/monal-im/Monal/labels).

To support Monal please read: https://github.com/monal-im/Monal/issues/363

Project board:
https://github.com/monal-im/Monal/projects/2

News & background information:
https://monal-im.org/

Translations:
[Weblate](https://hosted.weblate.org/engage/monal/)

Public muc: 
monal@chat.yax.im

Info: Currently Monal supports
- iOS from version 14
- Mac from version 11

Project Milestones:
https://github.com/monal-im/Monal/milestones

List of supported XEPs:
https://github.com/monal-im/Monal
______________________________________________________________________

**Priority**
- Issues with a [priority label](https://github.com/monal-im/Monal/issues?q=is%3Aopen+sort%3Areactions-heart-desc+label%3A%22%3Afire%3A++Priority%22)

**Stability & Bug fixes**

- [ ] #41
- [x] #6
- [x] #192
- [x] #384
- [ ] #235

### :heavy_check_mark: :tada:  Finished work

_MUC & Chat_

- [x] #234 
- [X]  #19 
- [X] #99
- [X] #150 
- [X] #158 
- [X] #181 
- [X] #203 
- [X] #204 
- [X] #260
- [X] #153 
- [X] #216 
- [X] #221 
- [X] #243 
- [X] #237 
- [X] #317 
- [X] #318
- [X] #223 
- [X] #226 
- [X] #241 
- [X] #268 
- [X] #271 
- [X] #296
- [X] #103 
- [X] #10
- [X] #231 
- [X] #256 
- [X] #282
- [X] #251 
- [X] #313
- [X] #319 
- [X] #339
- [x] #180

_Security_

- [X] #10
- [X] #209
- [X] #240 
- [X] #285 
- [X] #242

**Features**

- [x] #19 (XEP-0048, Community :heart: winner)
- [x] #148 
- [x] #43 
- [X] #45
- [X] #331
- [X] #130
- [X] #217
- [X] #205
- [X] #238
- [X] #345
- [X] #362
- [X] #269
- [X] #316 
- [X] #21 
- [X] #206 

**Other**

- [X] #144 [Weblate](https://hosted.weblate.org/engage/monal/)
- [X] #236

**Catalyst topics**

- [X] #333
- [X] #173 
- [X] #199 
- [X] #297 
- [X] #325 
- [X] #365

Feel free to comment and make suggestions.

**Comment by licaon-kter** [comment]
@Echolon So which issue is about "MUC OMEMO" ? Or is that fixed ( https://github.com/anurodhp/Monal/issues/225#issuecomment-570939220 ) ?

**Comment by Echolon** [comment]
I was just able to checkmark another Milestone. This is 50% of the list by now! 🎉

Great work @tmolitor-stud-tu @FriedrichAltheide @poormusic2001 !

**Comment by ThomasLewisNHTB** [comment]
The project board link returns 404.

**Comment by tmolitor-stud-tu** [comment]
Since more or less all of the listed issues are closed now, I'm closing this one, too.
