### ISSUE TITLE
Add share sheet support for photos / images

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#331]
Currently share sheet support exists for links. Sharing images is probably the next or maybe even the most common use case for the share sheet. Would be nice if Monal supported that.

**Comment by Echolon** [comment]
Yep, Monal should definitively register to this iOS service

**Comment by Echolon** [comment]
@tmolitor-stud-tu does this also close with the recent closings?

**Comment by foss-** [comment]
Closing - share sheet working as expected for images in test with desktop 5.0a 2021-03-08:
<img width="401" alt="share sheet" src="https://user-images.githubusercontent.com/5708172/110311344-ee86c900-8003-11eb-9e45-06a237f482aa.png">

**Comment by Echolon** [comment]
Thats another milestone
