### ISSUE TITLE
[iOS] MUC unusable `Error: modify - not-acceptable`

### ISSUE THREAD

**Issue by FRNK-BK** [monal-im/Monal#349]
<img src="https://user-images.githubusercontent.com/463868/73120588-92342780-3f70-11ea-8907-a86d77a7b8a0.jpg" width=270>

I am using Android/Conversations client in that group and on that serves flawlessly. One participant uses iPhone/Monal and nothing works. Sorry.

**Comment by FRNK-BK** [comment]
Worst is, the MUC messages of the Monal user don't go through to the others. If they reach the server, I didn't check. But MUC is broken in Monal for me.

**Comment by Echolon** [comment]
Hi,

what servers are in use?

**Comment by FRNK-BK** [comment]
https://compliance.conversations.im/server/f.reun.de

**Comment by Tyler-2** [comment]
Have same for my first IOS user - On an ejabberd server. They previously used Conversations.

**Comment by Tyler-2** [comment]
I see in my ejabberd logs with debugging on:
`<<"It is not allowed to send private messages to the conference">>}],`

**Comment by Echolon** [comment]
@Tyler-2 thank you for your feedback! If you see any other issues, logs are always helpful, so feel free to add more! Maybe also on other issues, e.g. Messeage replication #221

**Comment by Tyler-2** [comment]
@Echolon I unfortunately have only one IOS user at the moment - I'm trying to offer XMPP to other than Android/desktop/web users and this was the first foray. My one IOS user doesn't have much patience for trying these things. I would be perfectly happy to create a user for you and work with you to generate / provide server side logs if that would be helpful?

**Comment by anurodhp** [comment]
If you are interested in testing  monal but done have an iOS of Mac hansy, you can virtualizate a Mac 

https://github.com/myspaghetti/macos-guest-virtualbox

**Comment by FRNK-BK** [comment]
I tried with another iOS user, with another group. Same issue.
Has anyone ever been using MUCs with Monal on ejabberd successfully?

**Comment by Tyler-2** [comment]
Unfortunately I just instructed my user to go to Chat Secure. They seem alright with it.

**Comment by Echolon** [comment]
@tmolitor-stud-tu May you have some ideas about this?

**Comment by Ansheos** [comment]
Checking to move from Android to iOS, I am lacking a replacement to Conversations.
I have this bug too, so I cannot fully test Monal.
Context is: Conversations user, connecting to a Prosody server. ChatSecure can connect and autojoin all the MUCs (but shows other annoyances).

It would seem that Monal cannot see the MUC/conference service.
I wonder if I would be missing some dependencies, is there any module list, or even XEPs, that Monal would require maybe?

If needed I could dump (&clean) some logs.

**Comment by Echolon** [comment]
@Ansheos I think for appropiate usage of MUCs this feature is missing so far: https://github.com/anurodhp/Monal/issues/19

**Comment by Ansheos** [comment]
@Echolon could be. I'll keep an eye on #19  until closure before investigating further away.
Thanks.

**Comment by tmolitor-stud-tu** [comment]
@ansheos see my new comment in #19

**Comment by Echolon** [comment]
Confirmed.

iOS - Beta 4.7. (633)

**Comment by tmolitor-stud-tu** [comment]
fixed in alpha and beta
