### ISSUE TITLE
Support Monal!

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#363]
Dear users,

the development of Monal thrives and improves significantly with your support and your efforts! If you are encouraged to enhance Monal we suggest the following options:

**Ring the bell** :bell:
Have you recognized any bugs or do you have suggestions for improvements? Then please create an [issue](https://github.com/monal-im/Monal/issues/new/choose). _(Please be so kind and [check](https://github.com/monal-im/Monal/issues/322) first if your issue already is known! :pray: )_ Here you can test the [iOS Beta](https://testflight.apple.com/join/lLLlgHpB) and [macOS Beta](https://testflight.apple.com/join/tGH2m5vf)!
If there are bugs which are not reproducible or you intent to help with extended testing and reviews please feel free to contact us via mail at info@monal-im.org, too.

**Translations** :flags:
You can also help to translate Monal to your preferred language on our [Weblate site](https://hosted.weblate.org/engage/monal/)!

**Star Wars** :star:
To make Monal more prominent and to gain attention, be so kind and star the GitHub repository of Monal.

**Insert coin** :moneybag: 
Please support our community contributors with your donation!
- Donate via [GitHub Sponsors](https://github.com/sponsors/tmolitor-stud-tu)
- Donate via [Libera Pay](https://liberapay.com/tmolitor)
- EU citizens can donate via SEPA, too. Just contact Thilo Molitor via mail to thilo@monal-im.org to get his IBAN.

**I :heart: Monal**
Just leave a review or rating in the App Store!
- [iOS](https://apps.apple.com/app/id1637078500)
- [macOS](https://apps.apple.com/app/id1637078500)

**Hit the keys** :musical_keyboard:
If you have some time, a Macbook or similar and an iPhone a great help would be creating a [Pull Request](https://github.com/monal-im/Monal/pulls) or [review of code](https://github.com/monal-im/Monal)!
Hint: If you are interested in testing Monal but don't have an iOS or Mac hardware, you can virtualize:

- [MacOS Bis Sur](https://github.com/kholia/OSX-KVM)
- [Alternative 1](https://github.com/myspaghetti/macos-guest-virtualbox)
- [Alternative 2](https://www.intoguide.com/install-macos-catalina-on-vmware/)
- [Alternative 3](https://techsviewer.com/how-to-install-macos-10-15-catalina-on-vmware-on-windows-pc/)
- [Mac OS Beta ISO](https://gist.github.com/steinybot/105e6631504f1026662035acb4d592b8) as well as the [free preview image](https://apps.apple.com/us/app/macos-catalina/id1466841314?mt=12)

Direct download links to all [XCode versions](https://stackoverflow.com/questions/10335747/how-to-download-xcode-dmg-or-xip-file)
If you want to connect your physical iPhone to XCode inside your VM, [use this (tested by Monal devs)](https://github.com/sickcodes/Docker-OSX#usbfluxd-iphone-usb---network-style-passthrough-osx-kvm-docker-osx)

Access to the Alpha builds: We would also like you to ask if there are more people interested to test the [Alpha builds](https://github.com/monal-im/Monal/commits). That would help us a lot but also offers you to have the new bleeding-edge features implemented. Just sent your device's UUID to info@monal-im.org. Once your device has been authorized, you can [download and install](www.eightysoft.de/monal) it. For each new commit to the develop branch a new build will go down the pipeline. **Please be reminded that the Alpha obviously might be unstable, slower or come with other severe issues.** So, do not install this to your friends contacts!
Read here how to use logging with the [Monal UDP Logger](https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging)

Follow Monal on [Fosstodon](https://fosstodon.org/@Monal)!
 
Thank you for using and supporting Monal!

**Comment by Echolon** [comment]
@Echolon show this in the wiki, too!

**Comment by tmolitor-stud-tu** [comment]
@Echolon
Maybe migrate this issue into a wiki page?
That would look nicer and smoother :)

**Comment by Echolon** [comment]
@tmolitor-stud-tu Yes, I can COPY it, but I woulf not move it.

Why? Well, it is one of the highest clicked pages in the repository, so that tells it is placed quite right. I highly recommend to keep it here as well.

**Comment by mileskanda** [comment]
Greetings!
Dear developer, my organization decided to use monal as work messenger for Mac OS users, I have MBA, that supports only high sierra 10.3.6. In app store version only for Mac OS 10.15.
Can I find somewhere version for 10.13 OS?

Best wishes,
mileakanda

**Comment by Sardor-art** [comment]
Hello.

How can I log in with my ip address?
ex.server: 127.1.1.1
ex.jid: test@localhost

**Comment by FriedrichAltheide** [comment]
@Sardor-art Please have a look at the wiki https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions
BTW: It is not a good style to ask questions in a random existing and unrelated issue.
