### ISSUE TITLE
Future: Implement (new) OMEMO:1

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#372]
Hi Anu,

just a reference for you about the upcoming XEP for the new OMEMO: https://github.com/xsf/xeps/pull/903

Edit: Release is here by now: https://xmpp.org/extensions/xep-0384.html

Still, I would recommend to focus on the other important things for the next time. We should wait till that XEP has somehow be a approved or there is a Conversations implemenation.

Rel: #10

**Comment by licaon-kter** [comment]
https://xmpp.org/extensions/xep-0384.html

So not really new-OMEMO but more like omemo:1

**Comment by Neustradamus** [comment]
Can you update the XEP-0384: OMEMO Encryption to 0.4.0?

- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

**Comment by tibequadorian** [comment]
Don't know about the state of this issue but the current version is OMEMO 2 since version 0.8.0 of [XEP-0384](https://xmpp.org/extensions/xep-0384.html)

**Comment by tmolitor-stud-tu** [comment]
I think most clients will jump straight to MLS instead of doing OMEMO:1, so I'm closing this issue now

**Comment by tibequadorian** [comment]
👍 is there an XEP for this MLS thing?
