### ISSUE TITLE
XEP-0215: External Service Discovery

### ISSUE THREAD

**Issue by sjthespian** [monal-im/Monal#387]
Is there support for service discovery in Monal? 

For example, I run an XMPP gateway to other services such as IRC. In other XMPP clients (Psi and Pidgin for example), there is an option to get a list of services on the server, authenticate to them, and communicate with them.

**Comment by sjthespian** [comment]
I can make it work for now by firing up Adium or Psi to join the service, then Monal picks it up. If I can get the IRC gateway working I can finally retire Adium.

I finally found the contact list today, so that's progress. :-)

**Comment by Echolon** [comment]
@sjthespian 
> I finally found the contact list today, so that's progress. :-)

What was unclear for you?

I will leave the request open anyway.

**Comment by Echolon** [comment]
https://xmpp.org/extensions/xep-0030.html

**Comment by tmolitor-stud-tu** [comment]
You can just add any jid on this service to your contact list.
I don't know if I ever implement a list of services, though.

**Comment by Echolon** [comment]
Note: This is part of the Compliance Suite 2020 already

**Comment by tmolitor-stud-tu** [comment]
XEP-0215 is implemented for STUN/TURN servers now, closing this
