### ISSUE TITLE
MUC details views

### ISSUE THREAD

**Issue by licaon-kter** [monal-im/Monal#422]
...remove "Encryption keys" entry

Mac beta 4.7 (632)

**Comment by tmolitor-stud-tu** [comment]
well, I'll do all muc fixes once the notifications are fixed

**Comment by tmolitor-stud-tu** [comment]
we'll do acomplete redesign of the muc contact details.
this old menu is gone, fixed for now

**Comment by Echolon** [comment]
I take this off the milestones
