### ISSUE TITLE
Can not leave MUC

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#431]
Probably known, didn't find an open issue, so filing.

**Reproduce**

1. select MUC from "Chats" and click "i"
1. select "Leave Conversation" and confirm with "Yes"

**Currently**

Nothing. Both MUC and Group Chat info panel stay open.
When manually hiding room and re-opening Monal, the room is back.

**Expected**

Info Panel is closed and MUC is closed. MUC is no longer visited and also removed from favorites and auto join.

**Comment by licaon-kter** [comment]
Leave means remove from bookmarks?

Isn't there a Menu option to delete that closes it?

**Comment by foss-** [comment]
Leave is an option in the "i" info menu as described above
![leave](https://user-images.githubusercontent.com/5708172/88179052-985b4600-cc2b-11ea-9f9b-db2a4e10f0ab.png)

**Comment by Echolon** [comment]
Confirmed for iOS

4.7 (633)

**Comment by Echolon** [comment]
Partly confirmed for iOS - alpha 4.7 (30.07 18:39)

It does only delete the chat history (MAM) and removes me off the MUC. But I can still see the much, it should also remove the MUC from the contact list and bring me to this view actually.

**Comment by tmolitor-stud-tu** [comment]
fixed now in alpha/beta

**Comment by foss-** [comment]
This is now done via contact list.
