### ISSUE TITLE
User experience: Re-align account settings entries

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#440]
In this menu, please refactor the options as following:

_Show:_

- Message History (MAM) (write full words)
- Encryptions Keys (put Validate certificate in here)
- Change password

_Create a new menu:_

Advanced settings >
- Server, Port, Direct TLS, Resource, Label

<img src="https://user-images.githubusercontent.com/29168011/89585770-c309e900-d83e-11ea-8711-a5ce62f71add.PNG" width="250">

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
First of all: why?

Second: certifiate validation has nothing to do with "My Keys" which are OMEMO ones.

Third: having a header saying "Advanced settings" is imho enough.
We could move the change password, mam and omemo key settings to the general account settings above the advanced settings, though.

**Comment by Echolon** [comment]
- I think the users (and I think iPhone users are 95% a special case) should only see what they likely can handle. Advance users will find their way. In my view those five points are advanced and not really necessary to show and disturb their focus on what they likely look for

- On cert: yes, didnt knew

- Hmm, I would hide it, its not helping to confuse them with some stuff

@FriedrichAltheide

**Comment by Echolon** [comment]
@FriedrichAltheide thanks for overworking this. I still have two suggestions left:

- Write full expressions: Message Archive Preferences
- Write different wording: Encryption Keys (OMEMO)
- Align 'Change password' to the General section

**Comment by licaon-kter** [comment]
Change password should ask for current password, check if correct and then change it.

**Comment by Echolon** [comment]
@licaon-kter I think that is worth its own issue!

**Comment by Echolon** [comment]
rel. #513

**Comment by tmolitor-stud-tu** [comment]
change password is implemented now, reordering of the settings is done, too...I'll close this now
