### ISSUE TITLE
UI: Aggregate chat history date information

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#454]
Hello,

my suggestion is to aggregate the dates by having a **date line** which separate the chat history per date and only show the date once. Conversations uses a similar solution.

The current solution makes the inline chat quite crowded with information.

<kbd>
<img src="https://user-images.githubusercontent.com/29168011/90544134-fde91680-e186-11ea-84ac-d8edc79e481d.PNG" width="320">
</kbd>

**Comment by Echolon** [comment]
ref. #214

**Comment by FriedrichAltheide** [comment]
@Echolon still a problem?

**Comment by Echolon** [comment]
No it isn't anymore - thanks!

(The dates could have a bigger font size or stand out a bit more to indicate the change of the day. But lets review the chat UI in general another time, see #214)
