### ISSUE TITLE
UI: Improve adding of contacts or group chats with new buttons

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#469]
Hello everyone,

I would like to suggest a new design for adding contacts or group chats.
The idea is to improve **visual appearance** as well as make things more **recognizable** and therefore also **easier to use**.

First see this mock-up:
<kbd>
<img src="https://user-images.githubusercontent.com/29168011/90812285-25c2b080-e326-11ea-9dca-e5bd6ce46c45.png" width="320">
</kbd>

I suggest the following changes. **Please let us thrive the idea first**, ignore the detailed colors and material design for the moment.

- Place the **`add (+) button` to the bottom end** from the top edge _(I know this is similar to Android and might interfere with the fancy apple design suggestions, but okay - just a suggestion)_
- Once the `add (+) button` is clicked, the **background will get transparent** or blurred (preferred the first)
- **Two new buttons appear** as shown. I think it is fine like this, if we have to specify between joining or creating a group chat that can be done in another follow-up screen. We should **just ask for the basic intention** here.
- The **`Pending contacts` thing have to be more visible to the user**. Red color is not necessary, but there should be an **indicator** with a number there there is an action for the user.
- Replace the **person-symbol** in the top left with something like a **gearwheel**.

Asking for feedback @anurodhp

**Comment by Echolon** [comment]
rel.

#116 "Approve Contact" dialog on start doesn't even work (iOS, build 269)
#130 "Add Contact" UI not clear (3.1; build 285)
#214 [UI] Improve text bubble allocation and time stamp art UI
#440 User experience: Refactor account seetings art

**Comment by sirdrakeistda** [comment]
One additional thought:
Subscribing a contact should be reworked too. It should be found in the contact details. At the moment it's also on the same place where you add a contact iirc.

**Comment by Echolon** [comment]
rel. #513

**Comment by tmolitor-stud-tu** [comment]
I think I can close this, everything was reworked now :)

**Comment by Echolon** [comment]
Are you really satisfied with the current adding of contacts?
I wouldnt say so that this is finished yet

**Comment by tmolitor-stud-tu** [comment]
Yes I am
