### ISSUE TITLE
Settings - Change password - Have the user prove that they know the current password

### ISSUE THREAD

**Issue by licaon-kter** [monal-im/Monal#472]
...before actually changing it.

Eg. so your buddy can't change it when you give them your device to look at a meme

**Comment by anurodhp** [comment]
actually it is kind of funny that this isnt in the XMPP standard.

**Comment by tmolitor-stud-tu** [comment]
Actually the wire protocol does not matter at all in this case.

Monal should still check the user's knowledge of the old password against its database before accepting a password change request (and submitting it to the xmpp server).

**Comment by anurodhp** [comment]
Yeah. Easy enough to do client side

**Comment by izanp** [comment]
May I also suggest to be able to link another xmpp account as recovery for password?
Similar to how gmail does a recovery to secondary email.
