### ISSUE TITLE
Testflight: Invite testers to MUC and reporting

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#485]
Hello,

I wanted to suggest an in-app dialogue which shall remind Testflight testers to join the MUC and also encourage them to report on Github.

On could like to those summaries as well:

- https://github.com/anurodhp/Monal/issues/322
- https://github.com/anurodhp/Monal/issues/363

Another suggestion could be to **link to the Testflight from the Monal app directly**

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
@anurodhp may you implement this before the next beta?

**Comment by Echolon** [comment]
@poormusic2001 Do you have time to create a one time appearing popup dialogue (maybe also accessible cia Settings) to do this for the beta releases?

**Comment by Echolon** [comment]
This should be followed up once 5.0 is out

**Comment by izanp** [comment]
Im willing to assist. How can I help?
Ive noticed the muc is underdeveloped.
1. I can join a public chat group with no problem.
2. Private chat groups cannot be joined?

**Comment by izanp** [comment]
I have testflight i stalled today, but im not a developer... willing to test and report.

**Comment by Echolon** [comment]
Hi @izanp,

great to hear that you are interested to support. We can definitively make use of that!

If you are testing the testflight this is a great support for us. If you find any issues or new suggestions, please look if similar issues exists and if not yet here, write a bug report.

You can review a important collection if issues here: https://github.com/monal-im/Monal/issues/322
Please notice that MUC is indeed not in a good state - however there are currently many many significant changes made by the Monal developers. Just be bit patient until the final version 5.0 is released. Yes, using testflight provides you a first glimpse of the improved MUC features.

Also read this: https://github.com/monal-im/Monal/issues/363

**Comment by tmolitor-stud-tu** [comment]
feedback and reporting is already implemented by the testflight app: no need to tell users to join the muc (I guess most beta testers will join the muc anways)
