### ISSUE TITLE
Create DOAP file for supported XEPs

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#494]
Referencing to this issue: #259 

https://github.com/pulkomandy/xmpp-doap

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by wurstsalat3000** [comment]
Please note that the scheme currently found 'in the wild' is the one described here: https://github.com/pulkomandy/xmpp-doap/pull/6/files 

See also:

* https://github.com/dino/dino/blob/master/dino.doap
* https://github.com/yaxim-org/yaxim/blob/master/base.rdf.xml
* https://dev.gajim.org/gajim/gajim/-/blob/master/data/gajim.doap

**Comment by Echolon** [comment]
https://gajim.org/support/extensions/

**Comment by Echolon** [comment]
@wurstsalat3000 Gajims license allows me to just copy it? (Of course I will change it with monal details)

**Comment by wurstsalat3000** [comment]
Yes, you can just copy it.

It's nothing Gajim-specific, it's [a standard](https://en.m.wikipedia.org/wiki/DOAP) with XMPP extensions.

Am 15. Oktober 2020 23:14:16 MESZ schrieb Echolon <notifications@github.com>:

**Comment by Echolon** [comment]
Thank you!
