### ISSUE TITLE
Branding: Small visual changes for 5.0

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#513]
### Description of my issue or feature request:

Collection of possible visual changes for a new Monal 5.0 release.
The idea is to make the user aware that there is a more or less reworked client now.

Of course we have limited resources and way more important things. However, I think the developers invested a lot of work which should be recognised. Therefore I would like to collect possible changes which do make a difference, but do not need too much efforts to be implement.

- Start-up screen: Use Mon logo + Monal turquoise font color
- Start-up: Show a dialogue to welcome users to the new version and inform on important new features.

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by anurodhp** [comment]
Start up is easily updated. Some kind of user education/ change notes  on launch has been something I’ve wanted for a while and there are libraries to generate that

**Comment by tmolitor-stud-tu** [comment]
I guess I can close this
