### ISSUE TITLE
QR Code account feature does not work on macOS

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#525]
### Description of my issue or feature request:
The new QR code feature in Settings > Accounts shows an error message on macOS.
It does seem to work in 4.9 beta on iOS (camera is opened).

This should either be fixed or hidden in catalyst build for macOS.

### The Monal version and system version I use:
macOS 10.15.7
Monal 4.9 alpha 2020-12-10

### Additional information like screenshots:
![qr](https://user-images.githubusercontent.com/5708172/101815779-58382980-3b20-11eb-944d-ef243666245f.jpg)

**Comment by Echolon** [comment]
Can you reproduce this and send the logs?

**Comment by foss-** [comment]
This should be 100% reproducible for anybody running the catalyst build. If logs are needed, happy to send them to the dev looking in to this.

**Comment by anurodhp** [comment]
correct, I have removed this from the catalyst builds. Apple did not approve because this error was here. We will see how it can be  added back.
