### ISSUE TITLE
Seeing "New message" notifications on macOS even when no new message was received

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#546]
### Description of my issue or feature request:
Frequently seeing Monal notifications although no new message was received. Would expect to only see Monal notifications when new messages of unmuted rooms / conversations arrive.

### The Monal version and system version I use:
macOS 10.15.7
Monal 5.0 2021-01-23

### Additional information like screenshots:
<img width="385" alt="New Message notification" src="https://user-images.githubusercontent.com/5708172/105607399-afc3e900-5d9e-11eb-8faf-02dd071fd3b5.png">

**Comment by anurodhp** [comment]
Working with Apple to resolve this issue

**Comment by tmolitor-stud-tu** [comment]
Apparently apple has some bugs in their push system:

> Hi Thilo,
> 
> I'm currently working on getting this approved.
> 
> We have not yet given the entitlement to any macOS/Catalyst app, and so I encountered an error while provisioning your app. I'm working to get this resolved, but it could take some time.
> 
> I will stay in touch.

Once apple has resolved this, we will release a new build.

**Comment by Echolon** [comment]
I guess we should leave the issues open until they are closed. Otherwise people start reporting again and again

**Comment by tmolitor-stud-tu** [comment]
They do already 🤷‍♂️

Am 23. Januar 2021 23:25:19 MEZ schrieb Echolon <notifications@github.com>:

**Comment by anurodhp** [comment]
@tmolitor-stud-tu basically we are the first people to ever do this with catalyst.

**Comment by tmolitor-stud-tu** [comment]
Apple answered today :)

> 
> Hi Thilo,
> 
> I have attempted to provision this app for macOS/Catalyst (as well as iOS.) I received a message that the operation was successful.
> 
> Could you give it a try?

We are now in the process of trying this out in the alpha build :)

**Comment by tmolitor-stud-tu** [comment]
Seems to work in the latest alpha build :)

**Comment by foss-** [comment]
Confirming this no longer is happening in recent alpha build.
