### ISSUE TITLE
Read state not updating

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#551]
Frequently seeing the situation where a new message shows as unread in the left chat column. While having that chat open already and reading the message I often struggle to make Monal understand I have read the latest message. It will not update the unread count.

Clicking into the chat or scrolling up and back down to the latest message does not set the unread count to 0.

### The Monal version and system version I use:
macOS 10.15.7
Monal 5.0 2021-01-30

**Comment by Echolon** [comment]
Thanks for reporting! May you provide a simple reproduction?

**Comment by foss-** [comment]
Not really. Staying in one chat with Monal in focus should trigger this on macOS. Not sure if this problem exists on iOS.

**Comment by FriedrichAltheide** [comment]
known bug. Occurs only on BG -> FG change on iOS and catalyst when a msg was received while being in BG.

**Comment by FriedrichAltheide** [comment]
@foss- please check if it is already fixed in the alpha

**Comment by foss-** [comment]
This has certainly improved a lot. Read state overall is in a much better place now. But I still manage to reproduce a situation in a muc where new messages in a selected and viewed room will show as unread despite of scrolling up and down or clicking in the current chat.

Interestingly even selecting another chat is now sufficient to have those messages no longer show as unread.

**Comment by FriedrichAltheide** [comment]
I can't reproduce this bug on my end

**Comment by foss-** [comment]
Seems indeed resolved with latest alpha. Thanks for your work!
