### ISSUE TITLE
Backup function - Import and export of data

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#552]
### Description of my issue or feature request:

Monal should enable to backup data and import as well as export data. This can be of advantage when a user reinstalls the app or switches the device (or loose it). 
I guess Apple has some functions for this already, however we shouldnt rely on this nor force the user to use it.

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Users can always use iCloud backups or Apples device migration feature, no need to reinvent the wheel.

**Comment by licaon-kter** [comment]
And that gives Apple all you chats unencrypted, yes?

**Comment by tmolitor-stud-tu** [comment]
No, you can activate e2e encryption for iCloud backups: https://www.macrumors.com/how-to/enable-advanced-data-protection-icloud/

And using the device migration feature will transfer everything directly between both devices using wifi.
