### ISSUE TITLE
Catalyst: message interactions frequently invoked when scrolling chat

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#553]
### Description of my issue or feature request:
When scrolling chat up and down it frequently happens that message options do show. Currently those are invoked via sideways swipe. Since that seems fairly sensitive it is invoked by accident.
<img width="272" alt="will do" src="https://user-images.githubusercontent.com/5708172/107060811-b3f8f900-67d7-11eb-924c-9bf947fd8fe3.png">

### The Monal version and system version I use:
Monal alpha 2021-02-05
macOS 11.2

### Possible solutions
- decrease sensitivity for sideways scroll to avoid unintended invokation
- long press (how does that translate to macOS?) instead of sideway swipe to invoke actions
- preferred solution: Signal handles this nicely in their desktop app: options to interact with a single message are shown on mouse hover over that specific message. This is what it looks like:
        - also liking how this was implemented (clear icons and color scheme fitting nicely with rest of the UI)
<img width="211" alt="message options" src="https://user-images.githubusercontent.com/5708172/107060640-814f0080-67d7-11eb-945e-fc60ae9a8f84.png">

**Comment by Echolon** [comment]
@foss- is this still a thing?

**Comment by foss-** [comment]
Think (TM) this has improved. Invoking sideways scrolling now seems less sensitive and is triggered less often unintentionally.
