### ISSUE TITLE
Documentation: Explain translators how to change strings

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#563]
- Or we improve the function on weblate, which I personally think is more suitable for translators. I thought this is working.

**Comment by FriedrichAltheide** [comment]
> [...] improve the function on weblate [...]

What do you want to improve?

**Comment by tmolitor-stud-tu** [comment]
change what strings?

**Comment by Echolon** [comment]
People seem start to edit the wrong localization files (actually the localization files) and the Weblate edit function of the root strings does not work seemingly. Hence, I thought this should be discussed or described.
