### ISSUE TITLE
Signal error on MUC messages

### ISSUE THREAD

**Issue by jpds** [monal-im/Monal#564]
### Description of my issue or feature request:

I started a MUC with two contacts, I and another contact user use Conversations, while the third uses Monal.

The other Conversations user had no issue with OMEMO messages to the group, however, my friend with Monal joined, I sent a message, and they got the error in the screenshot attached.

Note that they're already in the group and has also sent a message to the group (which appears to have errored as well), while still being asked if they'd like to join that very same group. I also had no issue with OMEMO messages with this user on a 1:1 chat (before the group was made).

### The Monal version and system version used:

* Monal 4.9.1
* iOS 14.4

### Additional information like screenshots:

![signal-2021-02-08-125022](https://user-images.githubusercontent.com/29158971/107223042-9b722400-6a0d-11eb-8c26-f149fa562b8d.jpeg)

**Comment by tmolitor-stud-tu** [comment]
That's right, groupchats and omemo in groupchats is still worked on
This will be supported in monal 5.0 (at least the groupchat parts, not sure about the omemo in groupchat part, though)

**Comment by Echolon** [comment]
Hi @jpds,

thank you for your report. Currentlt we are rebuilding and actually correctlt implementing this feature. Please be a bit patient and wait with using groups.

As there are many other open issues, I will close this.
