### ISSUE TITLE
Crash on Mac OS Big Sur (Monal 4.9)

### ISSUE THREAD

**Issue by ddr46** [monal-im/Monal#566]
### Description of my issue or feature request:
When launching Monal on MacOS Big Sur, Monal opens the window and then crashes without any error message other than the window telling me that Monal has crashed and offering either to re-launch, send a message to Apple with the error or ignore.
I tried to de-install Monal and to re-install it, but it's sill doing the same

### The Monal version and system version I use:
Monal version used : same problem for the official version on the App Store and for the last version on the Monal site.
MacOS Big Sur used is the very last official one (11.2)

### Additional information like screenshots:

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by anurodhp** [comment]
When this happens could you send the text in the crash window to bugs@monal.im ? I’ll also check what Apple gives me but this would help a lot 

--
Anurodh Pokharel

**Comment by anurodhp** [comment]
We’ve identified a common crash that’s happening to a lot of people. I’ll give you a link to a build to see if it fixes your problem

**Comment by ddr46** [comment]
Thanks. I’ll wait for the the link, try as soon as i’ll receive it and report back

**Comment by anurodhp** [comment]
could you see if this helps
https://monal.im/Monal-OSX/Monal492.zip

**Comment by ddr46** [comment]
Unfortunately, it’s still the same result after deinstalling the previous version of Monal and using the new one.

Here is the report for Apple
========================================================================================
Process:               Monal [13275]
Path:                  /Applications/Monal.app/Contents/MacOS/Monal
Identifier:            maccatalyst.G7YU7X7KRJ.SworIM
Version:               4.9.2 (699)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Monal [13275]
User ID:               501

Date/Time:             2021-02-14 11:42:45.934 +0100
OS Version:            macOS 11.2.1 (20D74)
Report Version:        12
Anonymous UUID:        739BAD14-A9E8-B37B-85D4-9F7D13625C2E

Sleep/Wake UUID:       37C74414-B495-4FE3-8553-3A916EB0CF3C

Time Awake Since Boot: 10000 seconds
Time Since Wake:       750 seconds

System Integrity Protection: enabled

Crashed Thread:        11  Dispatch queue: receiveQueue[2] (QOS: UTILITY)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff207396af __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff204713c9 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff207eda9a -[__NSCFString characterAtIndex:].cold.1 + 0
3   CoreFoundation                      0x00007fff207f987b -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
4   CoreFoundation                      0x00007fff2064929a -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 235
5   CoreFoundation                      0x00007fff20649195 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
6   monalxmpp                           0x000000010dbfe27d -[xmpp send:withSmacks:] + 604
7   monalxmpp                           0x000000010dbfdfd3 -[xmpp sendIq:withHandler:] + 302
8   monalxmpp                           0x000000010dc01ba7 -[xmpp bindResource:] + 192
9   monalxmpp                           0x000000010dbfd7dc -[xmpp processInput:] + 18137
10  Foundation                          0x00007fff2142d01c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
11  Foundation                          0x00007fff2142cf14 -[NSBlockOperation main] + 98
12  Foundation                          0x00007fff2142cea5 __NSOPERATION_IS_INVOKING_MAIN__ + 17
13  Foundation                          0x00007fff2142c156 -[NSOperation start] + 785
14  Foundation                          0x00007fff2142be3a __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
15  Foundation                          0x00007fff2142bd0d __NSOQSchedule_f + 182
16  libdispatch.dylib                   0x00007fff2041b5dd _dispatch_call_block_and_release + 12
17  libdispatch.dylib                   0x00007fff2041c7c7 _dispatch_client_callout + 8
18  libdispatch.dylib                   0x00007fff2041f195 _dispatch_continuation_pop + 423
19  libdispatch.dylib                   0x00007fff2041e868 _dispatch_async_redirect_invoke + 713
20  libdispatch.dylib                   0x00007fff2042b857 _dispatch_root_queue_drain + 326
21  libdispatch.dylib                   0x00007fff2042bfb8 _dispatch_worker_thread2 + 92
22  libsystem_pthread.dylib             0x00007fff205c4453 _pthread_wqthread + 244
23  libsystem_pthread.dylib             0x00007fff205c3467 start_wqthread + 15

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff20592e7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff205931f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206bfbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206be2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff206bd6ce CFRunLoopRunSpecific + 563
5   com.apple.HIToolbox           	0x00007fff28945630 RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff2894542c ReceiveNextEventCommon + 709
7   com.apple.HIToolbox           	0x00007fff2894514f _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff22edd9b1 _DPSNextEvent + 883
9   com.apple.AppKit              	0x00007fff22edc177 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
10  com.apple.AppKit              	0x00007fff22ece68a -[NSApplication run] + 586
11  com.apple.AppKit              	0x00007fff22ea296f NSApplicationMain + 816
12  com.apple.AppKit              	0x00007fff231993bb _NSApplicationMainWithInfoDictionary + 16
13  com.apple.UIKitMacHelper      	0x00007fff34303faa UINSApplicationMain + 1418
14  com.apple.UIKitCore           	0x00007fff44f93db0 UIApplicationMain + 144
15  maccatalyst.G7YU7X7KRJ.SworIM 	0x000000010d534e99 0x10d52d000 + 32409
16  libdyld.dylib                 	0x00007fff205e2621 start + 1

Thread 1:: Dispatch queue: com.apple.root.background-qos
0   libsystem_kernel.dylib        	0x00007fff205957b6 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff20512c92 nanosleep + 196
2   com.apple.Foundation          	0x00007fff214d7a6c +[NSThread sleepForTimeInterval:] + 170
3   im.Monal.monalxmpp            	0x000000010dc39516 __26+[HelperTools activityLog]_block_invoke + 182
4   libdispatch.dylib             	0x00007fff2041b5dd _dispatch_call_block_and_release + 12
5   libdispatch.dylib             	0x00007fff2041c7c7 _dispatch_client_callout + 8
6   libdispatch.dylib             	0x00007fff2042b9b5 _dispatch_root_queue_drain + 676
7   libdispatch.dylib             	0x00007fff2042bfb8 _dispatch_worker_thread2 + 92
8   libsystem_pthread.dylib       	0x00007fff205c4453 _pthread_wqthread + 244
9   libsystem_pthread.dylib       	0x00007fff205c3467 start_wqthread + 15

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 3:: Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib        	0x00007fff20592e7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff205931f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206bfbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206be2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff206bd6ce CFRunLoopRunSpecific + 563
5   com.apple.CoreFoundation      	0x00007fff2079cb13 boundPairRead + 292
6   com.apple.CoreFoundation      	0x00007fff206f71ad CFReadStreamRead + 251
7   com.apple.Foundation          	0x00007fff214c1419 -[NSXMLParser parseFromStream] + 272
8   im.Monal.monalxmpp            	0x000000010dc0b040 __24-[xmpp startXMPPStream:]_block_invoke.571 + 134
9   libdispatch.dylib             	0x00007fff2041b5dd _dispatch_call_block_and_release + 12
10  libdispatch.dylib             	0x00007fff2041c7c7 _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff2041ee1c _dispatch_queue_override_invoke + 777
12  libdispatch.dylib             	0x00007fff2042b857 _dispatch_root_queue_drain + 326
13  libdispatch.dylib             	0x00007fff2042bfb8 _dispatch_worker_thread2 + 92
14  libsystem_pthread.dylib       	0x00007fff205c4453 _pthread_wqthread + 244
15  libsystem_pthread.dylib       	0x00007fff205c3467 start_wqthread + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 6:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	0x00007fff20592e7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff205931f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206bfbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206be2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff206bd6ce CFRunLoopRunSpecific + 563
5   com.apple.Foundation          	0x00007fff2144afa1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
6   com.apple.Foundation          	0x00007fff214d47c4 -[NSRunLoop(NSRunLoop) runUntilDate:] + 103
7   com.apple.UIKitCore           	0x00007fff44f95041 -[UIEventFetcher threadMain] + 138
8   com.apple.Foundation          	0x00007fff21443e1d __NSThread__start__ + 1042
9   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
10  libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff20592e7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff205931f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206bfbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206be2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff206bd6ce CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff230637c6 _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 8:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff2059b1fe __select + 10
1   com.apple.CoreFoundation      	0x00007fff206e66c3 __CFSocketManager + 644
2   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
3   libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 9:: IPCServerThread
0   libsystem_kernel.dylib        	0x00007fff205958e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205c7e6f _pthread_cond_wait + 1254
2   im.Monal.monalxmpp            	0x000000010dbe9bb2 -[IPC readNextMessage] + 257
3   im.Monal.monalxmpp            	0x000000010dbe94a7 -[IPC serverThreadMain] + 394
4   com.apple.Foundation          	0x00007fff21443e1d __NSThread__start__ + 1042
5   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 11 Crashed:: Dispatch queue: receiveQueue[2] (QOS: UTILITY)
0   libsystem_kernel.dylib        	0x00007fff20599462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff205c7610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff2051a720 abort + 120
3   libc++abi.dylib               	0x00007fff2058c418 abort_message + 231
4   libc++abi.dylib               	0x00007fff2057da7d demangling_terminate_handler() + 266
5   libobjc.A.dylib               	0x00007fff204739b1 _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff2058b847 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff2058b7e9 std::terminate() + 41
8   libdispatch.dylib             	0x00007fff2041c7db _dispatch_client_callout + 28
9   libdispatch.dylib             	0x00007fff2041f195 _dispatch_continuation_pop + 423
10  libdispatch.dylib             	0x00007fff2041e868 _dispatch_async_redirect_invoke + 713
11  libdispatch.dylib             	0x00007fff2042b857 _dispatch_root_queue_drain + 326
12  libdispatch.dylib             	0x00007fff2042bfb8 _dispatch_worker_thread2 + 92
13  libsystem_pthread.dylib       	0x00007fff205c4453 _pthread_wqthread + 244
14  libsystem_pthread.dylib       	0x00007fff205c3467 start_wqthread + 15

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff205958e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205c7e6f _pthread_cond_wait + 1254
2   com.apple.GeForceMTLDriver    	0x00007fff64dff663 0x7fff64c8e000 + 1513059
3   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
4   libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 13:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 14:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff20592e7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff205931f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206bfbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206be2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff206bd6ce CFRunLoopRunSpecific + 563
5   com.apple.CFNetwork           	0x00007fff24b4510e 0x7fff24905000 + 2359566
6   com.apple.Foundation          	0x00007fff21443e1d __NSThread__start__ + 1042
7   libsystem_pthread.dylib       	0x00007fff205c7950 _pthread_start + 224
8   libsystem_pthread.dylib       	0x00007fff205c347b thread_start + 15

Thread 15:
0   libsystem_pthread.dylib       	0x00007fff205c3458 start_wqthread + 0

Thread 16:: Dispatch queue: parseQueue[2] (QOS: UTILITY)
0   libsystem_kernel.dylib        	0x00007fff205958e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205c7e6f _pthread_cond_wait + 1254
2   com.apple.Foundation          	0x00007fff2143c538 -[NSOperation waitUntilFinished] + 697
3   com.apple.Foundation          	0x00007fff215a5407 __NSOPERATIONQUEUE_IS_WAITING_ON_AN_OPERATION__ + 17
4   com.apple.Foundation          	0x00007fff214b3681 -[NSOperationQueue addOperations:waitUntilFinished:] + 170
5   im.Monal.monalxmpp            	0x000000010dc0b1eb __24-[xmpp startXMPPStream:]_block_invoke_2 + 345
6   com.apple.Foundation          	0x00007fff2142d01c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
7   com.apple.Foundation          	0x00007fff2142cf14 -[NSBlockOperation main] + 98
8   com.apple.Foundation          	0x00007fff2142cea5 __NSOPERATION_IS_INVOKING_MAIN__ + 17
9   com.apple.Foundation          	0x00007fff2142c156 -[NSOperation start] + 785
10  com.apple.Foundation          	0x00007fff2142be3a __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
11  com.apple.Foundation          	0x00007fff2142bd0d __NSOQSchedule_f + 182
12  libdispatch.dylib             	0x00007fff2041b5dd _dispatch_call_block_and_release + 12
13  libdispatch.dylib             	0x00007fff2041c7c7 _dispatch_client_callout + 8
14  libdispatch.dylib             	0x00007fff2041f195 _dispatch_continuation_pop + 423
15  libdispatch.dylib             	0x00007fff2041e868 _dispatch_async_redirect_invoke + 713
16  libdispatch.dylib             	0x00007fff2042b857 _dispatch_root_queue_drain + 326
17  libdispatch.dylib             	0x00007fff2042bfb8 _dispatch_worker_thread2 + 92
18  libsystem_pthread.dylib       	0x00007fff205c4453 _pthread_wqthread + 244
19  libsystem_pthread.dylib       	0x00007fff205c3467 start_wqthread + 15

Thread 11 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000700008ea1000  rcx: 0x0000700008ea0808  rdx: 0x0000000000000000
  rdi: 0x0000000000013d03  rsi: 0x0000000000000006  rbp: 0x0000700008ea0830  rsp: 0x0000700008ea0808
   r8: 0x0000700008ea06d0   r9: 0x0000700008ea08a0  r10: 0x0000700008ea1000  r11: 0x0000000000000246
  r12: 0x0000000000013d03  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff20599462  rfl: 0x0000000000000246  cr2: 0x000060000030d000
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Thread 11 instruction stream not available.

Thread 11 last branch register state not available.


Binary Images:
       0x10d52d000 -        0x10d5a0fff +maccatalyst.G7YU7X7KRJ.SworIM (4.9.2 - 699) <B48779EA-CEC7-3E6C-8296-AE75524C2C13> /Applications/Monal.app/Contents/MacOS/Monal
       0x10d5e0000 -        0x10d5f7fff +org.cocoapods.CocoaLumberjack (3.7.0 - 1) <3755B5C3-19C1-3005-B477-70A76BDD9965> /Applications/Monal.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x10d636000 -        0x10d639fff +org.cocoapods.DACircularProgress (2.3.1 - 1) <9DF99F04-081A-3B32-954C-E27F8E7E38F7> /Applications/Monal.app/Contents/Frameworks/DACircularProgress.framework/Versions/A/DACircularProgress
       0x10d655000 -        0x10d65cfff +org.cocoapods.DZNEmptyDataSet (1.8.1 - 1) <56782AFD-9CB2-37E7-9D47-71BB16630D9D> /Applications/Monal.app/Contents/Frameworks/DZNEmptyDataSet.framework/Versions/A/DZNEmptyDataSet
       0x10d677000 -        0x10d686fff +org.cocoapods.EAIntroView (2.13.0 - 1) <DDA071BD-6106-3C9F-A471-7E623D309A5F> /Applications/Monal.app/Contents/Frameworks/EAIntroView.framework/Versions/A/EAIntroView
       0x10d6a3000 -        0x10d6a6fff +org.cocoapods.EARestrictedScrollView (1.1.0 - 1) <90F4FFE2-B10B-37A4-8F1A-EE60BC91C33F> /Applications/Monal.app/Contents/Frameworks/EARestrictedScrollView.framework/Versions/A/EARestrictedScrollView
       0x10d6be000 -        0x10d6cdfff +org.cocoapods.IDMPhotoBrowser (1.10.2 - 1) <393E3382-A503-31C6-A483-287D1B948F00> /Applications/Monal.app/Contents/Frameworks/IDMPhotoBrowser.framework/Versions/A/IDMPhotoBrowser
       0x10d6f4000 -        0x10d6fffff +org.cocoapods.MBProgressHUD (1.2.0 - 1) <3CCCCDF6-9ABD-3CCA-A055-0D08B7F64253> /Applications/Monal.app/Contents/Frameworks/MBProgressHUD.framework/Versions/A/MBProgressHUD
       0x10d71b000 -        0x10d732fff +org.cocoapods.MarqueeLabel (4.0.5 - 1) <4574803F-BF90-39E1-A579-190840B249DD> /Applications/Monal.app/Contents/Frameworks/MarqueeLabel.framework/Versions/A/MarqueeLabel
       0x10d76e000 -        0x10d78dfff +org.cocoapods.NotificationBannerSwift (3.0.6 - 1) <A6F9B851-DF6F-3D45-A095-81687804A43C> /Applications/Monal.app/Contents/Frameworks/NotificationBannerSwift.framework/Versions/A/NotificationBannerSwift
       0x10d7ef000 -        0x10d7f2fff +org.cocoapods.SAMKeychain (1.5.3 - 1) <4517E1D7-253A-3AEA-85DA-98983A6BDC94> /Applications/Monal.app/Contents/Frameworks/SAMKeychain.framework/Versions/A/SAMKeychain
       0x10d809000 -        0x10d850fff +org.cocoapods.SDWebImage (5.10.3 - 1) <F0425635-A684-3CFE-BF3E-20BC5372F676> /Applications/Monal.app/Contents/Frameworks/SDWebImage.framework/Versions/A/SDWebImage
       0x10d8e6000 -        0x10d919fff +org.cocoapods.SignalProtocolC (2.3.2 - 1) <A1FC6537-4FBC-35E4-A7B8-CD129EA09B01> /Applications/Monal.app/Contents/Frameworks/SignalProtocolC.framework/Versions/A/SignalProtocolC
       0x10d973000 -        0x10d97afff +org.cocoapods.SignalProtocolObjC (1.1.0 - 1) <48882CBD-E731-31BC-83D8-32982660C423> /Applications/Monal.app/Contents/Frameworks/SignalProtocolObjC.framework/Versions/A/SignalProtocolObjC
       0x10d99a000 -        0x10d9adfff +org.cocoapods.SnapKit (5.0.1 - 1) <716C10C5-D18A-38FE-82DA-AF4D9FCF7172> /Applications/Monal.app/Contents/Frameworks/SnapKit.framework/Versions/A/SnapKit
       0x10d9ff000 -        0x10da22fff +org.cocoapods.TOCropViewController (2.6.0 - 1) <5716C104-7F80-340E-9499-93C88E1AE057> /Applications/Monal.app/Contents/Frameworks/TOCropViewController.framework/Versions/A/TOCropViewController
       0x10da5b000 -        0x10da5efff +org.cocoapods.TPCircularBuffer (1.6.1 - 1) <B09E6955-BFD5-367C-97F9-6680B926B6AF> /Applications/Monal.app/Contents/Frameworks/TPCircularBuffer.framework/Versions/A/TPCircularBuffer
       0x10da73000 -        0x10da8efff +org.cocoapods.pop (1.0.12 - 1) <632F988D-E213-3F31-A901-177E6097C6C8> /Applications/Monal.app/Contents/Frameworks/pop.framework/Versions/A/pop
       0x10dacc000 -        0x10db5ffff +org.cocoapods.sqlite3 (3.34.1 - 1) <D89C7EA0-FB12-3EA9-A71F-166C640D72D1> /Applications/Monal.app/Contents/Frameworks/sqlite3.framework/Versions/A/sqlite3
       0x10dba2000 -        0x10dba9fff +im.monal.MLCrypto (1.0 - 1) <33273BF9-1EC7-341D-A658-15AB4703B0E0> /Applications/Monal.app/Contents/Frameworks/MLCrypto.framework/Versions/A/MLCrypto
       0x10dbbe000 -        0x10dc75fff +im.Monal.monalxmpp (4.9.1 - 0) <5CFE0176-8640-3D0D-835A-9EBA9CFE3917> /Applications/Monal.app/Contents/Frameworks/monalxmpp.framework/Versions/A/monalxmpp
       0x10dd81000 -        0x10dd90fff  libobjc-trampolines.dylib (818.2) <29187EF9-2BD6-3ABF-8088-DE708721B612> /usr/lib/libobjc-trampolines.dylib
       0x11acc2000 -        0x11ad5dfff  dyld (832.7.3) <0D4EA85F-7E30-338B-9215-314A5A5539B6> /usr/lib/dyld
    0x7fff202fc000 -     0x7fff202fdfff  libsystem_blocks.dylib (78) <E644CAA0-65B7-36E4-8041-520F3301F3DB> /usr/lib/system/libsystem_blocks.dylib
    0x7fff202fe000 -     0x7fff20333fff  libxpc.dylib (2038.80.3) <70F26262-01AA-3CEC-9FAD-2701D24096F0> /usr/lib/system/libxpc.dylib
    0x7fff20334000 -     0x7fff2034bfff  libsystem_trace.dylib (1277.80.2) <87FEF600-48D9-31C9-B8FC-D5249B2AE95D> /usr/lib/system/
================================================================================================================

**Comment by anurodhp** [comment]
I see the error. Will get you another build

**Comment by tmolitor-stud-tu** [comment]
I need the logfile of this crashing run.
You can go to settings --> log and use the share button at the bottom to extract the log after crashing once.
You might need to disable all network access to prevent an additional crash before you've reached this ui item though.

That boils down to:
1. let it crash once
2. disable all network/internet access
3. go to settings --> log and extract the logfile
4. send the log to thilo@eightysoft.de (my private mail) or info@monal.im

**Comment by tmolitor-stud-tu** [comment]
solved by deleting the database file (it seems to be a beta upgrade bug introducing a corrupt app state in the database file)
