### ISSUE TITLE
Crash when clicking + when there are no accounts

### ISSUE THREAD

**Issue by mimi89999** [monal-im/Monal#569]
### Description of my issue or feature request:
Monal crashes when I press + when there was no account added

### The Monal version and system version I use:
Monal: 4.9.1 (686)
iOS: 14.1
Device: iPad 8 gen

### Additional information like screenshots:
Steps:
1. Install Monal
2. Click close on account creation dialog
3. Click on +

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
already fixed in alpha

**Comment by mimi89999** [comment]
Could you push the alpha to TestFlight?

**Comment by FriedrichAltheide** [comment]
We will push a 4.9.2 (most probably without the fix) beta out to TestFlight in a few days. Followed by the first 5.0 beta (with the fix) hopefully a week after that.

**Comment by mimi89999** [comment]
OK. I just wanted to know what happens when + is clicked after the fix. I hope that something else than nothing.

**Comment by FriedrichAltheide** [comment]
A error msg will appear:
Title: "No enabled account found"
Body: "Please add a new account under settings first. If you already added your account you may need to enable it under settings"

**Comment by mimi89999** [comment]
OK. Actually, why are users allowed to access the main app UI without adding any account?

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu and I tested the + button in stable, beta and alpha and it worked in all versions with iOS 14.4

**Comment by FriedrichAltheide** [comment]
ref https://github.com/monal-im/Monal/commit/96d8a4d893404001c3642ed7fba1f296ee9ffe87 - ActiveChatsViewController.m: showLogin again if no account is enabled

**Comment by tmolitor-stud-tu** [comment]
This seems to be fixed in versions 4.9.0, 4.9.1 and 4.9.2 and this fix was verified under iOS 14.4, maybe you should update your iOS version to the latest to rule out an iOS related bug.

I'm closing this unless you proved new evidence this is till the case for iOS 14.4
