### ISSUE TITLE
Encryption Keys via QR-Code option show blank dialog

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#571]
### Description of my issue or feature request:

1. Existing chat > ⌘I / open contact details > Encryption Keys > Click QR-Code Icon

**Currently**
Empty Dialog is opened

**Expected**

Camera should be activated

### The Monal version and system version I use:
macOS 11.2.1
Monal 5.0 2021-02-13

### Screenshots

Encryption Keys Dialog:
<img width="405" alt="encryption keys" src="https://user-images.githubusercontent.com/5708172/107864471-a5a48000-6e5c-11eb-8d37-598f3c6e6840.png">

Clicking QR-Code Icon results in empty dialog:
<img width="409" alt="qr code" src="https://user-images.githubusercontent.com/5708172/107864479-be149a80-6e5c-11eb-9624-c65436fa48f5.png">

**Comment by FriedrichAltheide** [comment]
How many device keys does your account have?

**Comment by foss-** [comment]
@FriedrichAltheide Due to extensive testing: a lot.

**Comment by FriedrichAltheide** [comment]
You should see a warning msg now, if you have to many device keys

**Comment by foss-** [comment]
Can confirm, although no explanation *how* devices would be removed.

Minor: missing dot after `You need to remove some devices`
<img width="317" alt="screenshot" src="https://user-images.githubusercontent.com/5708172/109392000-fff01700-7919-11eb-85b9-d4583a4daeba.png">
