### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by jpds** [monal-im/Monal#573]
### Description of my issue or feature request:

I've been looking into why all the iOS clients on my XMPP server only do TLSv1.2, while all the Android/other ones support TLSv1.3.

It seems to be because Monal uses the old Secure Transport framework:

- https://github.com/monal-im/Monal/blob/b9ebd371b99e9ad75bb873b65f479d19d56fb0fc/Monal/Classes/xmpp.m#L11

Whereas the new Network framework does TLSv1.3 by default:

- https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06g-testing-network-communication

I think Monal should also support TLSv1.3 so this is a enhancement request for the newer framework.

**Comment by tmolitor-stud-tu** [comment]
We know, but apple's new network framework does not support STARTTLS (e.g. turning on TLS on an already established cleartext connection).
You can file a bug report at apple, if you want them to resolve this, but this doesn't seem to be high priority at apple.

**Comment by tmolitor-stud-tu** [comment]
We are considering to implement TLS1.3 via network framework for the non-STARTTLS case, thus I'm reopening this ticket again :)

**Comment by tmolitor-stud-tu** [comment]
Fixed in 75bbff5671803a69c95f5ab31a6ce0815324497e
