### ISSUE TITLE
Community project: Redesign of the Monal logo

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#579]
Hello everyone,

with support from @anurodhp & @tmolitor-stud-tu I am organizing the community project to redesign the Monal logo.
After the suggestion have been made we would like to vote with the community on what should be done. No worries, there will be the option to keep the current one, if a majority votes for this.

There are a few criteria:
- Have a similar coloring scheme
- Try to keep it suitable to the Monal name / "brand" and for the community
- You agree to publish this under the same [license as Monal](https://github.com/monal-im/Monal/blob/develop/LICENSE) is and do not use material that has copyright preventing the use in this project
- Provide it as SVG file (it is not are hard criteria but would be really helpful for us!)
- Please hand in before the **31st of March 2021**

Please publish your suggestion in this chat. If you have multiple suggestions / versions please post each in a separate comment.

We will call for voting outside form GitHub likely, but feel free to us the vote function here :+1: 
Please respect the work of other, if you like it or not.

**Comment by Echolon** [comment]
## The original one Monal logo
![Screenshot_20210224_205124](https://user-images.githubusercontent.com/29168011/109057566-32173400-76e2-11eb-8fea-23dd71a5aad1.png)

**Comment by Echolon** [comment]
## Design by @nautilusx 

![](https://monal.im/wp-content/uploads/2020/12/monal-60@2x.png)

**Comment by nautilusx** [comment]
I asked 7 future iOS users for their opinion. They would like to see a different desgin. Currently they are using ChatSecure.

They want a cleaner design for their messenger app. If we want to make it a real alternative to WA, Signal, Matrix ..., we need to adapt the design for the users.

They need to love it in order to put it on their home screen.

**Comment by p42ity** [comment]
I have an additional suggestion (I am not a logo designer). The colours of the "wings" of the XMPP logo look much like the colours of the himalayan monal. Maybe it would be possible to use this to signalise in the logo that monal is an XMPP messenger.

**Comment by Echolon** [comment]
We have few responses. I suggest we postpone any significant rebranding and redesigns for the moment.
