### ISSUE TITLE
Redesign of empty contact list and empty group chats

### ISSUE THREAD

**Issue by nautilusx** [monal-im/Monal#580]
I asked 7 future iOS users for their opinion. They would like to see a different desgin. Currently they are using ChatSecure.

They want a cleaner design for their messenger app. 

We should also change the pictures for the empty contact list and empty group chats
They like the two current images but they don't fit for a modern messenger.

Here is an example and an idea.

![no contacts](https://user-images.githubusercontent.com/8766955/109118265-653ddf80-7743-11eb-8013-fcf161115dbd.jpg)
![no groups](https://user-images.githubusercontent.com/8766955/109118277-6969fd00-7743-11eb-9ae3-14b88e821fbf.jpg)

We can use it. It is available under a free license.

https://code.briarproject.org/briar/briar/-/blob/master/briar-android/artwork/empty_state_contact_list.svg

https://code.briarproject.org/briar/briar/-/blob/master/briar-android/artwork/empty_state_group_list.svg

credits: Torsten Grote

**Comment by Echolon** [comment]
I would prefer to offer the add contact button directly and also access to the public chat search

**Comment by Echolon** [comment]
I deleted your comment in the other thread. Hope you dont mind.

**Comment by Echolon** [comment]
#442 
#469

**Comment by nautilusx** [comment]
@Echolon I'm fine with any new design and UI progress. So I don't mind.

Can you just add 7 votes for the new app icon because my 7 iOS contacts don't use Github.

**Comment by Echolon** [comment]
I will provide a public vote once we got something. So Github is just a first impression

**Comment by tmolitor-stud-tu** [comment]
groupchats list is now gone...it got refactored into the contact list

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu resolved in alpha?
