### ISSUE TITLE
Feature: Add muting option to MUC / group chats

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#585]
Known issue: It is possible to mute 1:1 or group chats on macOS by clicking on the avatar in the top left of the chat panel and then clicking the moon icon. Once it is filled that chat should be muted.

This works for 1:1 (I think) but it does not currently work for group chats. MUCs are very new and work has just begun so this is expected and a known issue.

### System information:

macOS version: 11.2.2
Used XMPP server (domain): disroot.org
Used XMPP server software & version: Prosody, trunk
How many accounts are registered in your Monal app: 1

**Comment by Echolon** [comment]
Should this be limited to Catalyst?

**Comment by foss-** [comment]
Issue affects Monal on macOS and iOS.

**Comment by FriedrichAltheide** [comment]
@foss- please try the latest alpha

**Comment by foss-** [comment]
Seems to work as expected. Muted channels no longer show notifications with notifications enabled for monal. Unread count for muted channels not shown in icon badge, only in left column chat list as expected.
Thanks a lot for addressing this.
