### ISSUE TITLE
Confirmation dialog shows different JID than deleted

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#592]
Deleting a contact from contact list when using search results in wrong info in confirmation dialog. In my case the wrong JID was shown in the confirmation dialog and was actually deleted after selecting `Yes`. So this results in unexpected dataloss.

macOS: 11.2.2
Monal: 5.0a 2021-03-03

While I was trying to delete a different contact confirmation asks about different JID:
<img width="405" alt="screenshot" src="https://user-images.githubusercontent.com/5708172/110132446-7766f000-7dcb-11eb-9ede-be32e396d57d.png">

**Comment by Echolon** [comment]
Thank you for reporting!

**Comment by foss-** [comment]
Confirming this is fixed in todays alpha. Thanks @FriedrichAltheide.
