### ISSUE TITLE
Send button not showing when using privacy settings

### ISSUE THREAD

**Issue by surentharp** [monal-im/Monal#594]
Hi,

Thank you for providing us great new features. I faced an issue which is described below.

### Description of my issue or feature request:

When you OFF the "Send Typing Notifications" in the "Privacy Settings" of Monal iOS app, the send button is not shown.

Usually, the mic icon changes into send icon, but in this case, only the mic icon is showing.

### System information (if you can provide):

iOS version: 5.0 (709)
macOS version:
Used XMPP server (domain):
Used XMPP server software & version:
How many accounts are registered in your Monal app: 1

### Additional information like screenshots:
I am attaching the screenshot of the issue.
![iOS](https://user-images.githubusercontent.com/5198904/110492620-5e867380-8118-11eb-8d47-f03cc33d9c34.jpeg)

If you can please activate the logs via `Settings/Log` - then reproduce your issue and then send the file to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
Great spot! Please continue reporting if you see something else!
