### ISSUE TITLE
Add video and audio chat 

### ISSUE THREAD

**Issue by ageekhere** [monal-im/Monal#6]
https://github.com/EricssonResearch/openwebrtc

**Comment by sflc2** [comment]
doesn't monal already do this? I get immediate notifications even when phone is asleep

**Comment by ageekhere** [comment]
now that OpenWebRTC 0.4.2 of iOS SDK out https://twitter.com/OpenWebRTC
Any chance that we can use it in monal? 
https://github.com/EricssonResearch/openwebrtc-ios-sdk/releases/tag/0.4.2

**Comment by anurodhp** [comment]
Will take a look for a future update.

**Comment by Echolon** [comment]
For the record https://nlnet.nl/project/Conversations/

**Comment by Hund** [comment]
What's the status on audio and video calls? The only user I wish to make audio calls with is my girlfriend and she's the only one using Ios and Monal, most are on Android and are using Conversations which already have support for it.

**Comment by Echolon** [comment]
Hi @Hund,

I think there are other important steps to do first, so I think you have to be more patient. Please see the Overview.

Kind regards

**Comment by Hund** [comment]
Where is this "overview"?

**Comment by Echolon** [comment]
@Hund https://github.com/anurodhp/Monal/issues/322

**Comment by Hund** [comment]
Thanks!

I hope you don't mind me asking, do you have plans on adding a feature to allow users to save images they receive?

**Comment by licaon-kter** [comment]
@Hund you can use the share sheet, right? Press the more button iirc,

**Comment by ThatOneCalculator** [comment]
@Echolon how much would it take to sponsor development of this feature? :eyes:

**Comment by Hund** [comment]
> @Echolon how much would it take to sponsor development of this feature? 👀

Check out Snikket if you want audio and video.

**Comment by ThatOneCalculator** [comment]
Is there a Snikket iOS app?

**Comment by ageekhere** [comment]
or Jitsi Meet

**Comment by tmolitor-stud-tu** [comment]
@ThatOneCalculator We already applied for funding for A/V calls by NLNet.

More money could help paying a developer building the UI for A/V calls (thus speeding up things significantly).

Even without money: contributions from SwiftUI developers are always more than welcome!

**Comment by ThatOneCalculator** [comment]
Awesome! I'll be happy to make either a one time dono or something recurring as long as it's used for something related to A/V, I'd love to help out with development but sadly my expertise lies not in Swift/Objective-C

**Comment by tmolitor-stud-tu** [comment]
@ThatOneCalculator Please write me an email regarding the donation (what do you want to donate etc.).

**Comment by tmolitor-stud-tu** [comment]
That's complete now (next beta will contain video call support, current stable already supports audio calls)
