### ISSUE TITLE
Better zh_Hant and zh_Hans support

### ISSUE THREAD

**Issue by comradekingu** [monal-im/Monal#607]
(Got an e-mail asking me to file this as a bug).

iOS version: 14.5 beta 6
macOS version:
Used XMPP server (domain):disroot.org
Used XMPP server software & version:
How many accounts are registered in your Monal app:21

The app is not installable in the Chinese App Store, and without language suport. Please add more support for Simplified Chinese and Traditional Chinese.

I can't find a proper e-mail address to contact with dev team. Thank you all for your great app.

**Comment by comradekingu** [comment]
Currently there is only
https://hosted.weblate.org/languages/zh_Hant/monal/ and
https://hosted.weblate.org/languages/zh_Hant_HK/monal/
which anyone can contribute to.

So I guess adding zh_Hans for translation allows this person to solve the issue.

**Comment by FriedrichAltheide** [comment]
@comradekingu  https://hosted.weblate.org/languages/zh_Hans/monal/
