### ISSUE TITLE
contact list unreadable in alpha build

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#608]
macOS 11.2.3, dark mode
Monal alpha 2021-04-05

Contact list is unreadable. Seems dark mode is not applied to contact list.

<img width="249" alt="contact list" src="https://user-images.githubusercontent.com/5708172/113590092-804d1a80-9632-11eb-98d1-cd039bd8f215.png">

**Comment by foss-** [comment]
Thanks for the quick action. Cannot confirm this is solved in latest main build using April 05 2021 19:36:50.

**Comment by FriedrichAltheide** [comment]
@foss- should now be working on catalyst as well

**Comment by foss-** [comment]
macOS 11.2.3
monal 5 2021-04-06 16:40:59UTC
verified

**Comment by foss-** [comment]
Sorry to re-open. This remains a problem on macOS 10.15.7 (19H524) + monal alpha 5.0 2021-04-09 17:29).

**Comment by FriedrichAltheide** [comment]
@poormusic2001

**Comment by poormusic2001** [comment]
😉

**Comment by FriedrichAltheide** [comment]
@foss- still unreadable?

**Comment by foss-** [comment]
macOS 10.15.7 (19H1030)
Alpha 5.0 (Apr 26 2021: 22:38:51 UTC)
verified
