### ISSUE TITLE
Contact profile view: Several minor UI issues

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#610]
### Description of my issue or feature request:

Those are very minor issues.

- [ ] In the contact profile view the cell lines of the top entries are not drawn until the end of the screen. In the first cell it is the lower end, in the second it is the top end 
<kbd><img src="https://user-images.githubusercontent.com/29168011/113762466-e4e2a500-9718-11eb-8c1f-f81f612114c4.jpeg" width="120"></kbd>

- [ ] In the contact profile view the contact nickname text is not aligned with the lower ones
<kbd><img src="https://user-images.githubusercontent.com/29168011/113763160-a699b580-9719-11eb-89f8-f5474206d737.jpeg" width="120"></kbd>

- [ ] Subcription information too long or not wrapped
<kbd><img src="https://user-images.githubusercontent.com/29168011/113763874-7e5e8680-971a-11eb-9bfd-a21b4f863df4.jpeg" width="320"></kbd>

### System information (if you can provide):

iOS version: 14.4.2
macOS version: 4.9.2 (700)
How many accounts are registered in your Monal app: 1

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
Closing, as this ticket is related to legacy UI
