### ISSUE TITLE
Last message correction: Text field shows default text when editing

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#612]
### Description of my issue or feature request:

This is a minor issue.

In the contact profile view the cell lines of the top entries are not drawn until the end of the screen. In the first cell it is the lower end, in the second it is the top end 
<kbd><img src="https://user-images.githubusercontent.com/29168011/113773406-43fae680-9726-11eb-8981-8fdae97aa266.jpeg" width="320"></kbd>

### System information:

iOS version: 14.4.2
macOS version: 4.9.2 (700)
How many accounts are registered in your Monal app: 1

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
already fixed in beta
