### ISSUE TITLE
Catalyst: custom background not shown after launch of monal

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#614]
macOS 11.2.3
monal 5.0 (2021-04-08 09:57)

Set custom background image in `Settings > Backgrounds`. Close and launch monal. Catalyst only.

**Currently**
Default background image shows. When switching to any chat, custom background then is used.

**Expected**
Once a background has been set it should be used in all occasions where a background image is used including right after launching monal with no chat selected.

**Comment by Echolon** [comment]
Cannot test. but good finding if true!

**Comment by foss-** [comment]
Clearly low prio, didn't get around to file this sooner. As this is macOS only, could you remove iOS tag please.

**Comment by FriedrichAltheide** [comment]
@poormusic2001

**Comment by poormusic2001** [comment]
> @poormusic2001

Check it when I am available.

**Comment by FriedrichAltheide** [comment]
@foss-

**Comment by foss-** [comment]
macOS 11.2.3
Monal 2021-04-26 11:38h
verified
