### ISSUE TITLE
Monal alpha not shutting down when AltTab is open

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#615]
macOS 11.2.3
AltTab 6.18.1
Monal 5.0 (2021-04-08 09:57)

First reported to AltTab as [#904](https://github.com/lwouis/alt-tab-macos/issues/904).

[Monal alpha builds](https://www.eightysoft.de/monal/) not closing when [AltTab](https://github.com/lwouis/alt-tab-macos) is running. When alt-tab is not running monal alpha will close as expected. Curiously this problem does not exist with the stable release of monal which would suggest this is a new problem introduced in recent builds.

Steps to reproduce the bug

    download monal alpha from link above
    unpack and drag to programs
    right-click > open twice as alpha builds are unsigned
    with AltTab running (also linked above) select monal and press ⌘Q to quit

**Currently**
Although the app window is gone the app will remain open and never close.

**Comment by FriedrichAltheide** [comment]
@foss- Please check how the beta behaves

**Comment by foss-** [comment]
My bad. Beta was what I was referring to as stable earlier: Version 5.0 (707) closes as expected.

**Comment by tmolitor-stud-tu** [comment]
if version 5.0 closes as expected I think this can be closed now.

**Comment by foss-** [comment]
Sorry for the confusion. This is however persisting with Alpha 5.0 (May  7 2021: 22:52:44 UTC).

**Comment by foss-** [comment]
Closing as currenty things seem to work as expected.

**Comment by foss-** [comment]
Re-opening as this is persisting.

**Comment by tmolitor-stud-tu** [comment]
I don't know alt-tab and I don't know how it is interacting with software.
It may well be that alt-tab and catalyst apps aren't compatible and that this incompatibility lies within apple's catalyst framework and alt-tab respectively, both of which we can not influence.

I'm tempted to close this unless you can provide more information / insights rather than "it doesn't work like it should".

**Comment by foss-** [comment]
@tmolitor-stud-tu alt-tab dev was kind enough to [look into this](https://github.com/lwouis/alt-tab-macos/issues/904#issuecomment-879544403).

Screencast with details about the problem: https://www.youtube.com/watch?v=7NUO5gqLT8Q

**Comment by tmolitor-stud-tu** [comment]
see my answer in the alt-tab issue: https://github.com/lwouis/alt-tab-macos/issues/904#issuecomment-881890004

**Comment by foss-** [comment]
Testing the latest alpha on macOS Catalina with alt-tab I can confirm what thilo and lwouis describe in the alt-tab issue: Monal lingers around for a bit and then disappears from alt-tab.

However, if Monal is selected from alt-tab while lingering around it appears it is re-opened and then never closed. I am unsure if this is expected or not.

**Comment by tmolitor-stud-tu** [comment]
This is expected: catalyst apps behave more or less like ios apps do
