### ISSUE TITLE
leave and remove chat when removing contact

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#617]
macOS 11.2.3
Monal 2021-04-08 09:57

**Reproduce**

1. create 1:1 chat
2. click on contact avatar (top left of chat)
3. Remove Contact + Yes

**Currently**

Chat remains open

**Expected**

Remove chat

This is especially a problem as clicking contact avatar again and then clicking "Clear omemo session" will result in a crash leaving monal in a crash loop whenever re-opening.

Workaround for that is to open via terminal using `open /Applications/Monal.alpha.app --args --invalidateAccountStates`

**Comment by Echolon** [comment]
I think there is a related issue (not duplicate). Can you review?

**Comment by foss-** [comment]
Tested with Alpha 5.0 (May 23 2021: 06:55:57 UTC)

- have chat with contact about to be removed open
- open contact list
- remove contact from contact list

**Expected**

Chat should be removed

**Currently**

Chat remains in chat list.
