### ISSUE TITLE
add exact version info (build time / build id) to about window

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#618]
**Currently**

menubar Monal > About Monal shows "Version 5.0 (0) for alpha builds.

**Expected**

For both stable, beta and alpha builds more detailed information would be useful. That information is already shown in Monal > Settings > Version were however it can not be copied.

TODOs
- [ ] Make version string in settingsViewController copyable
- [ ] check if we can add a custom string to the about window in the catalyst version

**Comment by FriedrichAltheide** [comment]
@poormusic2001 That's something for you

**Comment by poormusic2001** [comment]
> @poormusic2001 That's something for you

🙂

**Comment by FriedrichAltheide** [comment]
@foss-

**Comment by foss-** [comment]
Alpha 5.0 (Apr 26 2021: 13:08:44 UTC)
macOS 11.2.3
verified
![screenshot](https://user-images.githubusercontent.com/5708172/116104368-ad7c6e00-a6b0-11eb-8c82-051413cac449.jpg)
