### ISSUE TITLE
Update Privacy Policy

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#627]
Hi @anurodhp 

I think you (I can try to help) should under go a review of the Monal Privacy Policy. It is from 2014/2018 and should be updated.

https://monal.im/privacy-policy/

It think I should have its own page without being a blog post if I see that correctly.

Let me know what if I can help.

**Comment by Echolon** [comment]
@anurodhp have you checked on this?

**Comment by anurodhp** [comment]
things haven't changed a ton.  but here is a dedicated page. 

https://monal.im/monal-privacy-policy/

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu pushed a updated version
