### ISSUE TITLE
restrict option to edit message to own messages

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#639]
macOS 11.3.1
Alpha 5.0 (May  7 2021: 22:52:44 UTC)

**Currently**

Nice to have editing of messages. That feature should be restricted to user messages.

**Expected**

Post editing option should not be available for received messages.

<img width="687" alt="editing received message" src="https://user-images.githubusercontent.com/5708172/117550810-993a5880-b042-11eb-9c78-b2fc62e605f0.png">

**Comment by Echolon** [comment]
Wow, thats an interesting finding!

**Comment by tmolitor-stud-tu** [comment]
It was only a local ui bug, no wrong messages could be edited remotely.
