### ISSUE TITLE
better default chat background for light and dark mode

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#640]
**Currently**

Low contrast between chat background (no image selected) and message info text.

**Expected**

Use better default chat background:
Light: # FFFFFF
Dark: # 131313

<img width="72" alt="low contrast no background image" src="https://user-images.githubusercontent.com/5708172/117551204-def82080-b044-11eb-8adb-7332b82f156a.png">

**Comment by zainashraf1562** [comment]
Gsoc Applicant: I would like to work on this issue.

**Comment by tmolitor-stud-tu** [comment]
Fixed in https://github.com/monal-im/Monal/commit/68efd1702097bf8669f5df1391abc15f142c90ea by #1019
