### ISSUE TITLE
Consistency: close button should always show on same location

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#641]
**Currently**
`Close` location varies.
Contacts: top left
Settings: top right

**Expected**
Close should be placed in the same location, probably top right. Personally would prefer to use "x" instead of close to keep the dialogs a bit cleaner.

<img width="241" alt="contacts" src="https://user-images.githubusercontent.com/5708172/117785739-2816c300-b245-11eb-8219-5aba579e7f71.png">
<img width="408" alt="settings" src="https://user-images.githubusercontent.com/5708172/117785742-28af5980-b245-11eb-8d61-25190d25cea2.png">

Aligning `x` with Dialog title would save some space and allow to more efficiently use dialog space. Something like:
<img width="408" alt="x" src="https://user-images.githubusercontent.com/5708172/117787684-f999e780-b246-11eb-8fcf-e8a9368470f6.png">

**Comment by Echolon** [comment]
Thanks for reporting!

can you reference the big UI change issues?

**Comment by tmolitor-stud-tu** [comment]
fixed, close is now on the left side...
