### ISSUE TITLE
adapt 1:1 default chat icon

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#645]
Liking the new muc default icon. It follows monal default color, uses nice contrast and communicates muc very well.

Maybe the 1:1 default icon should be adapted to that? Currently has low contrast and not sure if the curent birdhead shape is the best solution. Why not follow same color scheme with just a single person shape in the icon. Should make for a nice consistent look and be easy to understand and see by users.

<img width="59" alt="muc + 1-1" src="https://user-images.githubusercontent.com/5708172/118396294-2d15b100-b64f-11eb-87bd-20c03563b372.png">

**Comment by Echolon** [comment]
Thanks @foss- its pretty much an early implementation. Lets first have a working implementation.

**Comment by tmolitor-stud-tu** [comment]
Normally people should use avatars.

Having a default avatar should either be an "ugly" one (like the currently used one), to motivate people to set an avatar, or a default avatar generated from the contact's jid using [XEP-0392: Consistent Color Generation](https://xmpp.org/extensions/xep-0392.html).

In the long run we're aiming for XEP-0392 avatars like done in Conversations, in the meantime the current bird-shaped avatar has to suffice.
