### ISSUE TITLE
Certificate expired for ios13push.monal.im

### ISSUE THREAD

**Issue by aumatt** [monal-im/Monal#651]
I'm seeing s2s connections to ios13push.monal.im fail with a certificate error:

`Destroying outgoing session XXXX ->ios13push.monal.im: Your server's certificate has expired`

Verified with openssl:

`openssl s_client -showcerts -starttls xmpp -connect ios13push.monal.im:5269`

<snip>

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:68:27:ba:ba:50:70:3e:1b:bd:6d:6a:a7:24:10:c7:05:93
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Validity
            Not Before: Mar 11 15:31:58 2021 GMT
            Not After : Jun  9 15:31:58 2021 GMT
```

**Comment by FriedrichAltheide** [comment]
should be fixed now
