### ISSUE TITLE
Follow-up and improvements to file upload UI

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#653]
https://github.com/monal-im/Monal/issues/596 is done.

This issue here is about some UI refinement on macOS.

**Reproduce**

- drag image to chat view
- with mouse pointer active in compose box press `Enter` key

**Currently**

Nothing

**Expected**

Image should be sent. This becomes even more confusing as I would assume anything that is typed while an image is opened would be sent together with the image as image description (like e.g. signal handles this). But actually when typing while image is open in monal and pressing enter, only the text is sent but not the image. This is very confusing.

**Comment by janst97** [comment]
The wrong behavior when sending messages by using the enter key should be fixed with 9f2fd6b.

**Comment by foss-** [comment]
Should we leave this open or do you want a separate issue for the remaining problem of sending an image with a description? Is that possible with xmpp?

**Comment by FriedrichAltheide** [comment]
I'm not aware of a XEP for sending Images with a description in the same message. Closing

**Comment by Echolon** [comment]
Maybe this one day becomes of interest here: http://larma.de/xeps/sfs.html

See also: https://xmpp.org/extensions/xep-0447.html
