### ISSUE TITLE
Add a reply option for message

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#667]
![IMG_2C9A369FF383-1](https://user-images.githubusercontent.com/2963008/122301683-b3047080-cf09-11eb-8ec8-b279a03bae3d.jpeg)

When I want "reply" to some message, I must copy it, type "> " and paste it into textbox.
I think that dedicated button "Reply" will be very useful - Conversations does replies in that way

**Comment by tmolitor-stud-tu** [comment]
Already implemented, see the last couple of beta releases

**Comment by Echolon** [comment]
@roman901 anyway, thanks for reporting! You can test the Testflight Beta already if you want.

**Comment by Echolon** [comment]
duplicate of #239
