### ISSUE TITLE
Feature: ephemeral messages - add option to delete messages after x days, weeks, hours

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#669]
### Description of my issue or feature request:

Add option to delete messages after x time.

Some inspiration how signal handles this:
defaults:
<img width="221" alt="defaults" src="https://user-images.githubusercontent.com/5708172/122554490-56a06e80-d039-11eb-906a-83a0a57805b7.png">
custom:
<img width="358" alt="custom time" src="https://user-images.githubusercontent.com/5708172/122554486-5607d800-d039-11eb-9efb-f99bda6d211c.png">

**Comment by licaon-kter** [comment]
With a nice message:
> <b>Warning:</b> This will not delete copies of these messages that are stored on other devices or servers. 

Right? :)

**Comment by foss-** [comment]
Certainly, so does this feature not make any sense for a decentralized system? Not feasible at all?

**Comment by licaon-kter** [comment]
For local history, it does. Just make sure users understand its limitations.

**Comment by Echolon** [comment]
I'm with @licaon-kter on this feature. I effectively does not make sense if you dont have the control about all instances

**Comment by Echolon** [comment]
but it is kind of related to #180 #271

**Comment by tmolitor-stud-tu** [comment]
makes no sense for a decentralized system, closing this issue
