### ISSUE TITLE
Push not working on Mac and iPhone, 4G or wifi, different networks

### ISSUE THREAD

**Issue by patrixl** [monal-im/Monal#671]
### Description of my issue or feature request:

Although in my ejabberd.log I can see s2s connections to ios13push.monal.im, my clients on macOS (Big Sur) and iOS 14 are not showing connections to the Monal push servers or Apple push servers.  As far as I know I don't have anything blocking these domains, push notifications also work for other apps and other XMPP clients. Background app refresh is enabled for Monal on my iPhone.

### System information (if you can provide):

iOS version: 14.6
macOS version: 11.4
Used XMPP server (domain): sorry, private
Used XMPP server software & version: ejabberd 20.01
How many accounts are registered in your Monal app:  1

### Additional information like screenshots:
<img width="403" alt="Screen Shot 2021-06-21 at 11 54 38 AM" src="https://user-images.githubusercontent.com/4702983/122701127-88a71000-d287-11eb-9c1c-2f0664018b7c.png">

If you can please activate the logs via `Settings/Log` - then reproduce your issue and then send the file to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
Which Monal version are you using on iOS and on macOS?

**Comment by patrixl** [comment]
macos: 4.9.2 (705)
ios: 4.9.2 (700)

**Comment by FriedrichAltheide** [comment]
Could you please try the latest beta?
macOS: https://monal.im/macOS/Monal-macOS.zip
iOS: https://testflight.apple.com/join/RjIlyvqa

BTW: check on macOS that you granted monal notification permissions (macOS system settings)

**Comment by patrixl** [comment]
Notification permissions are granted (as per the screenshot as well, but I confirmed again just in case).

Will try the betas and report back

**Comment by patrixl** [comment]
Ok now I can see the checkboxes for push server etc.. Very nice. Haven't received any messages yet, but at least it looks promising. Thanks!

**Comment by Echolon** [comment]
@patrixl thanks for reporting. Let us know if there is anything else.
