### ISSUE TITLE
Do not notify on every public MUC message

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#674]
### Description of my issue or feature request:

Currently: Every post in a public MUC is shown as new message.

Expected: Only notify if my nickname is mentioned.

### System information (if you can provide):

Monal: 5.0
iOS version: 14.6
Used XMPP server (domain): yax.im
Used XMPP server software & version:
How many accounts are registered in your Monal app: 1

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Will be implemented in monal 5.1

**Comment by tmolitor-stud-tu** [comment]
fixed in latest alpha
