### ISSUE TITLE
OMEMO QR looks too wide on Catalyst/iPad

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#679]
<img width="426" alt="Снимок экрана 2021-07-02 в 13 40 25" src="https://user-images.githubusercontent.com/2963008/124262806-2bd70f80-db3b-11eb-9364-93a0cbf6d030.png">
Version: Monal 5.0 on iPad and current beta Catalyst build from website on Mac

**Comment by Echolon** [comment]
@roman901 thank you for your report! Those things help a lot!

**Comment by tmolitor-stud-tu** [comment]
Is that still the case or can this ticket be closed now?

**Comment by roman901** [comment]
Checked I right now and it seems to be OK
