### ISSUE TITLE
Use equal Close button position in Settings and Contact Detail modal windows

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#682]
### Description of my issue or feature request:
Settings:
<img width="425" alt="Снимок экрана 2021-07-02 в 14 23 32" src="https://user-images.githubusercontent.com/2963008/124267559-15cc4d80-db41-11eb-9d69-1125532b6d84.png">
Contact Details:
<img width="436" alt="Снимок экрана 2021-07-02 в 14 23 50" src="https://user-images.githubusercontent.com/2963008/124267594-2086e280-db41-11eb-9e50-fd10adaa6fc2.png">

Apple-way: place Close button at left side

### System information (if you can provide):

iOS version: 5.0 beta
macOS version: 5.0 beta

**Comment by tmolitor-stud-tu** [comment]
Good catch. We will overhaul the contact details screen for monal 5.1, the close button will be moved, too.

**Comment by tmolitor-stud-tu** [comment]
We just implemented the close button move for 5.0.1 already, closing this :)
