### ISSUE TITLE
Follow system color scheme on Catalyst

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#683]
### Description of my issue or feature request:
On macOS I have chosen dark + orange colors. Monal uses correct dark theme and orange accent for "attach" and "send" buttons, but still use light-green for top panel

<img width="500" alt="Снимок экрана 2021-07-02 в 15 47 14" src="https://user-images.githubusercontent.com/2963008/124276667-c724b080-db4c-11eb-8a6d-c0edfe8b27a4.png">
<img width="115" alt="Снимок экрана 2021-07-02 в 15 47 23" src="https://user-images.githubusercontent.com/2963008/124276695-cbe96480-db4c-11eb-9107-07fc33c35e0a.png">

**Comment by FriedrichAltheide** [comment]
fixed in alpha 5d69f84e933d660304df50549f1e3fe96c946b8e

**Comment by roman901** [comment]
@FriedrichAltheide broken in latest alpha
