### ISSUE TITLE
Trim incoming messages

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#684]
<img width="236" alt="Снимок экрана 2021-07-02 в 17 15 40" src="https://user-images.githubusercontent.com/2963008/124287811-21c40980-db59-11eb-9983-f8a25b7035af.png">
<img width="120" alt="Снимок экрана 2021-07-02 в 17 15 37" src="https://user-images.githubusercontent.com/2963008/124287820-24266380-db59-11eb-981d-7c4c2bbf0ed0.png">
Some clients can send messages with newline at start of message (or their clients doesn't trim it before sending)

**Comment by tmolitor-stud-tu** [comment]
I don't want to trim newlines or spaces at the start of a message for the message view (ascii art etc.).

But trimming the preview in your upper screenshot sounds feasible, will be implemented in Monal 5.0.1 :)

**Comment by roman901** [comment]
@tmolitor-stud-tu I think that newlines at start of message makes no sense to resulting ASCII images, but very distracting at daily use :)

**Comment by roman901** [comment]
![IMG_098A4D6BC649-1](https://user-images.githubusercontent.com/2963008/124290223-dbbc7500-db5b-11eb-95e2-07f8fadd8388.jpeg)
Newlines also appears in pushes

**Comment by Echolon** [comment]
@tmolitor-stud-tu please lets only close on merge

**Comment by tmolitor-stud-tu** [comment]
@Echolon it *is* merged already

**Comment by tmolitor-stud-tu** [comment]
@roman901 implemented (it now trims for all incoming messages everywhere)
