### ISSUE TITLE
Share with Monal on iPad doesn't work.

### ISSUE THREAD

**Issue by donpatrice** [monal-im/Monal#688]
### Description of my issue or feature request:

Sharing links to websites on iPad doesn't work.

**Steps to reproduce:**

1. Open website in Safari
2. Press the share button
3. Select Monal
4. Select a recipient
5. Press send (or what ever it is in the english version, in German it's posten)
6. Open Monal
7. Go to the recipient
8. See that there is nothing, at least no post

**Expected behavior:**
See the post

On iPhone it's working.

### System information (if you can provide):

iPadOS version: 14.6
Monal version: 5.0 (749)
Used XMPP server (domain):
Used XMPP server software & version: ejabberd 21.01-2~bpo10+1
How many accounts are registered in your Monal app: 1

### Additional information like screenshots:

If you can please activate the logs via `Settings/Log` - then reproduce your issue and then send the file to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
Fixed in alpha.
Fix will be included in the next 5.0.1 beta 5ec7bc08c77389a24dbe6d3edba3b7d316d9cdce
