### ISSUE TITLE
Offline Account Status Explained

### ISSUE THREAD

**Issue by boroli** [monal-im/Monal#691]
### Description of my issue or feature request:

If the account is offline, for whatever reason, there's only a red dot next to the account name, but no further explanation underneath the account name. Without knowing this matter of fact, there seems to be no other way or information in Monal to retrieve further information of the account status. That's not really self explaining or obvious for an ordinary user.

Can you please add a simple "Offline" underneath the account name, as you're displaying also additional information in case the account is online.

Also, how can it be determined, if Monal tries to reconnect? Is there a "reload" button, or do I always need to actively deactivate/activate the account?

**Comment by tmolitor-stud-tu** [comment]
Monal will continously try to reconnect everey ~8 seconds, no need to deactivate/activate your account.
If monal can't connect in about 2 seconds while having a good wifi connection, you should check if the SRV records of your server are correct.

**Comment by boroli** [comment]
Thanks for the explanation. Will Monal at one point run against a time out and stop trying to reconnect, or will this go forever?

In that instance, the server went actually offline. But the only symptom Monal showed, that Monal was unable to send messages. It just constantly tried to send messages, but nowhere it popped up that the server was actually gone. So not really easy for an ordinary user to comprehend what was going on.

**Comment by tmolitor-stud-tu** [comment]
Yeah, that "unable to sync" notification tells the user that it could not send/receive messages.

If you then open the app long enough (~8 seconds) you will get an error badge in the app telling you the exact error that happened. Or no error, if the problem was transient and already went away.

**Comment by tmolitor-stud-tu** [comment]
I added the text "Unable to connect" under the account name.

Everythin else seems to be resolved, too, closing this now.
