### ISSUE TITLE
Not running in Backgound IOS Iphone

### ISSUE THREAD

**Issue by thonton** [monal-im/Monal#693]
### Description of my issue or feature request:
Since Version 5.0, the Monal App on my Iphone doesnt runs in Background. It stops working/pushing /disconnects after a few minutes, after closing the app.
In previous versions, it worked fine. Strange, no Push-Notification is activated? see below.

i completly removed the profile and monal and reinstalled fresh and added the account and allowed push-notfication.

### System information (if you can provide):

iOS Monal & system version: 5.0, iOS 14.6, IPhone 11
Used XMPP server (domain): jabber.cbxnet.de (own)
Used XMPP server software & version:
How many accounts are registered in your Monal app: 1
What XEPs are showed as green under Settings-->Account-->(i) in server column (under advanced settings): 0191, 0198, 0199, 0237, 0280, 0313, 0363, 0163

### Additional information like screenshots:
![Bildschirmfoto 2021-07-09 um 13 50 38](https://user-images.githubusercontent.com/84778434/125074919-3acf3c00-e0be-11eb-8b8d-0795820d5bc1.jpeg)

are these options checked or not? i would say No.

**Comment by licaon-kter** [comment]
Not a duplicate of https://github.com/monal-im/Monal/issues/676 ?

**Comment by Echolon** [comment]
@licaon-kter I was also wondering.

@thonton may you check the issue with your problem first?

**Comment by thonton** [comment]
you're right. but i dont see #676 in the issue-list. if i put it directly 676 in the url, i can see the issue 

edit:
because it's closed. sorry.
we'll check our server settings
