### ISSUE TITLE
5.0 is 700 or 750?

### ISSUE THREAD

**Issue by Neustradamus** [monal-im/Monal#695]
Here, we can see 700 and 750, it is possible to solve it?
- https://github.com/monal-im/Monal/releases/tag/Build_iOS_750

**Comment by poormusic2001** [comment]
Settings->About->Version 

![66C427A0-D53C-41FF-B0C3-E8EE92664966](https://user-images.githubusercontent.com/10296589/125384981-44151d00-e3cc-11eb-8b3d-bc73d759a2f9.jpeg)


> Here, we can see 700 and 750, it is possible to solve it?
> 
> * https://github.com/monal-im/Monal/releases/tag/Build_iOS_750

**Comment by Neustradamus** [comment]
Yes @poormusic2001, the team must update the text ;)

**Comment by Echolon** [comment]
I fixed it
