### ISSUE TITLE
Question on mod_mam / xep-0313

### ISSUE THREAD

**Issue by Luticus** [monal-im/Monal#696]
### Description of my issue or feature request:
My users on Monal for ios have not been getting IMs while offline of when the application is in the background.

My user gets this error:
![monalerror](https://user-images.githubusercontent.com/7807109/125524840-2ca5291d-6e67-40f7-87da-a3254abbef32.jpeg)

But my server has mam configured as far as I can tell:
![ejabberdmam](https://user-images.githubusercontent.com/7807109/125525839-6260e301-9e5f-448c-89d8-ec9d579c050c.png)

And my andriod conversations client seems to think mam is fine:
![conversationsandriod_mam](https://user-images.githubusercontent.com/7807109/125525904-07940cc4-5cef-436b-893f-6b839b17620f.jpeg)

### System information (if you can provide):

iOS Monal & system version: newest?

Used XMPP server software & version: ejabberd 20.07-1~bpo10+1

**Comment by tmolitor-stud-tu** [comment]
You most likely have an old version of ejabberd/mod_mam that does not support mam:2 but only mam:1 or mam:0 which monal does not support.

**Comment by tmolitor-stud-tu** [comment]
You should enable the stream management module (XEP-0198), too (it seems like you don't have enabled that).

**Comment by Luticus** [comment]
I'll check into it. I'm using ejabberd from Debian backports so i think it's mostly up-to-date.  Thanks.

**Comment by Luticus** [comment]
@tmolitor-stud-tu, it turns out that I had the mod_stream_mgmt mod enabled in ejabberd, but it's resend_on_timeout was set to "if_offline" I have adjusted it to "true" to see if that helps. all other values are default. If there's any specific configuration options for the mod that you can recommend, I'd love to know what they might be. Thanks again for your help!

**Comment by Luticus** [comment]
Also as a test, I went to the ejabberd website and found the .deb for their absolute newest version and installed it on my debian system.  It seems to be working for the moment and everything looks good from the conversations app perspective. I'll have to get a hold of one of my iphone users tomorrow and see if the problem is resolved.

**Comment by Luticus** [comment]
@tmolitor-stud-tu I'm pretty sure it's still not working. like it's not sending push notifications i think. My friend said he's still not getting messages when monal goes into the background.

**Comment by Luticus** [comment]
[
![messages_0](https://user-images.githubusercontent.com/7807109/125711855-4c980a4f-fca9-4235-928c-d42f2b0e0916.jpeg)
](url)
My user says they are unable to enable the push setting, and that iOS has notifications enabled for Monal.

**Comment by FriedrichAltheide** [comment]
The account section is missing in the screenshot. Please scroll down and take a second screenshot

**Comment by tmolitor-stud-tu** [comment]
Did you check that **bidirectional** server to server communication between your server and ios13push.monal,.im works?

**Comment by tmolitor-stud-tu** [comment]
Second question: are you sure you enabled a push module (XEP-0357) in the first place?

**Comment by Luticus** [comment]
@tmolitor-stud-tu I do have the mod_push enabled but it's configuration is defaulted:  mod_push: {}

I'm not sure how to check that ios13push.monal,.im works, I need to check some documentation for that I assume. If there's some good reading you can recommend or advice on how to check that or to properly configure mod_push to work with it, that would be awesome!

Thanks!

**Comment by Luticus** [comment]
@FriedrichAltheide  I'll check with my user and see if I can get that screenshot for you, unfortunately I don't use any IOS devices so I can't do it personally. I'm just trying to let my users who do use IOS have a first class experience with the chat server.

**Comment by tmolitor-stud-tu** [comment]
@Luticus Just grep your server's logs for `ios13push.monal.im`
If everything is okay you should find lines containing `inbound` and lines containing `outbound`.
If there is an error, you will get the error using this grep, too.

**Comment by Luticus** [comment]
I do see lines like this:  

ejabberd.log:2021-07-13 14:44:04.242 [info] <0.14486.1>@ejabberd_s2s_out:init:275 Outbound s2s connection started: example.com -> ios13push.monal.im
ejabberd.log:2021-07-13 14:44:08.715 [info] <0.14486.1>@ejabberd_s2s_out:handle_auth_success:209 (tls|<0.14486.1>) Accepted outbound s2s EXTERNAL authentication example.com -> ios13push.monal.im (34.227.106.56)

But I'm not seen any inbound entries, maybe I need to check my s2s inbound port?

**Comment by Luticus** [comment]
I checked my s2s port and it's open. Still no luck.

**Comment by tmolitor-stud-tu** [comment]
@Luticus 2021-07-13 is more than 9 days back, don't you have something newer?

**Comment by tmolitor-stud-tu** [comment]
@Luticus Do you have a proper TLS certificate for your s2s?
Monal's appserver won't talk unencrypted to you.

**Comment by tmolitor-stud-tu** [comment]
@Luticus Did you enable s2s dialback?

**Comment by FriedrichAltheide** [comment]
@Luticus Please send a link to your s2s IM Observatory result (https://xmpp.net)

**Comment by Luticus** [comment]
I'm checking into it now.

**Comment by Luticus** [comment]
@tmolitor-stud-tu These are newer and should be with TLS enabled.

2021-07-22 09:12:12.237 [info] <0.515.0>@ejabberd_s2s_out:init:289 Outbound s2s connection started: example.com -> ios13push.monal.im
2021-07-22 09:12:13.529 [info] <0.515.0>@ejabberd_s2s_out:handle_auth_success:223 (tls|<0.515.0>) Accepted outbound s2s EXTERNAL authentication example.com -> ios13push.monal.im (34.227.106.56)

Not sure about dialback, looking into it.

**Comment by Luticus** [comment]
@tmolitor-stud-tu Yes, mod_s2s_dialback is enabled with it's default configuration with no server restrictions.

**Comment by Luticus** [comment]
After messing with my firewall I've made some progress I think. I'm now seeing inbound lines:
2021-07-22 14:13:34.893 [info] <0.775.0>@ejabberd_s2s_in:handle_auth_success:183 (tls|<0.775.0>) Accepted inbound s2s EXTERNAL authentication ios13push.monal.im -> example.com (::ffff:34.227.106.56)

however I'm also seeing:
mod_push:notify:514 ios13push.monal.im rejected notification for joe@example.com (738FBBAF-3A41-5C53-9B37-E405192505ED) temporarily: Ratelimit reached (resource-constraint)

is there some configuration to avoid the ratelimit issue?

My users still don't seem to be getting notified, but I need to check up with them again.

**Comment by Luticus** [comment]
I *think* I have it working now, but I have one follow on question. What data gets pushed to the notification server? Should my users be concerned about privacy with this enabled?

**Comment by FriedrichAltheide** [comment]
@Luticus Have a look at https://monal.im/monal-privacy-policy/
Push is working -> Closing

**Comment by tmolitor-stud-tu** [comment]
@Luticus rate limiting does no harm, it just makes sure to only send one push every 20 seconds, see here for a better explanation: https://github.com/tmolitor-stud-tu/mod_push_appserver/#configuration-options-mod_push_appserver config item `push_appserver_rate_limit`

Other wording, same explanation: https://github.com/tmolitor-stud-tu/mod_push_appserver/releases/tag/5.2.0
