### ISSUE TITLE
MUC private messages

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#700]
So, I understand that's issue can be "epic".

In XMPP MUC's there is a private messaging without JID's violation. Most of clients supports it like normal chats, or with very strange Conversaitions-way.

**Comment by Echolon** [comment]
@roman901 I kindly ask you to use the issue template and the sections which make sense for Feature Requests.

**Comment by Echolon** [comment]
Other then that, the devs have decided to not support the feature in #284.

Therefore, I need to close this unfortunatley.
