### ISSUE TITLE
Autofocus on textbox in chat window

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#704]
By default, I must directly click to it to activate text input, or must do much "tabbing"

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by guodong323** [comment]
Could you please assign me to tasks related to the Monal project? I am committed to delivering my best and will adhere to all guidelines and requirements.

**Comment by tmolitor-stud-tu** [comment]
@guodong323  nothing happened here, removing you from this issue
