### ISSUE TITLE
Privacy enhancements.

### ISSUE THREAD

**Issue by Ocellated** [monal-im/Monal#706]
### Description of my issue or feature request:

There should be a way to opt out of crash reporting and other phoning home. I don't want my device to connect to Fabric’s Crashlytics (Google), TvPortal, MyNepali, Sleeptrack and WordSwat even if it is anonymous. 
I would make connecting to these services opt in however, opt out would still be better than nothing.
I think the app is great apart from this issue and I would really like to use this app as it is much better than its competition, but I don't want it bouncing around the internet connecting to Google and other services.

Also, is there a way to disable connections to `push.monal.im`? I am guessing if I disable notifications it won't connect to `push.monal.im` and I am ok with disabling notifications.

Ideally, the user should have the choice that the app only connects to their chosen XMPP server, not Monal or these other third parties.

**Comment by Echolon** [comment]
Hi @Ocellated,

thank you for your report.

First of all: Can you specify the Monal version you use?

I think Crashlytics has been removed already.

Regarding push: Monal.is asking you if you want to allow push notifications and you can disable it. However we need to ask @tmolitor-stud-tu if that does really not connect to the push server.

And yes, if you deactivate, you will not reveive any push notifications anymore.

**Comment by FriedrichAltheide** [comment]
#627

**Comment by FriedrichAltheide** [comment]
The privacy policy is now up to date with our current code base: https://monal.im/monal-privacy-policy/

**Comment by Ocellated** [comment]
Sorry, I read the old privacy policy because the privacy policy linked on the app store was the old one.

So I assume connections to Fabric’s Crashlytics (Google), TvPortal, MyNepali, Sleeptrack and WordSwat are no longer made?

And if I disable notifications, it won't connect to `push.monal.im` only my XMPP server, correct?

Finally, at the bottom, it says the new app collection is "controlled by iOS and macOS global settings". I don't mean to get off-topic, but how do I disable this on iOS 14.5?

**Comment by FriedrichAltheide** [comment]
ref. ee41eb89d6eb7226a769c8e3785d1ba15704fd49

**Comment by Ocellated** [comment]
So in the latest update disabling notifications disables connecting to `push.monal.im`? In the current version the boxed is checked and it doesn't let me uncheck it

**Comment by tmolitor-stud-tu** [comment]
@Ocellated yes the latest alpha version will do this.
The next beta will include this, too.
