### ISSUE TITLE
Enable OMEMO in chats by defalut

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#709]
### Description of my issue or feature request:
Right now Monal doesn't try to activate OMEMO by default, and it can be confusing. Just realized, that some of my messages doesn't encrypted because I doesn't seen that encryption is disabled.

Maybe it is worth making the indication of disabled encryption more explicit and flashy.

### System information (if you can provide):

iOS Monal & system version: Monal 5.0 Beta / iOS 14.6
macOS Monal & system version: Monal 5.0 Alpha / Big Sur

If you can reproduce your issue: send us your log file (`Settings/Log`) to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[x] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/anurodhp/Monal/labels
[x] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings-->Account-->(i) in server column (under advanced settings)
[x] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
dupl. of #234
