### ISSUE TITLE
Wrong error message while OMEMO-encrypted messages processing

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#710]
### Description of my issue or feature request:
Installed new version on Monal on Mac -> generated new OMEMO key.
Wrote a message to someone, opened chat on phone -> got strange decrypting error.
I understand, that key doesn't trusted fully (yellow "trust"), but this looks like unexpected error. 

### System information (if you can provide):

iOS Monal & system version: Monal 5.0 Beta / iOS 14.6

### Additional information like screenshots:
![IMG_800F3B9FA453-1](https://user-images.githubusercontent.com/2963008/126479774-3fdf1632-97c4-4e3c-a7b5-022bc3968cda.jpeg)

If you can reproduce your issue: send us your log file (`Settings/Log`) to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[x] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/anurodhp/Monal/labels
[x] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings-->Account-->(i) in server column (under advanced settings)
[x] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by Echolon** [comment]
Thanks for reporting!

**Comment by FriedrichAltheide** [comment]
This error message is expected after an omemo error. This could be the result of a timing edge case. Please try to send a few omemo encrypted messages between the devices with a few seconds in between. Does the error persist?

**Comment by roman901** [comment]
@FriedrichAltheide no, new messages sent and received normally

**Comment by tmolitor-stud-tu** [comment]
I think I can close this then
