### ISSUE TITLE
How to Enter Contact's Omemo Encryption Keys witout QR Code

### ISSUE THREAD

**Issue by samirparikh** [monal-im/Monal#713]
How do I enter a contact's Omemo Encryption Keys if I don't have a QR code for them?

![monalContactEncryptionKeys](https://user-images.githubusercontent.com/10586237/126566125-6f871fac-150b-4411-8c32-69bcc1c89805.png)
I am running version 5.0 (750) on iOS 14.6.

**Comment by FriedrichAltheide** [comment]
Please use the issue template.
A QR code will never add omemo encryption keys. It will only verify them.
