### ISSUE TITLE
Monal Im iOS crash at startup

### ISSUE THREAD

**Issue by izanp** [monal-im/Monal#714]
### System information (if you can provide):

iOS Monal & system version: 5.0.1
macOS Monal & system version: iOs 14.6
Used XMPP server (domain): yax.im
Used XMPP server software & version:n/a
How many accounts are registered in your Monal app: 1
What XEPs are showed as green under Settings-->Account-->(i) in server column (under advanced settings): n/a

### Additional information like screenshots:

If you can reproduce your issue: send us your log file (`Settings/Log`) to info (at) monal (dot) im.
PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)

---
[ ] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/anurodhp/Monal/labels
[ ] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings-->Account-->(i) in server column (under advanced settings)
[ ] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by izanp** [comment]
Sorry, dont get confused
This is a current error on ios only.
Both current test flight and app store version does the same.

If airplane mode is enabled, the app dont crash but as soon as airplane mode is disable it can ash...

Only way to fix this is to uninstall the app and reinstall.

Unable to find out what triggers it at the moment.

I have a debug file of 44mb
Where can I upload it?

**Comment by izanp** [comment]
Im unable to do the checks within the app at the moment but did check for similar crash reports on github.... none found
I believe my report is the first

**Comment by tmolitor-stud-tu** [comment]
Please sent the logfile via mail to ***@***.***

Am 22. Juli 2021 07:12:49 MESZ schrieb izanp ***@***.***>:

**Comment by tmolitor-stud-tu** [comment]
Nice, github removed my mail address :D
Please sent it to thilo+monal@eightysoft.de

**Comment by izanp** [comment]
Does your email have a + sign in it?
Dont you have a next cloud or dripbox for large file uploads like these?

**Comment by tmolitor-stud-tu** [comment]
@izanp yes it has
Nextcloud is here, too: https://dyn.eightysoft.de/nextcloud/index.php/s/o25SzX8zaHKomMt

**Comment by izanp** [comment]
Done

**Comment by tmolitor-stud-tu** [comment]
@izanp nothing here yet, did you upload to nextcloud vor did you send it via mail?

**Comment by izanp** [comment]
> @izanp nothing here yet, did you upload to nextcloud vor did you send it via mail?

Emailed

**Comment by FriedrichAltheide** [comment]
@izanp try TestFlight build 5.0.1 (752)
