### ISSUE TITLE
Make Monal more cross platform and support Android and GNU/Linux

### ISSUE THREAD

**Issue by Porrumentzio** [monal-im/Monal#715]
I discovered Monal and seems a great program, but I can't use it as I'm not using Apple systems. As Monal seems so good, it would be awesome if it could be used on Android and GNU/Linux

**Comment by licaon-kter** [comment]
[Conversations](https://conversations.im) doesn't work on Android?

[Dino](https://dino.im) or [Gajim](https://gajim.org) don't work on Linux?

/close as wontfix

**Comment by Porrumentzio** [comment]
Yes, they work and I use them. Monal seems more modern looking and easier to suggest to "normies"

**Comment by Echolon** [comment]
Hey @Porrumentzio,

thanks for suggesting, but I think with the current resources that is not possible :-(

**Comment by licaon-kter** [comment]
@Porrumentzio Keep in mind:
* Monal follows, or tries to, the Apple rules for the interface, it wants to be familiar like iMessage, not sure how good that "looks" on _other platforms_
* Monal is still behind, feature wise, Conversations and Dino (and Siskin on iOS FYI) already have OMEMO in groups and Audio/Video calls.

**Comment by Porrumentzio** [comment]
Thanks for explaining :)
