### ISSUE TITLE
Show downloaded files (images, videos) in Monal user folder

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#728]
### What Monal Release channel are you using?

AppStore

### iOS system version

14.6

### iOS Monal version

5.0.0 (Build 750)

### Used XMPP server (domain)

jabber.de

### How many accounts are you using in Monal?

1

### What happened?

The user intended to access and save a received video on the system. However, pressing or further finding of the video was not possible.

Moreover, in the file manager Monal folder no images or video are shown at all.

It has been wondered if this is a user permission issue.

A nice user-friendly solution could be to show all files in an in-app gallery maybe.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Already implemented in alpha, will be in Monal 5.2.
