### ISSUE TITLE
Write text for section: About

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#734]
### 

- [X] I understood that this template is only for feature requests and not for bug reports

### 

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Write a proper text for the Abouy sevtion under Settings

**Comment by Echolon** [comment]
The current website about could be used for this:

https://github.com/monal-im/monal-im.org/blob/master/content/about.md

**Comment by tmolitor-stud-tu** [comment]
Done, the website is linked to the about section in app settings now :)
