### ISSUE TITLE
[Bug]: Nickname misaligned in MUC when sending images / files

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#736]
### What Monal Release channel are you using?

AppStore

### iOS system version

14.6

### iOS Monal version

5.0.1

### Used XMPP server (domain)

yax.im

### Which XMPP-Server software are you using?

Prosody

### How many accounts are you using in Monal?

1

### What happened?

Please see this image:

<kbd><img src="https://user-images.githubusercontent.com/29168011/131248407-350fb9bc-43bc-4449-b547-c64df0731cea.PNG" width="320"></kbd>

The nickname of the send file is misaligned.

Obviously a minor issue.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Will be fixed when we migrate the chatview to swiftui, I'll close this
