### ISSUE TITLE
[Bug]: iOS authorization contact

### ISSUE THREAD

**Issue by Username7823553** [monal-im/Monal#739]
### What Monal Release channel are you using?

AppStore

### iOS system version

14.7.1

### iOS Monal version

5.0.1(761)

### Used XMPP server (domain)

jabb.im

### How many accounts are you using in Monal?

2

### What happened?

A problem happened! I don't see messages about authorization ? Can I make it automatic ?

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please check the contact request list in Monal
View of your active chats -> tap the icon with the two torsi in the upper right corner -> tap the "+" button -> Contact requests (second list element)

**Comment by Username7823553** [comment]
FriedrichAltheide

I don't see messages from new contacts before I confim auth requests ? Can I add any notify that someone make contact request ?

**Comment by FriedrichAltheide** [comment]
Messages from a new contact will be displayed as a normal chat. But omemo might not work until you approve the contact. There ist no UI to visualise new contact requests otherwise right now
