### ISSUE TITLE
[Bug]: File to large to attach any files or pictures

### ISSUE THREAD

**Issue by ioscanner** [monal-im/Monal#740]
### What Monal Release channel are you using?

Beta

### iOS system version

15.0 same issue with other versions

### iOS Monal version

5.0.1 (761)

### Used XMPP server (domain)

auth.sms.gdn

### Which XMPP-Server software are you using?

ejabberd

### How many accounts are you using in Monal?

1

### What happened?

I can receive pictures and files.  But anytime I try to send any file even a small image it fails to send. Stating: Could not upload file: Upload Error: not-acceptable ( File too large).  I can send via other xmpp apps.  This has been broken for a long time.  I was going to roll back to 4.x version that was the last time I know it worked.  I stopped using Monal because of the double text issues.   I did test this with my own server openfire and had the same results.

How can we fix this so it can send files correctly?  Also, I am not seeing the double text issues like I use to.  So that issue seems to be resolved now.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by ioscanner** [comment]
AstraChat on IOS work with no issues sending files both as photo or files using the same server and settings.  Desktop apps Pidgin works as well.  Not many iOS apps work.

**Comment by FriedrichAltheide** [comment]
How big is your file? Is the server using the "HTTP File Upload" module from ejabberd or something like "Prosody Filer"?

**Comment by ioscanner** [comment]
Doesn't matter the size.  I have tried a 100k png file.  I can then go to AstraChat on iOS and send the file just fine using the same xmpp account.  If it was on the server side AstraChat and Pidgin would have issues sending the file too.

**Comment by ioscanner** [comment]
I don't have access to the setting on the remote side.  When I tested to my server I had it set to 100MB.  But it does work with AstraChat and Pidgin.

**Comment by FriedrichAltheide** [comment]
Please try a different xmpp server like trashserver.net from Thomas Leister and check if uploads are working there.

**Comment by ioscanner** [comment]
I am using the VOIP providers SMS gateway to xmpp server.  It worked back in 4.x version.   Changing the server is not the issue.  If two other xmpp clients work then I don't think it is on the server side.  I prefer Monal, but since 4.x I have not been able to get the program to work either duplicate messages or can't send or receive images on various builds.  So we moved to AstraChat.  But their interface is pretty ugly and no font sizing.  So would be nice to get Monal working again,.  I miss it!

**Comment by tmolitor-stud-tu** [comment]
Can you provide a logfile of monal to thilo@eightysoft.de (mail)?

**Comment by FriedrichAltheide** [comment]
@ioscanner which HTTP Upload Plugin are you using in pidgin?

**Comment by ioscanner** [comment]
Sure I will send a log file. How do I generate the logfile?  I don't see an option to create the logfile.

I am not sure AstraChat is using.  
RFC-3920:Core
RFC-3921:Instant Messaging and Presence
XEP-0012 Last Activity
XEP-0016 Privact lists
XEP-0054 VCARD-temp
XEP-0085 Chat State Notifications
XEP-0153 vCard-Based Avatars
XEP-0172 User Nickname
XEP-0184 Message delivery receipts
XEP-0191 Blocking commands
XEP-0198 Stream Management
XEP-0199 XMPP Ping
XEP-0176: Jingle ICE-UDP
XEP-0136: Message Archiving
XEP-0045: Multi-User Chat
XEP-0363: HTTP File Upload

**Comment by FriedrichAltheide** [comment]
https://github.com/monal-im/Monal/wiki/Introduction-to-use-of-Monal-UDP-Logger#access-logfiles
Please try to upload a file before exporting the log file

**Comment by ioscanner** [comment]
I sent the log file.

**Comment by FriedrichAltheide** [comment]
Try to reduce the image quality:
>  Settings - Privacy Settings - Auto-Download Media Settings - Image Quality

**Comment by ioscanner** [comment]
I tried this already. Auto on, images size .33. Tried with taking a photo and using a current one. I have no issues receiving an image. I can not send. But on AstraChat or pidgin I can send and receive.

**Comment by ioscanner** [comment]
The picture I am trying to send is 277KB.

**Comment by FriedrichAltheide** [comment]
The server that you are using only allows an upload size of ~1MB.
Monal tries to reduce the quality of an image before sending. It seems that in your case the size increased due to the quality reduction so that the final upload size above your ~1 MB limit.
So, either try to reduce Image Quality in Monal even more, to see if it helps, or ask the xmpp provider to increase the http upload limit.

**Comment by ioscanner** [comment]
I sent a new log file. The file size is in only 277kb. I did this to confirm it was. Not a size issue. Now it throws an internal error.

**Comment by ioscanner** [comment]
Seems to be using uploads.auth.sms.gdn.

**Comment by ioscanner** [comment]
I was sending a file that was only 277kb.  I even tried 65kb.  Nothing works.  Did you look at the latest log I sent.

**Comment by FriedrichAltheide** [comment]
You reported to different issues:
1. "Upload Error: not-acceptable ( File too large)"
2. "Upload Error: internal-server-failure"

The first error occurs when you are uploading files that are larger than the server allows.
The second error occurs every time you request a upload slot with a file < ~1MB. The upload service "uploads.auth.sms.gdn" is the origin of this error. `<error type='wait'><internal-server-failure xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error>`. Please contact the server admin to resolve the internal server failure. There is nothing that we can do, as monal is requesting the upload slot as described in XEP-0363

**Comment by ioscanner** [comment]
Why does AstraChat and Pidgin work?  I have no issues with either of those.  I am not going to get the carrier to change their code just because one client app doesn't work.   I wonder if they are using another method to upload.

**Comment by FriedrichAltheide** [comment]
Closing this ticket. Monal http upload works as described in XEP-0363. AstraChat and Pidgin may use other XEPs or their own upload servers.
