### ISSUE TITLE
[Bug]: macOS & Kerio Connect with Let's Encrypt certificate reports error

### ISSUE THREAD

**Issue by alexanderharm** [monal-im/Monal#742]
### What Monal Release channel are you using?

AppStore

### macOS system version

11.6

### macOS Monal version

5.0.1

### Used XMPP server (domain)

private

### Which XMPP-Server software are you using?

other

### How many accounts are you using in Monal?

1

### What happened?

When trying to connect to an internal XMPP server (Kerio Connect) with Let's Encrypt certificates the client reports 

>The operation couldn't be completed. (kNWErrorDomainTLS error -9808 - bad certificate format)

However, OpenSSL reports just fine.

```bash
# /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.1.1l  24 Aug 2021

# /usr/local/opt/openssl/bin/openssl s_client -connect kerio.example.com:5223
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = kerio.example.com
verify return:1
---
Certificate chain
 0 s:CN = kerio.example.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

### Anything else?

Maybe related to <https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/>?

The macOS shipped LibreSSL version does indeed show described behaviour:

```
# openssl version
LibreSSL 2.8.3

# openssl s_client -connect kerio.example.com:5223
CONNECTED(00000005)
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
---
Certificate chain
 0 s:/CN=kerio.example.com
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
```

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
The DST Root CA X3 expiration should't be a problem.

Please verify that the "Verify return code" is zero for the following commands
`/usr/local/opt/openssl/bin/openssl s_client -xmpphost <your_virtual_host> -connect <xmpp_server>:5223`
`openssl s_client -xmpphost <your_virtual_host> -connect <xmpp_server>:5223`

Please check the c2s connection with the "IM Observatory" (https://xmpp.net) and report the result.
Did you set the optional xmpp-server in monal account settings or are you using SRV-Records for auto discovery.

**Comment by alexanderharm** [comment]
Thanks for your reply, for your information:

1. Error also shows on iOS
2. Error goes away if I trust the cert manually in Keychain Access
3. I did use the advanced account setup, setting the server manually
4. I can connect just fine using unencrypted 5222

Will now do the testing.

**Comment by licaon-kter** [comment]
It should not be a problem but it might be, eg. Eg. Siskin needed some updates too:
https://github.com/tigase/siskin-im/commit/03fb20aad831f9ed4f04bb35cbf9b6ffe03b7a05

So maybe try to regenerate the cert (if you did not do this after Sep 30 already), or even try to exclude DST entirely, eg. certbot has `--preferred-chain="ISRG Root X1"`

**Comment by alexanderharm** [comment]
The cert has been generated recently (8th October). Do I understand correctly that removing cross-signing will lead to problems with Android devices?

**Comment by alexanderharm** [comment]
Could not do the IM Observatory test because it tries to connect via 5222 and I cannot submit the hostname appending `:5223`. I openend now 5222 but can only run the test laster.

**Comment by alexanderharm** [comment]
With build-in LibreSSL

```
# s_client -xmpphost example.com -connect kerio.example.com:5223
CONNECTED(00000005)
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
---
Certificate chain
 0 s:/CN=kerio.example.com
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFLzCCBBegAwIBAgISBKgXK3RV5zZo913xfAT5/vLNMA0GCSqGSIb3DQEBCwUA
…
QAVkpCh4rREdBukLs+OUsDr/mohrwoHzfuE4hAVlGry6EJI=
-----END CERTIFICATE-----
subject=/CN=kerio.example.com
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4507 bytes and written 322 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6162C2E98B68C9D43E9D982621EA883F2E8810C1E5825A689413305D6273EC34
    Session-ID-ctx:
    Master-Key: D679F5F21CA0573FAC5103677F517DE7AA14D72EE5FC84C91B0DBFC39606EDAFDF6F5D9996730F28693BD123BF406520
    Start Time: 1633862375
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by FriedrichAltheide** [comment]
@alexanderharm Did you enable "direct TLS" when using port 5223? I just checked with one of my servers. I have the same chain and direct tls and starttls are working. 5222 isn't unencrypted, it is just using starttls. Please try port 5223 with direct tls (don't forget to save). close monal and kill it afterwards. Then open monal again.

**Comment by alexanderharm** [comment]
With Homebrew's OpenSSL

```
# /usr/local/opt/openssl/bin/openssl s_client  -xmpphost example.com -connect kerio.example.com:5223
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = kerio.example.com
verify return:1
---
Certificate chain
 0 s:CN = kerio.example.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFLzCCBBegAwIBAgISBKgXK3RV5zZo913xfAT5/vLNMA0GCSqGSIb3DQEBCwUA
…
QAVkpCh4rREdBukLs+OUsDr/mohrwoHzfuE4hAVlGry6EJI=
-----END CERTIFICATE-----
subject=CN = kerio.example.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4511 bytes and written 449 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6162C93B691D58A531D5910CE9CDC1D9E77564EA59A8D69CA302FF477498258C
    Session-ID-ctx:
    Master-Key: 45E682932429D229835A94997C0FFD720EDECA4C87A304C82A3CC39E566982BCC93882050C21D0D77C96CEEAB3665749
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1633863993
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

**Comment by alexanderharm** [comment]
@FriedrichAltheide: Yes I did. However, I indeed needed to kill it first before it started working! Is that exepected behaviour?

Kerio does not do STARTTLS afaik.

The SRV-entry is ordered but a different provider has to set them, I don't have access to the DNS.

Thanks for all the help, shall I close?

The solution is to quit Monal and then kill it via Activity Monitor or Terminal.

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu After changing the server port and saving the changes the new port isn't used. Even a manual reconnect doesn't change the used port.

@alexanderharm Check if you can add a xmpps-client SRV record for your virtual host. That way your users don't need to set the xmpp server, port and direct tls settings.

**Comment by alexanderharm** [comment]
That presence status in Monal is incorrect is probably an issue of Kerio and not of Monal, right?

**Comment by FriedrichAltheide** [comment]
Could you be a bit more precise what you understand of "presence status".

FYI: if you want push support , allow s2s communication to the monal app server (https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)
Even the Mac version uses push messages.

**Comment by alexanderharm** [comment]
By presence status I mean the indicator showing me current status of other users like online, offline, busy, away, dnd...

I will contact Kerio about the rest because there is hardly anything green of the server capabilities.

**Comment by alexanderharm** [comment]
I will close this ticket since the issue was solved by @FriedrichAltheide

**Comment by tmolitor-stud-tu** [comment]
> Kerio does not do STARTTLS afaik.

That cannot be true, Monal does not allow unencrypted xmpp. It even tries to use starttls if the server does not advertise it, conforming to [RFC 7590 section 3.1](https://tools.ietf.org/html/rfc7590#section-3.1).

--> monal would not connect/authenticate over the unencrypted connection.

**Comment by alexanderharm** [comment]
I have no doubt that Monal does this. I wasn't sure what Kerio does (it does STARTTLS as I found out later, too).

So the only issue left for me is presence. In Monal ALL users are online all the time. With Kerio client or Adium they show correctly.
