### ISSUE TITLE
RFC 7395: Websocket via XMPP (support?)

### ISSUE THREAD

**Issue by johnspurlock** [monal-im/Monal#743]
### 

- [X] I understood that this template is only for feature requests and not for bug reports

### 

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Does this app support connecting to xmpp servers that only support websockets?

I noticed https://tools.ietf.org/html/rfc7395 in your doap, but didn't see a way to configure them in account advanced settings.  Also didn't see anything ws related in a quick code search.

Thanks!
\- John

**Comment by tmolitor-stud-tu** [comment]
You are right, we don't support XMPP over Websocket, I updated the DOAP file to reflect that in commit https://github.com/monal-im/Monal/commit/428f4438938edfc767fd93ce0dba9484c8eedeb5
