### ISSUE TITLE
[Bug]: Missing string for translation

### ISSUE THREAD

**Issue by nautilusx** [monal-im/Monal#748]
### What Monal Release channel are you using?

AppStore

### iOS Monal version

5.0.1 (761)

### Used XMPP server (domain)

@domain.org

### How many accounts are you using in Monal?

1

### What happened?

@tmolitor-stud-tu: one string is missing for translation

"Own OMEMO Keys" (under settings > account > keys (OMEMO) > icon qr code > then above the qr code

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Hmmm...it's a normal string in the storyboard @FriedrichAltheide anything to do here?

**Comment by tmolitor-stud-tu** [comment]
It seems we can't make it translatable, it just won't show up.
I'll close this for now.
