### ISSUE TITLE
[Bug]: Monal alpha unexpected notifications showing, many crash reports

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#752]
### What Monal Release channel are you using?

Alpha

### macOS system version

11.6.2

### macOS Monal version

Alpha 5.1.0 (Dec 15 2021: 19:56:45 UTC)

### Used XMPP server (domain)

disroot.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

trunk

### How many accounts are you using in Monal?

1

### What happened?

There is a problem where Monal alpha shows notifications while there are no new messages incoming. Mucs set to mute or mention only and no other new messages arriving.

Looking at console app > crash reports there are quite a few crash reports for `NotificaionService` (sic!).
<img width="1235" alt="ugh" src="https://user-images.githubusercontent.com/5708172/146544393-39235e0b-fad1-473d-91df-baa53d4eb0d1.png">

They all look like this: https://bin.disroot.org/?154d44e5dab3f9fb#6CudCbS4TfN8cdvScSBpaqDiotg3rYQ7CSCyqa3HeSmp

The interesting part is:

```
Process:               NotificaionService [23948]
Path:                  /private/var/folders/*/Monal.alpha.app/Contents/PlugIns/NotificaionService.appex/Contents/MacOS/NotificaionService
Identifier:            NotificaionService
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NotificaionService [23948]
```

Could it be, that the typo in the Name confuses macOS and it goes bananas due to that?

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please check the newest build "Alpha 5.1.0 (Dec 16 2021: 21:05:27 UTC)"

**Comment by foss-** [comment]
Seems fixed - thanks a lot.

**Comment by foss-** [comment]
Followup: With yesterdays alpha build the crashes were gone but the random "New Message" notifications remained. Certainly a related but separate issue. Thilo asked to test a more recent alpha and running Alpha 5.1.0 (Dec 17 2021: 17:43:58 UTC) on macOS 11.6.2 and the issue with unrelated "New Message" notifications seems gone (so far).
