### ISSUE TITLE
[Bug]: allow to send attachments by pressing enter

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#754]
### What Monal Release channel are you using?

Alpha

### macOS system version

11.6.2

### macOS Monal version

Alpha 5.1.0 (Dec 20 2021: 18:05:09 UTC)

### Used XMPP server (domain)

disroot.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

trunk

### How many accounts are you using in Monal?

1

### What happened?

Unable to send attachment by pressing `Enter` key.

**Reproduce**

1. drag image into a 1:1 chat
2. type `Test` info message box
3. Press `Enter` key

**Expected**

Image should be sent along with image description (of if that is - not yet? - supported, send image and right after the image the text as separate message.

**Currently**

Message is sent but image remains in preview / compose view. When only adding an image and pressing `Enter` nothing happens, while the image should be sent.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by foss-** [comment]
Thanks for working on this @angelina-p09 

Confirming that pressing enter does send attachments as expected now (tested on macOS 13.3.1).

**Currently**

One minor fine-tuning could be done: When dragging an image (or other attachment into chat, since the compose box does not have focus, it is not possible to either type a message or to directly press enter to send.
This is with https://github.com/monal-im/Monal/pull/923

**Expected**

After dragging an attachment into chat, the cursor should be active in the composer box so that users can send with a press of enter or add a message to their attachment if they want.

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by guodong323** [comment]
Hi, I want to try to solve this question

**Comment by FriedrichAltheide** [comment]
After an out-of-band discussion with @tmolitor-stud-tu, we decided to close this issue as a won't fix (at least for now). Reason: When adding a file you are most likely already using the mouse / trackpad. Hence, it does not really make a difference to click on send.
