### ISSUE TITLE
[Bug]: Pinned chats UI: find better solution

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#755]
### What Monal Release channel are you using?

Alpha

### macOS system version

11.6.2

### macOS Monal version

Alpha 5.1.0 (Dec 20 2021: 18:05:09 UTC)

### Used XMPP server (domain)

disroot.org

### How many accounts are you using in Monal?

1

### What happened?

**Currently**

UI for pinned chats uses a green which looks very alien.
<img width="307" alt="pinned chat UI" src="https://user-images.githubusercontent.com/5708172/146911788-53c6b53e-af90-4e6f-a4f6-c8401146e976.png">

**Expected**

There are various options to address this. I don't think that using a color to indicate pinned chats is a good solution as it will likely always look wrong. Would it be possible to just make the separation line between pinned and non-pinned chats a bit thicker as indicator? Whichever solution, this has to be seen in app to say what works.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by Echolon** [comment]
Still I like to populate the Monal color scheme more

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by vednp** [comment]
Can I work on it??

**Comment by tmolitor-stud-tu** [comment]
sorry, to my knowledge, @zainashraf1562 is already working on this

**Comment by tmolitor-stud-tu** [comment]
this is solved and released now, closing this issue
