### ISSUE TITLE
[Bug]: Highlight selected chat in left chat list panel

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#756]
### What Monal Release channel are you using?

Alpha

### macOS system version

11.6.2

### macOS Monal version

Alpha 5.1.0 (Dec 20 2021: 18:05:09 UTC)

### Used XMPP server (domain)

disroot.org

### How many accounts are you using in Monal?

1

### What happened?

**Currently**

The selected chat is not highlighted in the left chat list panel.

**Expected**

Selected chat should be highlighted.

This is how signal solves this. Lower chat is highlighted to indicate which chat is currently active in main view:
<img width="130" alt="signal" src="https://user-images.githubusercontent.com/5708172/146911513-d2deb08f-6523-4899-979a-d657c232fa8d.png">

Keep in mind to also address this for pinned chats. See also: https://github.com/monal-im/Monal/issues/755

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by licaon-kter** [comment]
You can get server software/version from https://compliance.conversations.im

**Comment by foss-** [comment]
@licaon-kter not sure how that would be relevant to this feature request / UI change.

**Comment by licaon-kter** [comment]
Just a FYI :)

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by zainashraf1562** [comment]
Gsoc Applicant: I would like to work on this issue.

**Comment by tmolitor-stud-tu** [comment]
@zainashraf1562 from the original issue:

> Keep in mind to also address this for pinned chats.
