### ISSUE TITLE
[Bug]: Crash on opening app. Winnie the Pooh picture with a message along the lines of "Oops nothing here"

### ISSUE THREAD

**Issue by gitbq** [monal-im/Monal#762]
### What Monal Release channel are you using?

AppStore

### iOS system version

14.7

### iOS Monal version

5.0.1

### Used XMPP server (domain)

hot-chilli.net

### How many accounts are you using in Monal?

1

### What happened?

Opening the app, randomly this message appears (the Winnie the Pooh) picture and it is unable to get past this message screen. 
The only way to proceed is to reinstall, but then all the conversations are lost etc.

This has happened on devices originating from various Asian countries.

hot-chilli.net
chinwag.im
these domains and others have occasionally had the same issues.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please give the latest beta release a try.
If the error persists in the beta, export the debug log (https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions#how-to-export-a-log-file).

**Comment by Echolon** [comment]
Hi @gitbq,

have you considered to install the testflight?
