### ISSUE TITLE
[Bug]: Cannot send messages using external keyboard on iOS

### ISSUE THREAD

**Issue by JJ-OpusVL** [monal-im/Monal#763]
### What Monal Release channel are you using?

Beta

### iOS system version

15.1

### iOS Monal version

5.1.0 (764)

### Used XMPP server (domain)

opusvl.com

### How many accounts are you using in Monal?

1

### What happened?

On iOS (iPad) with an external keyboard connected, pressing Enter (with no modifier keys) adds a newline to the message.

Unfortunately, the iOS keyboard / microphone control overlaps Monal's send message button meaning that the only way to send a message is to show the soft keyboard and press send on the touchscreen.

![IMG_B7693C02C4BD-1](https://user-images.githubusercontent.com/7986920/149493265-33bc1f60-05d3-4fd7-9a6c-5b82ba2b06dd.jpeg)

Expected behaviour:
- Pressing Enter without a modifier sends the message
- Pressing Option + Enter adds a newline

Alternatively, could a shortcut be added to send the message?

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by Echolon** [comment]
Thank you for reporting!
