### ISSUE TITLE
[Bug]: only show badge for unread messages that qualify for notification

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#767]
### What Monal Release channel are you using?

Alpha

### macOS system version

12.2

### macOS Monal version

Alpha 5.1.0 (Feb  3 2022: 06:50:56 UTC)

### Used XMPP server (domain)

disroot.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

trunk

### How many accounts are you using in Monal?

1

### What happened?

Monal app icon badge number shows total of unread count. It does not take into account the muc setting for notifications.

Expected
- muc set to mention only: only messages with mentions added to badge counter
- muc set to silent: no messages added to badge counter for specific muc

Rational behind this request is to reduce noise, which is the entire point of changing the notification settings. The idea is to only add relevant 1:1 or mentions to unread badge counter since otherwise the counter is rather useless and can not serve to inform users about relevant message that may require action on their part.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
muted mucs or 1:1 chats are already not counted, mention-only counting is a bit more difficult, though...
