### ISSUE TITLE
[Bug]: Cannot send OMEMO encrypted message to MUC

### ISSUE THREAD

**Issue by jtmaston** [monal-im/Monal#769]
### What Monal Release channel are you using?

Beta

### iOS system version

15.2.1

### iOS Monal version

5.1.0(766)

### macOS system version

-

### macOS Monal version

-

### Used XMPP server (domain)

For privacy reasons, rather not post here

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

Trunk

### How many accounts are you using in Monal?

1

### What happened?

I can't enable OMEMO on MUC... I can however read OMEMO messages sent by other users and can read even messages I sent from other clients ( them encrypted too ).

### Anything else?
<kbd><img src="https://user-images.githubusercontent.com/43366646/152603293-4c7c5005-ec58-4589-8a53-039946d2143c.png" width="300"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/43366646/152603307-7fd747de-25e0-422d-9ba9-7efbc6455dc4.jpeg" width="300"></kbd>

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
OMEMO for MUC isn't fully implemented yet
