### ISSUE TITLE
[Bug]: ios13push.monal.im is presenting an invalid TLS certificate

### ISSUE THREAD

**Issue by ghost** [monal-im/Monal#806]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.4.1

### iOS Monal version

5.1.0

### Used XMPP server (domain)

w-a-s-t-e.de

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.0-1~buster1

### How many accounts are you using in Monal?

1

### What happened?

ios13push.monal.im is presenting an invalid TLS certificate which prevents push notifications from being delivered to Monal app on iOS:

excerpt from /var/log/prosody/prosody.log:

May 07 13:47:22 s2sout56293b5622f0      info    Stream encrypted (TLSv1.3 with TLS_AES_128_GCM_SHA256)
May 07 13:47:22 s2sout56293b5622f0      warn    Forbidding insecure connection to/from ios13push.monal.im because its certificate is not valid for this name
May 07 13:47:22 s2sout56293b5622f0      info    Outgoing s2s stream w-a-s-t-e.de->ios13push.monal.im closed: Your server's certificate is not valid for this name
May 07 13:47:22 s2sout56293b5622f0      info    Sending error replies for 1 queued stanzas because of failed outgoing connection to ios13push.monal.im

openssl s_client -servername ios13push.monal.im -connect ios13push.monal.im:5269 -starttls xmpp:

CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = push.monal.im
verify return:1
---
Certificate chain
 0 s:CN = push.monal.im
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---

I'd say, the certificate's CN does not match the service url used for the s2s connection.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Seems to be a prosody related bug, where the first domain of a multi domain cert was used. We removed the cert containing multiple domains (push.monal.im, ios13push.monal.im, ...) and replaced it with multiple certs with only a single domain. We will soon move to our new push system replacing prosody with ejabberd.

**Comment by ghost** [comment]
Working again. Thanks a lot!
