### ISSUE TITLE
[Bug]: Monal app freeze

### ISSUE THREAD

**Issue by surentharp** [monal-im/Monal#832]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.5

### iOS Monal version

5.1.1

### Used XMPP server (domain)

mail.paradisetoys.biz

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

21.12

### How many accounts are you using in Monal?

1

### What happened?

I am using monal app in iPhone 13. The monal app in my phone freezes (not responding) at certain times. I also checked by closing and reopening the app, but it is not responding.

So, I must uninstall and install it again for the app to work properly. Since this is happening frequently, I am reinstalling the app to overcome this issue.

Thank you for providing us this app. Hope this information will be helpful in solving this issue.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by Echolon** [comment]
@surentharp are you able to reproduce this?

**Comment by FriedrichAltheide** [comment]
we already reproduced it...
@surentharp By the way check if your server admin can upgrade ejabberd to the latest version for a better push experience :)

**Comment by surentharp** [comment]
@Echolon Currently I am testing by using the latest beta version. The issue didn't occur till now.

I shall test it and update you once if I can be able to reproduce this issue.

**Comment by tmolitor-stud-tu** [comment]
If it happens again, please extract the logfile and send it via mail to info@monal-im.org or upload it here: [Next cloud](https://dyn.eightysoft.de/nextcloud/index.php/s/Bm9jcga4xPJjz9p)

Please include a note in the mail telling us the timestamp when the freeze occurred.

**Comment by surentharp** [comment]
@tmolitor-stud-tu Thank you for the support. I will do as per your guidelines.

**Comment by tmolitor-stud-tu** [comment]
Closed for now, I'll reopen it once you send us a logfile.
