### ISSUE TITLE
[Bug]: No Push 5.2.0

### ISSUE THREAD

**Issue by madfoss** [monal-im/Monal#839]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.5

### iOS Monal version

5.2.0

### Used XMPP server (domain)

privat

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.1

### How many accounts are you using in Monal?

1

### What happened?

No push notification under IOS since version 5.2.0, regardless of whether Europe / US.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by licaon-kter** [comment]
From the support channel:
> Heads up: Monal 5.1.1 did contain a bug that made notifications not work as intended for new installs (upgrades to 5.1.1 from earlier versions continued to work fine).
> The new 5.2.0 release fixes that bug, but unfortunately you have to either turn on Notifications manually in iOS settings (see screenshot below) or uninstall and reinstall Monal to make notifications work again.
> We are sorry for the inconvenience! 
![monalpush](https://user-images.githubusercontent.com/2282799/177136657-203b5fd5-f8fa-4eec-ac26-c1f4a3e32158.jpeg)

**Comment by madfoss** [comment]
Solved
Sorry, i have restricted xmpp domains, the push address has been changed from ios13push.monal.im to eu.prod.push.monal-im.org.

After the change, Push works again.

**Comment by licaon-kter** [comment]
@madfoss https://monal-im.org/privacy/#push-servers

/close this if fixed

**Comment by FriedrichAltheide** [comment]
@madfoss for the future: please whitelist all subdomains of "push.monal-im.org"
