### ISSUE TITLE
[Bug]: Profile popup has wrong size on iPad

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#840]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.5

### iOS Monal version

5.2.0

### Used XMPP server (domain)

custom

### How many accounts are you using in Monal?

1

### What happened?

![IMG_1DD8650447D8-1](https://user-images.githubusercontent.com/2963008/178068601-a6209ba2-f4b8-4100-b225-52f91981eda0.jpeg)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by janst97** [comment]
Fixed with ce56ade, I'm keeping this ticket open until the changes are merged into the develop branch.
