### ISSUE TITLE
[Bug]: Monal is sending old copied links whenever sending any attachement to anyone

### ISSUE THREAD

**Issue by hollymrklm** [monal-im/Monal#841]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.6

### iOS Monal version

5.2.0

### Used XMPP server (domain)

custom

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

25.05

### How many accounts are you using in Monal?

1

### What happened?

Hello, everyone, I found strange behavior when sending attachments.

Few weeks ago client A (running Monal) has sent two messages containing a link to client B (blabber / dino). One of those messages was _presumably_ copied from another messenger app using copy + paste text (not share), the other was a link to Nextcloud folder gained directly from NC app...

Since that every time client A sends _ANY_ picture (tested on pictures only) to _ANY_ client (client B or anyone else), the picture is delivered and client B receives those two messages at the same time. (For each picture both messages.)

This happens only when pictures are shared from e.g. gallery app. However when chosen by Monal directly from chat view, all works as expected...

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
That's a known bug already fixed in alpha builds: https://github.com/monal-im/Monal/commit/d316d011387016002c601e566e67837c6d280706

Unfortunately the app migration from Anu's Apple account to mine takes much longer than anticipated which delays a new release containing this fix (among other fixes).
Currently we are planning to do a release this week, but given that we constantly discover new problems we need to fix first, I can not guarantee that timeframe.

**Comment by hollymrklm** [comment]
Hello, good news then. Posted it because couldn't find something similar in bugs. Will take better look next time. Thanks and looking forward new release!

2. 8. 2022 15:55:50 Thilo Molitor ***@***.***>:
