### ISSUE TITLE
iOS Public Beta Unavailable

### ISSUE THREAD

**Issue by Reinachan** [monal-im/Monal#842]
The public beta link on the [website](https://monal.im/) and in [this issue](https://github.com/monal-im/Monal/issues/363) no longer work.

![Text in image says: Beta not found. There is a problem with the public link URL. Contact the developer for more information](https://user-images.githubusercontent.com/16106839/182577252-e54d9e68-075f-498e-b122-3835330260c6.jpeg)

**Comment by FriedrichAltheide** [comment]
We are still migrating the app from Anu's Apple account to thilo.
Unfortunately the transfer takes much longer than anticipated delaying a new release and therefore new TestFlight links.
We are currently planning to do a release this week, but given that we constantly discover new problems we need to fix first, we can not guarantee that timeframe.

**Comment by tmolitor-stud-tu** [comment]
We just published our first beta in the migrated app and generated new enrollment links: https://github.com/monal-im/Monal#releases
