### ISSUE TITLE
[Bug]: Sharing to Monal Contacts

### ISSUE THREAD

**Issue by izanp** [monal-im/Monal#844]
### What Monal Release channel are you using?

Beta

### iOS system version

15.5

### iOS Monal version

5.3.0 799

### Used XMPP server (domain)

conversations.im

### How many accounts are you using in Monal?

>= 6

### What happened?

When sharing a file(photo) from Photos, choosing Monal and then the contact you wish to send to, the contact list is not showing all your contacts but only the recent sent to contacts.A problem happened!

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Fixed in this commit: https://github.com/monal-im/Monal/commit/ac865e3a588878e34207dcbd61a8ccb438bb71ff

This fix will be included in the next beta.
