### ISSUE TITLE
[Bug]: (i) Information on contact list crash app

### ISSUE THREAD

**Issue by izanp** [monal-im/Monal#845]
### What Monal Release channel are you using?

Beta

### iOS system version

15.5

### iOS Monal version

5.3.0 799

### Used XMPP server (domain)

conversations.im

### How many accounts are you using in Monal?

>= 6

### What happened?

When navigating to Contacts and pressing (i), the app crash(this is on the current testflight version)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Thanks for your report, I think I fixed your crash here: https://github.com/monal-im/Monal/commit/25ef78bf04222809cb517c332111e700bb7357db

The next beta will include your fix, please check if the bug persists in that beta and reopen this issue, if so.
