### ISSUE TITLE
[Bug]: GIFs not animating on iOS

### ISSUE THREAD

**Issue by frznGT** [monal-im/Monal#846]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.6

### iOS Monal version

5.3.0

### macOS system version

N/A

### macOS Monal version

N/A

### Used XMPP server (domain)

private

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

22.05

### How many accounts are you using in Monal?

>= 6

### What happened?

On iOS, the new gif animation functionality does not work when a gif is added from the image library (photos). It does work when a gif is attached as a regular file.

After a cursory look, it looks like this may be the code responsible, which converts every image uploaded from the UI to jpg:

https://github.com/monal-im/Monal/blob/206ed28470fd63e070258d1eedd94e4b15692651/Monal/Classes/MLFiletransfer.m#L545-L570

Thank You!

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
You are right, but the problem begins even further: Apple's UIImage can't handle animated GIFs, so passing that to the MLFiletransfer implementation is wrong in the first place.

I'll push a fix shortly.
