### ISSUE TITLE
[Bug]: Monal in a certain case doesn't clear the red dot badge nor send the XEP-0333 read notification

### ISSUE THREAD

**Issue by unriccio** [monal-im/Monal#847]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.6.1

### iOS Monal version

5.3.1

### Used XMPP server (domain)

magicbroccoli.de

### How many accounts are you using in Monal?

1

### What happened?

Under certain conditions the red dot/badge over Monal icon doesn't disappear when reading received messages (or even after sending a reply!) - contextually Monal doesn't send the XEP-0333 read notifications.

How to reproduce:
- two devices (I tried with Android/Conversations and iPhone/Monal)
- start chatting between the two devices
- on Monal side: "minimize" (=swipe up without closing) the app, while the chat is still open
- on Conversation side: send a message
- Monal receives it and correctly sends the XEP-0184 delivery notification
- do not tap on the iOS notification
- Monal icon correctly shows the (1) badge/red dot
- tap on the icon, Monal reopens the chat
- scroll at the bottom of the chat - Monal doesn't remove the badge nor send the XEP-0333 read notifications
- even send a reply, and then swipe up Monal again - the red dot is still there

I did a few other tests:
- this behaviour doesn't happen if Monal is closed and not minimized (= swipe up and then swipe away) - probably because upon reopening you pass through splashscreen -> rooster -> chat
- the badge is cleared and the XEP-0333 notifications are sent if you go back from the chat to the rooster and then enter the chat again - this seems what was reported some time ago in this comment https://github.com/monal-im/Monal/issues/411#issuecomment-760961054 (and, indeed, a friend told me the same a while ago as well... but I didn't have the time to test extensively/reproduce systematically until recently)

Thanks for your precious work :)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Thanks for your detailed description!
