### ISSUE TITLE
[Bug]: upgrade message shown but no upgrade available

### ISSUE THREAD

**Issue by mirabilos** [monal-im/Monal#848]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.7

### iOS Monal version

5.3.1 (805)

### macOS system version

none

### macOS Monal version

none

### Used XMPP server (domain)

caas.mirbsd.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.11.9-2+deb11u2

### How many accounts are you using in Monal?

1

### What happened?

I got a notification I **have to** upgrade Monal or it will “stop working” within weeks.

1. Why? There’s no reason it should.
2. 2. The Äpp Store doesn’t show me any update to install.

### Anything else?

XEP-0352 is deliberately not enabled. I had massive problems with message delivery when it was enabled.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
I'm sorry, that was my fault.
I wanted to send an upgrade notice to all old Monal installations, but got the filter expression wrong.
By the time I noticed my error 10 - 20% of valid Monal installations already got the message.

The wrong message was `Your Monal version is very old and will stop working in a few weeks, please upgrade!`

After fixing the filter, I sent out a new message with a slightly different text: `Your Monal version is very old and will stop working in a few weeks, please upgrade to version 5.3.1 at least!`

**If you received the second text, your Monal version is seriously outdated and you should upgrade immediately!**

_If you received the first text, just ignore it._
