### ISSUE TITLE
[Feature]: Quote message

### ISSUE THREAD

**Issue by francescoragazzi** [monal-im/Monal#869]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

It would be great if one would be able to quote messages by swiping right on the message (iOS) or via a little dropdown menu (on macOS). Thanks for the great work!

**Comment by tmolitor-stud-tu** [comment]
Already implemented, just swipe left :)

**Comment by francescoragazzi** [comment]
aaaah ) sorry, I was swiping in the wrong direction : )
