### ISSUE TITLE
[Bug]: Dark Mode not working: https://monal-im.org

### ISSUE THREAD

**Issue by tran-h-trung** [monal-im/Monal#879]
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

trung.fun

### How many accounts are you using in Monal?

>= 6

### What happened?

I went to the official website of Monal and my eyes !!!! Oh my eyes !!!!!!!!!

### Anything else?

…I like cheese.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
fixed in staging
