### ISSUE TITLE
[Feature]: Invite user to use XMPP/Monal

### ISSUE THREAD

**Issue by tran-h-trung** [monal-im/Monal#891]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Dear Monal.

It would be nice for Apple users to be able to spread XMPP too.

<3
Trung

**Comment by licaon-kter** [comment]
Can you explain how you want this to work exactly?

Invite how?

**Comment by tran-h-trung** [comment]
Of course I can.

There is a blog post on Prosŏdy about invite:
»    https://blog.prosody.im/great-invitations/

AFAIK, Monal can consume invite but yet create them.
(I don't have an iphone so I have no idea if it can consume the URL
from my server. Hint: Snikket-android can.) 



So my Feature Request is for creating the invite. The flow is:

0. Client requests an invite token.
1. Server returns the token along with the URL to an invites page.

The URL is controlled entirely on the server side. (For example, currently
in Prosŏdy, `mod_invites_register_web` is used to generate invite token
and `mod_http` is used to customize the URL.)

Monal can then encode this URL to QR for scanning on mobile devices.

On the client side, there are 2 kind of requests. For *regular* account:
»   `urn:xmpp:invite#invite`

and an extra option for *admin* account: 
»   `urn:xmpp:invite#create-account`

The seperation between regular and admin is for admin not having 
to adding all of his|her invitee to his|her roster. (without this option,
admin's roster might turns into a mess.)

Both commands are already implemented in Profanity.

This feature is also already in Conversations under:
»   `Invite to Conversations`

However, C' doesn't have an option for `#create-account` atm (i think).

If Monal can't recognize admin vs regular account yet, I would 
suggest Monal to do the same as C' and upgrade later. (But obviously
Monal can lead the race.)

**Comment by tmolitor-stud-tu** [comment]
Already implemented, will be part of Monal 6.0: https://github.com/monal-im/Monal/commit/e0b6c9b11e38ab9e79f74cc7c71c1b22942571f1
