### ISSUE TITLE
[Bug]: macOS only: no way to select background image when not using photos app

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#895]
### What Monal Release channel are you using?

Alpha

### macOS system version

13.1

### macOS Monal version

Alpha 6.0 (Dec 28 2022: 20:40:30 UTC)

### Used XMPP server (domain)

disroot.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

trunk

### How many accounts are you using in Monal?

2

### What happened?

open `Settings > Backgrounds > Select background image`.

**Currently**

No Photos and no option to select an image when user is not using photos app on macOS (or zero photos exist in photos app).

**Expected**

Open images folder ffrom macOS.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Images can be selected from the photos.app on macOS

**Comment by foss-** [comment]
Not sure I understand. I am not using photos app and also not seeing any option to select that app. If the photos app is a requirement, maybe that should be stated. It would be nice to fall back on a file picker when photos app is not used.
![1](https://user-images.githubusercontent.com/5708172/209930689-4dac7c95-e7e3-425f-83c9-dcc23e0a05a2.png)
