### ISSUE TITLE
[Bug]: OMEMO does not work between Movim and Monal

### ISSUE THREAD

**Issue by rstefko** [monal-im/Monal#899]
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

@

### Which XMPP-Server software are you using?

Prosody

### How many accounts are you using in Monal?

1

### What happened?

Not sure where the problem is. OMEMO works fine with between Monal and Conversations or Gajim. Also OMEMO works between Movim and Conversations or Gajim, but not between Movim and Monal.

I also opened issue on Movim side: https://github.com/movim/movim/issues/1143

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Missing Monal version, prosody version, prosody community modules version, domain. More details would be much appreciated. e.g. error messages. Does the monal user trust your fingerprint / other way around? is Monal showing a warning for you OMEMO fingerprint? Are you both in each others roster? Same domain different domains? Please send a picture from the supported XEPs:  Monal -> Settings -> select account -> press (i) (4-th entry)

**Comment by rstefko** [comment]
Thank you for the reply.

Monal version is 5.4.4. Prosody version 0.12.2. prosody-modules rev: ca7feb293d55.
I don't see any errors in Prosody log.

I have tested with my account using Movim, Monal and Conversations and second account using Monal and Conversations. Both using the same client versions and the same server.

On the start I have checked all devices trust each other.

### Send OMEMO message from Movim to the second account.
My Account:
Movim OK (send the message)
Conversation OK (can read message)
Monal OK (can read message)

Second Account:
Monal OK
COnversations OK

### Replied from Second account using Conversations
My Account:
Movim OK
Conversation OK
Monal OK

Second Account:
Monal OK
COnversations OK (send the message)

### Replied from Second account using Monal
My Account:
Movim Received encrypted message (unable to read)
Conversation OK
Monal OK

Second Account:
Monal OK
COnversations OK (send the message)

From this point Movim does not trust the Monal fingerprint and I cant check it in the settings.

**Comment by rstefko** [comment]
XEPs are all green, just SASL is not available.

**Comment by FriedrichAltheide** [comment]
Please make a screenshot of the fingerprints (local account and from the remote contact) on both accounts with monal and conversations

**Comment by rstefko** [comment]
What do you expect to see there? There are no "warnings" on fingerprints in Monal. And yes all fingerprints are there on all devices. Otherwise in the first case (Send OMEMO message from Movim to the second account) the OMEMO message would not be readable on other devices, right?

**Comment by FriedrichAltheide** [comment]
Closing stale issue due to missing information

**Comment by Neustradamus** [comment]
@rstefko: Any news on it?

**Comment by rstefko** [comment]
No. I switched from Movim to Converse.js - it works great.

**Comment by Neustradamus** [comment]
@rstefko: What is the situation with Movim "one year" after?

**Comment by rstefko** [comment]
I can't test it anymore. I stopped using it a year ago :(
