### ISSUE TITLE
[Feature]: iOS Password manager recogintion

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#915]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Today a user installed Monal and registered a new account. While entering the password the iPhone user expected to use the iOS password manager somehow integrated in iOS. I would like to recommend to support this as part of

- user experience
- possibly corporate function one day

Related:
- [Password AutoFill save password SwiftUI](https://stackoverflow.com/questions/61229358/password-autofill-save-password-swiftui/72921193#72921193)
- [How to find saved passwords and passkeys on your iPhone](https://support.apple.com/en-us/HT211146)

**Comment by FriedrichAltheide** [comment]
While I understand that in some cases this might improve the user experience, I prefer to force users to think about how they store their passwords securely.

**Comment by Kobaxidze256** [comment]
It's impossible to use iOS without trusting Apple to not take advantage of their hold over your phone. Maybe asking forethought out of Apple product owners is going too far?
