### ISSUE TITLE
[Bug]: Auto-scroll button in wrong position when switching chats

### ISSUE THREAD

**Issue by angelina-p09** [monal-im/Monal#921]
### What Monal Release channel are you using?

Beta

### iOS system version

16.2

### iOS Monal version

6.0.0

### Used XMPP server (domain)

yax.im

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

When switching between chats, the auto-scroll button changes position making the user unable to click it. 

<img src=https://user-images.githubusercontent.com/124469658/233558250-1448a6cc-9327-4e2a-822d-1117c6133802.png width= 40% height=40%>

<img src= https://user-images.githubusercontent.com/124469658/233558253-c4a824ad-9656-46d7-977a-613f866c02ee.png width= 40% height=40%>

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
@angelina-p09 Could you try to fix that?

**Comment by matthewrfennell** [comment]
I am interested in contributing to Monal, and saw the help wanted tag.
I had a quick look, and think it can be solved with a small change using constraints.
Should I raise a PR, or leave it for the SwiftUI rewrite?

**Comment by tmolitor-stud-tu** [comment]
Hi @matthewrfennell !

Sounds great! Our swiftui rewrite is at least 6-12 month away, so fixing things before would be great :)

Do you plan to contribute more or just this single fix?

**Comment by tmolitor-stud-tu** [comment]
Sidenote: strictly speaking, the help wanted tag should be on **every** issue. So feel free to also take a look at the other issues :)

**Comment by matthewrfennell** [comment]
> Sounds great! Our swiftui rewrite is at least 6-12 month away, so fixing things before would be great :)

Ok great, thank you!
Just FYI - I need to get a one-time approval from work, so will be a couple of weeks before I raise the first PR.

> Do you plan to contribute more or just this single fix?

I'd like to contribute more if possible.
I really like XMPP and convinced many of my contacts to use Monal. So I want to help with anything that will make the app even better :)

> Sidenote: strictly speaking, the help wanted tag should be on **every** issue. So feel free to also take a look at the other issues :)

Sounds good, I'll take a look!
I have almost no experience with iOS, which is why I started small, but I'm up to work on any part of the project.
Let me know if there's anything that would be really helpful.
