### ISSUE TITLE
[Bug]: OMEMO new key on Monal start-up

### ISSUE THREAD

**Issue by grrgui** [monal-im/Monal#924]
### What Monal Release channel are you using?

AppStore

### macOS system version

Ventura 13.3.1

### macOS Monal version

5.4.4 (845)

### Used XMPP server (domain)

chapril.org

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Here is the scenario: A friend uses Monal on MacOS. I use Blabber on Android.
We accept each other's OMEMO keys and manage to exchange encrypted messages.
When he shuts down and restarts his Mac, sometimes he can't read my new messages anymore. Indeed, in this case, I notice that a new key is associated to his device (it is not systematic...). Why is the key renewed instead of keeping the same one? 

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [ ] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [ ] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please check if the user installed Monal via App Store **and** e.g. via brew (or just downloaded a recent or old version manually).

**Comment by grrgui** [comment]
It seems it was a manual donwload (version 5.4.4 (845))
Thank you for your support! ;)

**Comment by FriedrichAltheide** [comment]
Only use one version. App Store **or** manual/brew install.

**Comment by grrgui** [comment]
It is a manual install.

**Comment by FriedrichAltheide** [comment]
1. is it a real Mac or a hackintosh?
2. Are you sure about the monal version number?
3. Are multiple version of monal (different versions in different folders or with different names) installed?

**Comment by grrgui** [comment]
1. It is a real Mac
2. I've just checked the version, it is 5.4.4 (845)
3. only one version is installed on the Mac

**Comment by FriedrichAltheide** [comment]
Please export a log file (https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging) right after the next key rotation. Send the log file to info@monal-im.org.

**Comment by tmolitor-stud-tu** [comment]
can this be closed?

**Comment by grrgui** [comment]
Problem not seen recently, I close this issue.

**Comment by lillian-b** [comment]
I got this issue as well just now.
edit: I installed through Brew and NOT app store

**Comment by grrgui** [comment]
So am I, I still have this issue, almost every day I have to accept his new key on my device to be able to communicate with my friend.

**Comment by FriedrichAltheide** [comment]
Please ensure that you only installed one version of monal (one Monal.app) that is either installed via brew **OR** via the appstore. OMEMO keys are only replaced with a new pair if the vendor specific UUID of the app installation has changed. This is the case when a user switches between release types. Or when monal is uninstalled and later reinstalled.
Our current release types are:
- App Store stable
- App Store beta (TestFlight)
- Brew stable / Brew beta

**Comment by lillian-b** [comment]
I **only** ever installed Monal through Brew stable.

I restarted my laptop and the key is reset again. I am seeing this error in settings (the first, non-broken device is my mobile phone):

<img width="493" alt="image" src="https://github.com/monal-im/Monal/assets/146143737/b4323cde-0dc7-4d5c-b599-42fa5f1e59bc">

**Comment by FriedrichAltheide** [comment]
The list only contains two entries. One for your mobile phone and one for your laptop. You stated that a new omemo key was created after the reboot. Hence I would assume that the list of omemo fingerprints of your accounts contains three elements. But there are only two. So please explain in detail how to reproduce and what exactly you are experiencing, please also check if the same error can be reproduced on a server with a more modern ejabberd version.

The only thing that I see is that the session of the own device is broken but in theory that should never be used.

**Comment by grrgui** [comment]
Hi there,
On my side, I have a lot of OMENO keys related to the account of my friend using Monal on her laptop.
![Screenshot_20231202](https://github.com/monal-im/Monal/assets/28450645/3e64e598-583e-4dda-b6c2-84e487c90db5)
To have a clear picture, this morning, she removed Monal and reinstalled it from the App Store.
I was surprised to see that after reinstall the session was already there (no password needed for exemple). Is there a way to force a new session and kill the old one?

For information, she has one account used on two devices : a Mac Book (Monal) and an Android Phone (Blabber, a fork of Conversations).

**Comment by FriedrichAltheide** [comment]
@grrgui do you have any kind of proof that all these keys are in fact from monal on macOS? These could also be from blabber or from other previously used xmpp clients (even ones from years ago).

Why do you want a new session? What do you mean by killing an old session? What exactly is the problem that you are facing. Right now I do not see a relation to this ticket.

**Comment by FriedrichAltheide** [comment]
@lillian-b We have still not received any information on how to reproduce this, a corresponding log file, or whether it is reproducible with a newer version of ejabberd. Hence, I am tempted to close this ticket soon.

**Comment by lillian-b** [comment]
@FriedrichAltheide, I forgot about this ticket, sorry! I have not been able to reproduce this issue again after last time, so it is not a problem to close the ticket.
