### ISSUE TITLE
[Bug]: "No OMEMO-keys found" on all contacts that use OMEMO

### ISSUE THREAD

**Issue by VWarte** [monal-im/Monal#928]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.7.7

### iOS Monal version

5.4.4 (845)

### Used XMPP server (domain)

jabber.wirtschaftstools.de

### Which XMPP-Server software are you using?

openfire

### XMPP Server Software Version

4.7.5

### How many accounts are you using in Monal?

1

### What happened?

Just installed Monal and logged in with my XMPP account. As soon as I open a chat with one of my contacts, I get the message:

No OMEMO-key found. This contact supports no OMEMO-enrypted messages. Please try again in a couple of seconds.

I've tested it with 3 of my contacts, 2 of them use Conversations on Android, one is using Gajim on Linux. Every single of this contacts supports OMEMO and there were no problems with OMEMO messages when I was using Conversations on Android. Also, all contacts use the same server running Openfire.

If I open the profile of a contact und look under keys, there are no keys listed.

I have tested other iOS XMPP clients (ChatSecure, Snikket), and OMEMO works everywhere besides in Monal. I've also tried the suggestions (flight mode, reset OMEMO, etc.).

What may be the issue here?

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Monal 5.4.4 is known to work with both, prosody and ejabberd. I guess openfire is lacking some modern pep/pubsub feature monal is relying on.

That said: please try the current beta. We did a complete rewrite of the OMEMO code and it might well be, that the beta now works flawlessly even with openfire.

**Comment by FriedrichAltheide** [comment]
No response. Closing
