### ISSUE TITLE
[Bug]: Unable to manually accept second OMEMO key

### ISSUE THREAD

**Issue by zak333** [monal-im/Monal#931]
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

jabber.de

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Situation:
- Contact uses (at least) two OMEMO keys (for example from Conversations and Gajim)
- Both keys are stored and verified in the contacts' Conversations device and were scanned using the QR code.
- The QR code contains both keys in the format: `xmpp:user@host?omemo-sid-XXXXX=key1;omemo-sid-YYYYY=key2`
- This QR code was scanned using Monal.

Result:
- The first key was verified.
- The second key was *not* verified.
- I was not able to manually accept the second key in Monal. The switch changed between left/untrusted and middle(/possibly trusted?) but without any effect.
- Right now the contact cannot send OMEMO encrypted messages from the second device to Monal. Only the following error message is written (german version):

> Beim Entschlüsseln dieser verschlüsselten Nachricht ist ein Fehler aufgetreten (Signalfehler). Versuche, eine verschlüsselte Nachricht an diese Person zu beheben. (Error Domain=org.whispersystems.SignalProtocol Code=12 "Untrusted Identity" UserInfo={NSLocalizedDescription=Untrusted Identity})

Expected:
- Monal should verify all the keys in the QR code.
- It should be possible to manually accept both keys, so messages will be shown and decrypted without error.

Note: I do not use Monal myself but open this issue for a friend.

Thank you!

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Please try the current beta release, the issue might be solved there.

**Comment by zak333** [comment]
Thank you. As I mentioned I do not have an iOS device myself and my friend will not install the beta version.

When the next stable version is out I will check if the problems are solved and report back here.

**Comment by zak333** [comment]
I tested this with Monal 6.0 and both of my keys were already verified now after the update.
I tried re-scanning the keys but the camera icon in the top bar did nothing, maybe this is another bug?
Showing the QR code worked.

For me the issue can be closed. I will do this.

Thank you.
