### ISSUE TITLE
[Bug]: Excess notifications

### ISSUE THREAD

**Issue by glitterbonegirl92** [monal-im/Monal#933]
### What Monal Release channel are you using?

AppStore

### iOS system version

16.6

### iOS Monal version

5.4.4

### Used XMPP server (domain)

conversations.im

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Hi there, I'm getting excess notifications from the app – up to five for a single action by another user. Thanks!

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Could you please give an example? What exactly is shown up to 5 times?

**Comment by glitterbonegirl92** [comment]
Hi, I'm not sure what changed, but I'm getting the right number of notifications now! That was strange. Thank you for responding!

**Comment by FriedrichAltheide** [comment]
We still have no idea what you are referring to.

**Comment by glitterbonegirl92** [comment]
That makes several of us! 😅
