### ISSUE TITLE
[Bug]: Monal alpha leaking / filling SSD

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#935]
### What Monal Release channel are you using?

Alpha

### macOS system version

13.5.1

### macOS Monal version

ID: c541d69bc03e0a4784fa57d91054432ca798022c Timestamp: 2023-08-27T15:12:46+02:00 Fix mam query bug

### Used XMPP server (domain)

disroot.org

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

3

### What happened?

Monal alpha crashed on open https://github.com/monal-im/Monal/issues/934 and then keept writing files to SSD until macoS spit out a warning about disk space.

With only a few GBs left I looked at activity manager but monal alpha was not running. Restarted system but disk space kept decreasing.

On uninstall of Monal alpha notived that AppCleaner showed one related folder with ovver 130 GB of data.

### Anything else?

Not sure how bad this could have gone. If Monal alpha keeps writing stuff this could certainly bring users into an unusable state with macOS. So this is a rather severe issue.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
I think I know what happened: on each crash a copy of the logfile was created to be sent within the crashreport. But crashreports will only be sent (and deleted afterwards) if you open the app, so all these crashreports containing big logfiles piled up and filled your ssd.

Definitely something to fix before releasing a new stable build. Maybe restrict the number of open crash reports to 5 or so.

**Comment by foss-** [comment]
I can confirm this. At one opening I was asked whether to send logs or not. I opted for sending the logs and a mail (in-app) was created with 5 log files.

There is another problem with this form of mail (instead of opening a new draft in mail app, at least on macOS), that the logs can not be dragged from draft to desktop to extract them and provide them on other means than email. But that should be a separate issue.

**Comment by tmolitor-stud-tu** [comment]
Did you send these 5 crashlogs? I did not receive them, but those would have been super helpful.

**Comment by foss-** [comment]
No, don't want to send logs via email. And dragging them to desktop did not work. Obviously emailing them to myself and then providing the log may have worked.
