### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fjrider** [monal-im/Monal#940]
### What Monal Release channel are you using?

AppStore

### iOS system version

16.6

### iOS Monal version

5.4.4

### Used XMPP server (domain)

Snikket.chat

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Monal app keeps crashing, using JMP.Chat account on snikket.chat instance

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
To look into that issue, I need you to send us a logfile via mail to info@monal-im.org
See here for an explanation how to export a logfile: https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging

Please tell us at least one timestamp of a crash, too (the logfiles can grow really large and without a timestamp it's like searching the needle in a haystack).

**Comment by FriedrichAltheide** [comment]
No mail/response within 3 weeks, closing
