### ISSUE TITLE
[Bug]: Dino/Movim audio call issues

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#945]
### What Monal Release channel are you using?

Beta

### iOS system version

16.6

### iOS Monal version

6.0 (863)

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

4

### What happened?

First, congratulations for the audio calls!
They work fine between Monal and Conversations/Beagle im
When initiating a call from Monal to Dino, it works fine.

When I do the opposite, i.e. initiate a call from Dino, and accept it in Monal, the latter says `connecting` for a little bit then `Call ended: application error`, while the former gets stuck in Calling/ringing until I manually cancel the call.
(After the call ends on monal's side, sometimes I get a notification from iOS: `"Monal - XMPP chat" crashed. Do you like to share additional information with the developer?`
This crash notification is more likely to happen if Monal was in the background and the screen was locked when the phone received the call. Especially if I open the app afterwards.
I already shared such a crash report yesterday)

Establishing a call to Movim, I get `Call ended: application error` on Monal, whereas Movim is stuck on `...connecting`
Accepting a call from Movim, I get call failed on Monal, while Movim is stuck on `...ringing` (with the cancel button disabled, and its color changed to green. I think Movim is stuck trying to connect)
While on Movim, If I cancel a outgoing call (both when using the cancel button and when closing the call window. And in both cases without doing anything on Monal's side), Monal doesn't stop ringing.

For the sake of comparison, Conversations <-> Dino calls work fine for me in both directions, but Conversations <-> Movim calls are broken. Though in that case Movim _doesn't get stuck in its call state._

For reference, I get `App failure` on Conversations, and `call ended` on Movim, in both call directions.
It's likely there's some issue on Movim's end.

### Anything else?

Note that both devices tested were in the same local network, So turn/stun shouldn't be involved.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by germanicianus** [comment]
@lissine0, did you also test the MacOS Monal version? I just launched the Alpha 6.0 of yesterday and don't have any means of initiating an audio/video call. The Android client blabber.im of my contact has also no means of initiating an audio/video call with me despite he can do so with another contact.

That's only a case of _not implemented yet for MacOS Monal_, correct @tmolitor-stud-tu or @FriedrichAltheide?

Side-note: Monal is currently available in the AppStore of China.
https://apps.apple.com/cn/developer/molitor-und-dietzel-inh-thilo-molitor/id1508738269
Keep in mind that CallKit is not allowed to be used in apps published in the China AppStore.
https://support.dolby.io/hc/en-au/articles/1500007496422-iOS-App-approval-CallKit-in-China-region

**Comment by tmolitor-stud-tu** [comment]
Yes, callkit does not work on macos and until apple fixes that, we don't support calls on macos.

Regarding china: calls are disabled for china already.

**Comment by tmolitor-stud-tu** [comment]
@lissine0 we are currently fixing the dino issue, but I'm not sure if I'll fix the movim issue.

**Comment by lissine0** [comment]
> callkit does not work on macos

But BeagleIM has working calls. Don't they use CallKit?
> @lissine0 we are currently fixing the dino issue, but I'm not sure if I'll fix the movim issue.

Thanks, but could you reproduce the movim issue?

**Comment by tmolitor-stud-tu** [comment]
No, they don't use callkit for macos and not using callkit would be significatly more work on our side.

**Comment by tmolitor-stud-tu** [comment]
No I did not test movim

**Comment by lissine0** [comment]
About the movim problem, these may be relevant: https://codeberg.org/iNPUTmice/Conversations/commit/6660877 (issue https://github.com/movim/movim/issues/1231)
and https://github.com/movim/movim/issues/1233

**Comment by tmolitor-stud-tu** [comment]
Yes, once movim solves these, calls with movim should work.
Dino is already fixed in the current beta.
