### ISSUE TITLE
[Documentation]: update Building Monal wiki page for rust related steps

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#948]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Since Monal is now using rust for the sdp-to-jingle mapper (https://github.com/monal-im/Monal/commit/d46c875), the [Building Monal wiki page](https://github.com/monal-im/Monal/wiki/Building-Monal) should be updated.
For me, the extra steps were the following: (before starting a monal build in xcode)

1. Install rustup by running `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` as mentioned in https://www.rust-lang.org/tools/install
2. Assuming we're in monal's source directory, run `chmod +x rust/build-rust.sh` to make the script executable, And `./rust/build-rust.sh` to run it.
3. In my case, the script didn't finish successfully. I had the following error:
`error: failed to get iphoneos SDK path: process exit with error: xcrun: error: SDK "iphoneos" cannot be located
       xcrun: error: SDK "iphoneos" cannot be located
       xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'`
So I followed the first answer in https://stackoverflow.com/questions/68565356/xcrun-error-sdk-iphoneos-cannot-be-located
4. Open the Monal project in Xcode. This can be done by running `open Monal/Monal.xcworkspace` as mentioned in [Building Monal](https://github.com/monal-im/Monal/wiki/Building-Monal).
5. Add LibMonalRustSwiftBridge as a local project: In Xcode, go to File -> Add packages... -> Add local ; Select the rust/LibMonalRustSwiftBridge directory under Monal's source tree. Make sure that Monal is selected in `Add to project` and finally add the package.

**Comment by tmolitor-stud-tu** [comment]
Updated https://github.com/monal-im/Monal/wiki/Building-Monal

**Comment by lissine0** [comment]
Sorry for being pedantic, but could you please improve the formatting of the error message by making it in a multiline code block?
```
error: failed to get iphoneos SDK path: process exit with error: xcrun: error: SDK "iphoneos" cannot be located
    xcrun: error: SDK "iphoneos" cannot be located
    xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
```
Thanks :)
