### ISSUE TITLE
[Bug]: Audio calls edge case

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#952]
### What Monal Release channel are you using?

Beta

### iOS system version

16.6

### iOS Monal version

6.0 (865)

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

4

### What happened?

Say that I have two accounts, romeo@example.net and juliet@im.example.com, both of them logged in to the same Monal instance.  And say that juliet@im.example.com is also logged in on several other clients.
If I start a call on Monal, from romeo@ to juliet@, I have noticed the following:

- Conversations and Dino both hang up immediately.
- Monal (which started the call) remains in `Discovering devices...`
- BeagleIM and Movim keep ringing. But If I try to take the call using BeagleIM, it gets stuck `connecting...` and Monal is still stuck saying `Discovering devices...`

I asked about this in the xsf room (see the bottom of https://logs.xmpp.org/xsf/2023-10-03 in addition to https://logs.xmpp.org/xsf/2023-10-04). One theory is that juliet@ in Monal rejects the call, and thus Dino and Conversations stop ringing (because it was handled on another device). But if that's the case, shouldn't Monal (on romeo@ ) stop the outgoing call? 

Note that when I tested Conversations in this same scenario, I was able to take the call from other clients.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by licaon-kter** [comment]
Why would juliet@Monal reject the call?

**Comment by FriedrichAltheide** [comment]
@lissine0 Create a log file, compress the log file, and send us the log file along with a timestamp corresponding to the call attempt to info@monal-im.org.

**Comment by lissine0** [comment]
> Why would juliet@Monal reject the call?

Because Monal doesn't handle two simultaneous calls?
Imagine if you were in an audio call, and someone else calls you.
What would your client do in that case?
But the fact that juliet@Monal rejects the call is just a theory.

> @lissine0 Create a log file, compress the log file, and send us the log file along with a timestamp corresponding to the call attempt to [info@monal-im.org](mailto:info@monal-im.org).

Will do.

**Comment by licaon-kter** [comment]
"Both in the **same** Monal instance" ah, I didn't get that from the OP.

**Comment by lissine0** [comment]
yes, I'll make the OP clearer.

**Comment by tmolitor-stud-tu** [comment]
From static code analysis our current guess is, that CallKit has a flaw that gets triggered when a call is already started but not yet connected and another call gets reported to CallKit.
That could result in CallKit reporting an error which results in Monal rejecting the call.

Why the UI doesn't reflect this state change is open for debate. Could be an issue with the "both accounts in the same Monal instance", but we'll know more once the logfile arrives.

**Comment by tmolitor-stud-tu** [comment]
It was an issue with "both accounts in the same Monal instance".

**Comment by lissine0** [comment]
Confirmed fixed as of the latest alpha (https://github.com/monal-im/Monal/commit/e480f8562d437f73b7fd517bf0ac3fc2d6856807)
Thanks!
