### ISSUE TITLE
[Bug]: Connectivity errors when accepting a call from Dino 

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#953]
### What Monal Release channel are you using?

Beta

### iOS system version

16.6

### iOS Monal version

6.0 (865)

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

1

### What happened?

When accepting a call from Dino, most of the time, the two clients would try to connect for several seconds and then I get `Call ended: connection failed` on Monal and `The call has been terminated connectivity-error` on Dino.
On some rare occasions, it works.
Calls work reliably in the other direction, and so do Dino -> Conversations calls.
I emailed a log file.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by lissine0** [comment]
I forgot to mention, when I see `Call ended: connection failed`, there's a low chance that the call-error sound is played indefinitely in a loop.sound
It'd stop if I start playing audio. (not system sounds)
The logs I emailed correspond to a case of this happening.

**Comment by tmolitor-stud-tu** [comment]
the call-error sound is played until you close the call screen.

**Comment by lissine0** [comment]
Sometimes, it's played only once.
But when it's on loop, last time it only stopped when I opened the browser and started playing a video.
It can also stop if you do another call.

**Comment by lissine0** [comment]
Using the latest commit, the sound loops are gone.
But I don't hear the errorPlayer at all on call failures.
> Sometimes, it's played only once.

I only recall this happening once.
Perhaps I confused it with busyPlayer?
Anyway, the point is, the errorPlayer didn't work most of the time in the past.

Note: ringing and busyPlayer work okay on latest commit.

**Comment by tmolitor-stud-tu** [comment]
what dino version are you using? my dino and monal alpha work just fine in both directions...

**Comment by lissine0** [comment]
I'm using Dino 0.4.3
I can reproduce this with high consistency.
Try many Dino -> Monal calls in a row.

**Comment by tmolitor-stud-tu** [comment]
I already tested ~6 calls now, it never happened. same dino version, latest monal alpha
