### ISSUE TITLE
[Bug]: edited messages in MUCs appear duplicated

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#956]
### What Monal Release channel are you using?

Alpha

### iOS system version

16.7

### iOS Monal version

6.0 (commit 0a908b6)

### Used XMPP server (domain)

personal server

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.4

### How many accounts are you using in Monal?

2

### What happened?

If I edit a message in a public channel, it gets corrected but I also see a duplicate one just below it. (my other online clients don't see any duplication)
With private group chats, it's the same thing, except that the duplicate message can't be decrypted.

This might be relevant: https://github.com/monal-im/Monal/issues/941

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by MYEUHD** [comment]
This was only fixed for omemo encrypted messages in group chats.
For unencrypted messages, whether in a private group chat or a public channel, the issue still happens.

**Comment by lissine0** [comment]
This was only fixed for omemo encrypted messages in group chats.
For unencrypted messages, whether in a private group chat or a public channel, the issue still happens.

**Comment by tmolitor-stud-tu** [comment]
Dies it persist if you close the app and reopen it?

**Comment by lissine0** [comment]
> Does it persist if you close the app and reopen it?

Yes.
And to be clear, the message duplication only appears on the author's monal instance, but not on their other clients or for other members.

Also, I can always reproduce this on public channels (with both prosody and ejabberd accounts and on both prosody and ejabberd MUC servers)
But on private group chats, I can reproduce it with my prosody (admin) account but not with another prosody account or an ejabberd account (regardless of the MUC server)

**Comment by tmolitor-stud-tu** [comment]
Can you test it with the current beta build? I've changed the matching to use occupant ids in mucs and that could have solved it.

**Comment by lissine0** [comment]
I'm already using the latest beta build :)
These observations https://github.com/monal-im/Monal/issues/956#issuecomment-2241151967 are for 6.4.1rc2 (919)

**Comment by lissine0** [comment]
I have just tried https://github.com/monal-im/Monal/commit/a4fc7d4f0bed7fa9d698e4a9018d38baf1efc98e
Unfortunately, the issue isn't fixed for public channels.
However, it seems to be fixed for private group chats.

**Comment by tmolitor-stud-tu** [comment]
Fixed in latest beta and alpha
