### ISSUE TITLE
[Bug]: The first start of the app stops the playback of music e.g. from spotify 

### ISSUE THREAD

**Issue by chschwerdt** [monal-im/Monal#964]
### What Monal Release channel are you using?

AppStore

### iOS system version

17.0.3

### iOS Monal version

6.0 (869)

### Used XMPP server (domain)

X.y.z

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

1. Open Spotify 
2. Play music
3. Open Monal
4. Music stops

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please submit a PR.
