### ISSUE TITLE
[Bug]: After new update, Monal hangs when opening file picker

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [monal-im/Monal#965]
### What Monal Release channel are you using?

AppStore

### macOS system version

12.2.1

### macOS Monal version

6.0 (869)

### Used XMPP server (domain)

.

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

After the update, when I open the attachment picker via the paperclip icon -> file, monal stops responding. After a while I may be select a file but the dialog is extremely laggy. The problem resolves once this dialog goes away.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
The file picker is just the native dialog provided by Apple (UIDocumentPickerViewController). 

@FriedrichAltheide does this hang on up to date macOS versions, too?

**Comment by FriedrichAltheide** [comment]
On a modern macOS version it works just fine.

**Comment by tmolitor-stud-tu** [comment]
Okay, I'm closing this as wontfix then.
