### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MohsinKhan007** [monal-im/Monal#966]
### What Monal Release channel are you using?

AppStore

### iOS system version

16.4.1

### iOS Monal version

6.0

### Used XMPP server (domain)

mohsin@xmpp.urkob.com

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

1.12.1

### How many accounts are you using in Monal?

1

### What happened?

the issue is with notifications. I cannot receive notification when the app is closed. I updated from the previous version but in no vain. Many times, there is an emergency situation and still It only works when I open the app my my self

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please update your prosody server to a recent version.
Further, update your prosody community modules to a recent version as stated in https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins .
Afterwards push should work.
