### ISSUE TITLE
[Bug]: Monal does not start --  Symbol not found: _OBJC_CLASS_$_UNNotificationActionIcon

### ISSUE THREAD

**Issue by Tang101719** [monal-im/Monal#967]
### What Monal Release channel are you using?

AppStore

### macOS system version

11.2.2

### macOS Monal version

6.0

### Used XMPP server (domain)

yax.im

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

Monal does not start anymore.

### Anything else?

Process:               Monal [51131]
Path:                  /Applications/Monal.app/Contents/MacOS/Monal
Identifier:            Monal
Version:               6.0 (869)
App Item ID:           1637078500
App External ID:       860708036
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Monal [51131]
User ID:               501

Date/Time:             2023-10-31 09:20:12.384 +0100
OS Version:            macOS 11.2.2 (20D80)
Report Version:        12
Anonymous UUID:        6C72828B-2BE8-EAEC-76C5-1D27B7DB9B3C

Sleep/Wake UUID:       36E239BB-1204-4B56-8E2E-956BFFDBFA0D

Time Awake Since Boot: 370000 seconds
Time Since Wake:       1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_UNNotificationActionIcon
  Referenced from: /Applications/Monal.app/Contents/MacOS/Monal (which was built for Mac OS X 14.0)
  Expected in: /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
Please update at least to macOS 11.7 and then try again.

**Comment by Tang101719** [comment]
> Please update at least to macOS 11.7 and then try again.
Still doesn't work....

Process:               Monal [2248]
Path:                  /Applications/Monal.app/Contents/MacOS/Monal
Identifier:            Monal
Version:               6.0 (869)
App Item ID:           1637078500
App External ID:       860708036
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Monal [2248]
User ID:               501

Date/Time:             2023-10-31 12:36:07.041 +0100
OS Version:            macOS 11.7.10 (20G1427)
Report Version:        12
Anonymous UUID:        6C72828B-2BE8-EAEC-76C5-1D27B7DB9B3C

Sleep/Wake UUID:       72FE378B-D586-4D60-96B6-7878A7161FA7

Time Awake Since Boot: 880 seconds
Time Since Wake:       150 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_UNNotificationActionIcon
  Referenced from: /Applications/Monal.app/Contents/MacOS/Monal (which was built for Mac OS X 14.0)
  Expected in: /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications

**Comment by FriedrichAltheide** [comment]
Please check if you can start the latest monal alpha release

**Comment by FriedrichAltheide** [comment]
Correction: The alpha CI is still running, wait 20min and then download the latest monal alpha release (https://github.com/monal-im/monal#releases) and check if it starts

**Comment by Tang101719** [comment]
The alpha build works for me. Thanks

**Comment by FriedrichAltheide** [comment]
Fixed in latest beta
