### ISSUE TITLE
[Feature]: Photo sending compression options

### ISSUE THREAD

**Issue by distefam** [monal-im/Monal#968]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

When selecting a photo to send on iOS, Monal sends the full-resolution image. Many other XMPP clients (Conversations on Android, and Snikket on iOS, for example), send a compressed version of the photo when sending a photo and only send the full-resolution photo when sending it as a file attachment.

It would be nice to be able to set this at the application preferences level.

**Comment by FriedrichAltheide** [comment]
The compression can be changed in the monal privacy settings. I agree that current section title and settings name is not ideal. Hence your are more than welcome to provide a PR :)

**Comment by distefam** [comment]
> The compression can be changed in the monal privacy settings.

I just checked and while there is a setting called "Auto-Download Media Settings" it seems only to apply to files that are _received_ rather than _sent_. The reason that it is important to be able to limit the file sizes of images when sending is to keep them under the MMS limit (generally around 3MB) for use with JMP.chat.

**Comment by FriedrichAltheide** [comment]
The section also contains a compress ratio slider that will apply to uploads. As I said, the section title is misleading.

**Comment by distefam** [comment]
Ah, I didn't realize that. Just tried and it works, thank you for the help.
