### ISSUE TITLE
[Feature]: Icons in `Contacts` view should use the same size

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#972]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

**Currrently**

The two icons in the top right use different size, resulting in an inconsistent look. `Contact Requests` icon is slightly smaller than `Add Contact of Channel` icon.
![1](https://github.com/monal-im/Monal/assets/5708172/550822a1-e93b-4d24-a475-830ac455b86d)

**Expected**

Icons should use same size. I'd prefer if the size of the first icon was increased as it already is very small and hard to see.

**Comment by tmolitor-stud-tu** [comment]
That's a limitation of UIKit, will be fixed when switching to SwiftUI for this view (that might be just around the corner)

**Comment by foss-** [comment]
With the addition of a third icon it becomes obvious icons are correctly aligned:

![1](https://github.com/monal-im/Monal/assets/5708172/78bef2c9-6c4b-493e-aade-94c687c1cdbb)

Closing.
