### ISSUE TITLE
[Bug]: monal user frequently loses connection to ejabberd. Connection returns only when user consults Monal again

### ISSUE THREAD

**Issue by znoteer** [monal-im/Monal#977]
### What Monal Release channel are you using?

AppStore

### iOS system version

17?

### iOS Monal version

6

### macOS system version

n/a

### macOS Monal version

n/a

### Used XMPP server (domain)

<mybox>.fbx.one

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

23.01-1 (Debian Stable)

### How many accounts are you using in Monal?

1

### What happened?

This report is being made by an Android and Linux user who admins an ejabberd server on behalf of a monal user on that server.

The monal user keeps disappearing from the apps of other users. For example, in Dino the chat with the Monal user has greyed out avatars. No messages are sendable. They appear in the conversation but get no checkmark and are never received by the Monal user even when their connexion returns. They get, therefore, no notification of a message.

A connexion is only re-established when the Monal user brings the app to the fore on their phone.

I'm submitting logs from the server. I've cleaned out most of the messages relative to other private and mu chats. I've left a few in just to show that things function normally for other users and channels. I don't see any errors, so there isn't much I can point to in the logs except to point to some timestamps where things happened.

The file begins with several instances of attempting to connect user nate to the server which end with "closing c2s connection...Connection failed...waiting 300 seconds". At 20:41 on 2023-11-15 nate is asked throught non-XMPP channels to look for messages in Monal. That immediately starts some connection activity in the logs.

At 21:00 gerry sends nate a message, then 3 more at 21:01. Nothing further happens with regards to nate until 2023-11-16 when nate sends gerry 2 messages, an image and then another message at 14:45, :46, :46 and :47. 

I've inserted 2 blank lines in the logs at each of these two points to make them easier to spot.

As I said above, to my inexperienced eyes, nothing appears particularly wrong in the log messages themselves. But, in sanitising the output I did notice one strange thing that could possible impact nate's connexion. That thing is that nate changes IP addresses very frequently.

Please advise if further information is required
[monal-disappearing.txt](https://github.com/monal-im/Monal/files/13396070/monal-disappearing.txt)

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by licaon-kter** [comment]
Yes, that might be expected, as Apple wants to kill the app, but your messages should trigger push messages that wake up the app.

You checked the boxes that you've read the Wiki, you actually did? There's advice there about ejabberd version, setup, etc. And about Monal setup...

You can't compare with Android or Linux. :)

Please mention what settings Monal has toggled on. The Push screen is all green? Background Sync is on? Notifications? The ejabberd logs have "Enabling push for" this user? Etc

**Comment by FriedrichAltheide** [comment]
1.	You are using a non-recommended version of ejabberd. Use 23.10 as it fixes a possible push bug.
2.	You redacted your XMPP domain.
    a.	How can I check our push server now?
    b.	How can I check now if you have configured the SRV records as advised?
    c.	How can I check now that you have direct TLS enabled as recommended?
    d.	How can I check now that you have configured v4 and v6?
3.	Your ejabberd log only contains info logging.
4.	Your stream resumption is 300 seconds vs our advised 24 hours --> you presumably have not read the “Considerations for XMPP server admins”


Check if your issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins). If not, reopen the ticket.
