### ISSUE TITLE
Add custom sounds choices / control for different senders

### ISSUE THREAD

**Issue by citbr** [monal-im/Monal#98]
It appears that Apple's official Messages program keeps losing functionality with MacOS upgrades, the latest thing to go was the "AppleScript handler" option that could be used with an AppleScript to trigger custom sounds depending on which of your contacts was sending you a message.  So now I am looking at other options and I ran across Monal, which looks like it could replace Messages but I just need to know if there is any way to use custom sounds for new message notifications that can be set according to the sender.  For certain important people I want to use a "wake the dead" alarm bell sound while for those people who insist on sending useless links at 3 AM I want to use a very soft alert sound.  Can Monal do this now?  And if not, would you consider adding this capability?

**Comment by anurodhp** [comment]
Hi, 
I don’t have custom notifications but  it  is something I’ve been planning. I wasn’t familiar with the use case you’ve described but it makes a lot of sense.  It’s low hanging fruit, I’ll add it to my the roadmap.

**Comment by OPNComet** [comment]
Thank you, much appreciated.

**Comment by citbr** [comment]
Thank you.  Much appreciated!

**Comment by anurodhp** [comment]
Following up on this, I've added custom sounds to the app. I will add custom sounds based on sender in a future update.

**Comment by DanScharon** [comment]
would be nice if one could also add/choose own custom sounds

**Comment by tmolitor-stud-tu** [comment]
Closed in favor of #991
