### ISSUE TITLE
MUC: following an invitation is broken

### ISSUE THREAD

**Issue by ge0rg** [monal-im/Monal#99]
When you follow a MUC invitation ("Chat Invite") dialog, it will join with the nickname "test". The joined MUC does not appear on the "Group" tab in the app, but only in "Chats".

It also looks like the join isn't properly registered; Monal shows all incoming messages without a nickname in the chat tab.

Suggested behavior:
- show the username/nickname of the inviter in the invitation, both direct and mediated
- open the "Edit Group Chat" dialog, prefilled with the invitation data, when tapping "Join"
- maybe: do not leave the invitation message from the bare JID in the chatroom log

**Comment by Echolon** [comment]
Hi @ge0rg 

is this still persistent?

**Comment by unriccio** [comment]
This still happens, I saw it with the current iOS stable version (4.7) and MacOS beta (.zip file).

To reproduce:
1. create a MUC with Conversations
2. invite a Monal user
3. Monal opens the MUC as a normal 1-1 chat with the MUC jid (and not as a group chat)
(so they will receive the messages sent to the MUC but each time they try to send something they receive an "Error:cancel - service-unavailable")

Thanks!

**Comment by Echolon** [comment]
Yes this is known. There is lots of working going into the backend and we will take care on this!

Thanks for confirming!

**Comment by tmolitor-stud-tu** [comment]
fixed now
