### ISSUE TITLE
[Feature]: Rewrite debug menu using SwiftUI

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#990]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Rewrite the debug menu to contain at least the following:

1. The current text fields and the switch for configuring the UDP-logger
2. A list of current logfiles ordered by date (newest first) and a way to export (e.g. share) them
3. A button to export the database
4. A few buttons to trigger crashes like in the current debug menu

**Comment by mosliem** [comment]
Hello @tmolitor-stud-tu  i 'd like to work on this issue

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by tmolitor-stud-tu** [comment]
Nothing happened in 2 weeks, I'll remove the assignment to make it possible for other gsoc applicant to complete this task.

**Comment by vednp** [comment]
Hi @tmolitor-stud-tu can I work on it?

**Comment by tmolitor-stud-tu** [comment]
@vednp I just saw that you did not yet complete (or even got assigned) any of the short gsoc teaser tasks. Please complete two of these first, before starting to work on one of the bigger tasks.
I removed your assignment to this issue for now.

I'm sorry I did not realize this before.

Short teaser tasks: https://github.com/monal-im/Monal/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8E%83+Short+GSOC+Teaser%22
Wiki entry explaining the application process: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by zainashraf1562** [comment]
Gsoc Applicant: I would like to work on this issue.
