### ISSUE TITLE
[Feature]: Rewrite the privacy settings UI using SwiftUI

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/Monal#993]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Rewrite the current privacy settings UI using SwiftUI.

Possibly the different settings in there should be split into different settings pages rather than one like it's currently implemented.

Every setting should be accompanied by an explanatory text for better UX.

**Comment by guodong323** [comment]
I hope this message finds you well. I am reaching out as I am eager to participate in Monal's Google Summer of Code 2024 project this year. To prepare adequately, Could you please assign me to tasks related to the Monal project? I am committed to delivering my best and will adhere to all guidelines and requirements.
By the way, Would it be possible for you to provide specific UI designs or relevant design documentation? Having clear guidance will greatly assist me in refactoring the project. If such resources are unavailable, I am prepared to work with the existing UI structure and utilize SwiftUI for the refactoring process.
Thank you for your patience and support. I am eager to contribute to the Monal project and showcase my skills and potential in Google Summer of Code.

**Comment by mosliem** [comment]
Hello @tmolitor-stud-tu  
i 'd like to work on this issue 
can you assign it to me?

**Comment by thevaidik** [comment]
Hey Vaidik here  , i am working on this issue, it would be good if i can be assigned. 
@tmolitor-stud-tu

**Comment by tmolitor-stud-tu** [comment]
Unfortunately @thevaidik was the first one to ask for this issue (via 1:1 chat) so they are assigned now.

**Comment by tmolitor-stud-tu** [comment]
For all interested in participating in GSOC, I wrote a quick "how to" checklist over at our wiki: https://github.com/monal-im/Monal/wiki/GSOC-2024-Guidline

**Comment by vednp** [comment]
Hey @tmolitor-stud-tu, if it is still open can I work on it?
