### ISSUE TITLE
[Bug]: Monal 6.1.0 app crashes IOS 17.3

### ISSUE THREAD

**Issue by madfoss** [monal-im/Monal#999]
### What Monal Release channel are you using?

AppStore

### iOS system version

17.3

### iOS Monal version

6.1.0

### Used XMPP server (domain)

Prosody

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

After updating to Monal 6.1.0, the app crashes immediately after starting.
iPhone 13 mini, IOS 17.3

The same applies to an older iPhone XS with IOS 16. After installing Monal 6.1.0 and logging into an account, the app works. But as soon as you try to make a call the app crashes, even if the XMPP server does not support calls. The Monal app then crashes immediately after starting.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
That's suboptimal. Are you asked to send a crash report before the app crashes again?
Can you turn on flight mode and then try to start Monal? Will it crash in this case?

It would be *very* helpful if you could export a logfile and/or send a crash report.
You can compress the logfile and send it via mail to info@monal-im.org.

How to export a logfile: https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging

**Comment by madfoss** [comment]
> Are you asked to send a crash report before the app crashes again?

No, the app will close immediately.

> Can you turn on flight mode and then try to start Monal? Will it crash in this case?

Yes, even when flight mode is switched on, the app crashes immediately.

A friend just called me and said the same thing, after updating to 6.1.0 the app crashes (iPhone 12, IOS 17.3).
So far he has also used the call function without any problems.

**Comment by tmolitor-stud-tu** [comment]
oh that's bad.
can you contact me via xmpp under thilo.molitor@juforum.de to debug this further?

I'm thinking of using the udp logger to extract logmessages of the crash, but that only works if the logger has been configured and activated in monal prior to the crash.

**Comment by tmolitor-stud-tu** [comment]
Given that you are the only one reporting these crashes so far, maybe the combination of your server and Monal is causing this.

Do you use a public server or a self hosted one? If it's a public one, what domain is it? If it's a self hosted one: what software and version are you running?

**Comment by tmolitor-stud-tu** [comment]
Another question: did you use Monal beta once and switched back to stable? And if so: when did you switch back?

**Comment by tmolitor-stud-tu** [comment]
I got another user having the same problem.
They was kind enough to give me access to live debugging their app and I got a crashlog.
The fix is coming soon (pending apple review).

**Comment by madfoss** [comment]
Works with Monal version 6.1.1, thanks!
